### ISSUE TITLE
warp test suite fails when run in container environment

### ISSUE THREAD

**Issue by peti** [yesodweb/wai#205]
NixOS runs all builds in a chroot container that doesn't have network access to guarantee that build results are reproducible. The latest version of warp fails its test suite in that environment: see http://hydra.cryp.to/build/27363/nixlog/4/raw for a complete build log.

To remedy the situation, the entire test suite has been disabled, which is unsatisfactory. Would it be possible to split the test suite into two parts: one that accesses the network and one that doesn't (like the `dns` package does)? Then we could still run the pure tests.

**Comment by snoyberg** [comment]
No response to previous question, closing as cannot reproduce
