### ISSUE TITLE
Caching issue with wai-app-static

### ISSUE THREAD

**Issue by hdgarrood** [yesodweb/wai#210]
With the following application:

```haskell
{-# Language OverloadedStrings #-}
import Network.Wai
import Network.Wai.Handler.Warp
import Network.Wai.Application.Static

app :: Application
app = staticApp $ defaultFileServerSettings "."

main :: IO ()
main = run 3001 app
```

I do the following:
```
$ echo "hello world" > test.txt
$ curl http://localhost:3001/test.txt
hello world
```
So far, so good. Now open test.txt in Vim, delete the word "hello", and save.
```
$ curl http://localhost:3001/test.txt
hello 
```
However, test.txt now just contains "world\n"
Looking at the headers with `curl -v`, the `Content-Length` does get updated correctly, but it seems to be serving the wrong content.

See also https://github.com/scotty-web/scotty/issues/55
Could this be an issue with FD reuse?

**Comment by kazu-yamamoto** [comment]
Now the duration is 0 by default. Let's close.
