### ISSUE TITLE
wai-websockets, missing query string in http request

### ISSUE THREAD

**Issue by kosmoskatten** [yesodweb/wai#217]
Hi @banacorn and others!

The Http request contains a query string (e.g. /foo?bar=123) but when the application handler inspects the pending request only the path part (i.e. /foo) is available.

In Wai's intercept handler for WebSocket requests, only the path part is taken  from Wai's request record (rawPathInfo), but not the query string (rawQueryString). I guess that both those parts should be concatenated before invoking the application handler.

Cheers,
  --patrik

**Comment by snoyberg** [comment]
I believe this has since been resolved.
