### ISSUE TITLE
setPort/settingsPort deprecation

### ISSUE THREAD

**Issue by xich** [yesodweb/wai#233]
The most recent warp deprecates `settingsPort` (and the other record selectors of `Settings`) in favor of new setter functions like `setPort`. However, there don't seem to be any new getter functions. For instance, I'd like to use `defaultSettings` and then figure out what port the server started on to report it to the user, in the case they haven't explicitly specified a port.

I can do this with `settingsPort` itself, but I get a deprecation notice when I compile, and I'd rather not upload a package that depends on deprecated functions. Thoughts on creating some getters, or un-deprecating the selectors?

**Comment by kazu-yamamoto** [comment]
It seems to me that this issue has been resolved. Let's close.
