### ISSUE TITLE
Gzip middleware cache should index by etag as well

### ISSUE THREAD

**Issue by meteficha** [yesodweb/wai#243]
Hi! =)

If I'm reading the code correctly, right now the gzip middleware may serve stale data from the gzip cache since it only takes the filename into account.  Its etag, if available on the response header, should be used as well, right?

**Comment by kanishka-azimi** [comment]
Current progress, next steps?

**Comment by Vlix** [comment]
I feel like taking a jab at the GZip middleware. Any objections? (since this issue is a bit old)

**Comment by snoyberg** [comment]
No objection from me.

**Comment by Vlix** [comment]
First draft made in #875

**Comment by Vlix** [comment]
I found a bunch of subtle edge cases and I'm making this Middleware a bit more robust before I add the ETag functionality.
I think I'm done with the extra checks and tweaks in handling headers, but I still want to add some tests for what is testable with this Middleware. Hope make a PR before end of next week.

**Comment by Vlix** [comment]
Second step in #880 , new and improved `gzip` middleware. After this, I'll actually add the ETag functionality 😅

**Comment by Vlix** [comment]
Implemented with #885
