### ISSUE TITLE
TechEmpower's Web Framework Benchmarks

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#246]
GHC 7.8.2 has come. How can we ask this benchmark to use GHC 7.8.2?

@gregwebs I think "-A4M" is small. (I'm not sure the capital letter "M" is correct.)  "-A32m" should be enough. Moreover, "-qa" would help to improve the performance.

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/wai/setup.py

**Comment by flip111** [comment]
wai is quite low in all benchmarks, often getting out performed by ruby, python, js, php solutions. Is this inherit to haskell itself ?

**Comment by snoyberg** [comment]
Probably not. I gave up trying to get those benchmarks to perform correctly after wasting weeks trying to get a change merged in to use the correct compiler version. I haven't bothered fixing or even looking at the benchmarks since then. The other thing that has historically always hurt the benchmarks is that our database libraries are not performant, but that's also not inherent to Haskell.

**Comment by flip111** [comment]
I believe stack can be used now. Could just try make it stack based on the latest lts. I think there are a few benchmarks that don't involve the database such as json serialization and plain-text.

**Comment by snoyberg** [comment]
If you'd like to work on getting that changed, I'd support it, but I don't
have time to work on such a PR myself.

**Comment by flip111** [comment]
Ok it wasn't much work i created a PR here https://github.com/TechEmpower/FrameworkBenchmarks/pull/3149

I did some ghc profiling on one of my own projects once and made a nice html with profiteur. I could do that too for wai. It will obviously slow down the benchmarks but give an idea where most of the slowdown happens. I don't see myself optimizing wai at this point but i can probably generate the html if anyone is interested.

**Comment by snoyberg** [comment]
I'd certainly be interested in any benchmarking information you'd like to share. But a three year old closed issue may not be the best place to share it :). If you notice regressions, can you open a new issue?

**Comment by flip111** [comment]
@snoyberg since i was not able to run wai with lts-6.3 i don't know if there was a performance regression, we will have to wait till the next TFB benchmark i guess. Would you like that i open an issue for the trace in case i'm able to collect one?

**Comment by snoyberg** [comment]
I'm not sure what you mean by the trace.

**Comment by flip111** [comment]
@snoyberg i meant making a ghc profiling file and visualizing it with profiteur https://github.com/jaspervdj/profiteur#profiteur

**Comment by snoyberg** [comment]
Not sure how to answer, but: if you see evidence of a performance issue in
Warp, yes, please open an issue.
