### ISSUE TITLE
warp-tls and Godaddy certs

### ISSUE THREAD

**Issue by andrewthad** [yesodweb/wai#248]
I'm responsible for a website with an SSL cert (from Godaddy), and I am trying to get it working with warp-tls. On localhost, I've managed to generate a fake certificate with openssl, and it works fine. However, on the production server, I can't get the real cert to work. Possibly relevant certificate information from Godaddy's control panel is:
Type:Standard SSL
Private Key Length:2048 bits
Signature Algorithm:SHA-2
Also, there is a certificate chain file that you download with it, and I can't find a way to use this with warp-tls. I would appreciate any help that anyone can offer (or if putting it behind Nginx is the best solution, if someone could let me know that).

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
