### ISSUE TITLE
Install fails from hackage if older version of streaming-commons is present

### ISSUE THREAD

**Issue by andygill** [yesodweb/wai#264]
groundhog install of  fails out of the box.
  * It looks like I have  `streaming-commons-0.1.1`
  * `Data.Streaming.Blaze` did not appear until 0.1.2.

So, `streaming-commons` should be `streaming-commons >= 0.1.2`, perhaps?

        $ cabal install warp
        Resolving dependencies...
        Configuring warp-3.0.0.2...
        Building warp-3.0.0.2...
        Preprocessing library warp-3.0.0.2...

        Network/Wai/Handler/Warp/Response.hs:20:8:
            Could not find module ‘Data.Streaming.Blaze’
            Perhaps you meant
              Data.Streaming.Zlib (from streaming-commons-0.1.1)
              Data.Streaming.Text (from streaming-commons-0.1.1)
            Use -v to see a list of the files searched for.
        Failed to install warp-3.0.0.2
        cabal: Error: some packages failed to install:
        warp-3.0.0.2 failed during the building phase. The exception was:
        ExitFailure 1

**Comment by kazu-yamamoto** [comment]
Let's close this.
