### ISSUE TITLE
wai-websockets-example malfunctioning.

### ISSUE THREAD

**Issue by dschalk** [yesodweb/wai#271]
I fired up the wai-websockets server on my Ubuntu 14.04 box and loaded four browsers: Chrome, Firefox, Opera, and Arora.  The chat works as expected until I close any one of the browsers.  Closing any one browser brings the chat session to a halt for the remaining clients.  Their messages are no longer broadcast.

New clients can sign on.  They are prohibited from using existing names.  But their messages are not broadcast, and the receive no messages from the other clients.  All they receive is a list of clients.

After one browser closes, wai-websockets-example  ceases to support chat sessions.  It doesn't work again until it is re-booted.

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
