### ISSUE TITLE
warp-tls is vulnerable to insecure renegotiation

### ISSUE THREAD

**Issue by ptek** [yesodweb/wai#297]
https://www.ssllabs.com/ssltest/ shows that our warp-tls instance (service.global.de), is prone to MITM attacks because it supports "insecure renegotiation".

warp-tls == 3.0.0.1
tls == 1.2.13

**Comment by ygale** [comment]
@ptek first wrote:

> [vulnerable] because it supports "insecure renegotiation"

then wrote:

> vulnerable, because it actually does *not* support secure renegotiation

Those are two completely different claims. The first version is what I saw in a report on SSL Labs.

**Comment by kazu-yamamoto** [comment]
Let's close this in favor of https://github.com/vincenthz/hs-tls/issues/112.
