### ISSUE TITLE
changing the type of runSettingsConnectionMakerSecure

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#302]
The type of the second argument is `IO (Connection, Bool)` where `Bool` indicates whether or not TLS/SSL is used. This is not good enough for HTTP/2 because HTTP/2 requires:
- TLS/1.2
- Cipher level is TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 at least
- Application Layer Protocol Negotiation
-  Server Name Indication

These parameters should be checked before starting HTTP/2.
For this purpose, I would like to change `Bool` to, say,  `Maybe TLSContext` which includes enough information. `TLSContext` (or whatever) should be defined in the Warp module to not depend on the tls library.

Another option is to add a new member to `Connection`. (It seems to me that this is a kind of hack and is not elegant.)

@snoyberg What do you think?

**Comment by kazu-yamamoto** [comment]
This is done in 02e21202cbe80ec99a3a1f190475f7518b0c7787 on the master branch.
@snoyberg Please check.

**Comment by snoyberg** [comment]
LGTM
