### ISSUE TITLE
Warp: WebSockets get terminated after settingsTimeout

### ISSUE THREAD

**Issue by keynoru** [yesodweb/wai#310]
Warp sets timeout (default 30 seconds) to all incoming connections to fight attacks such as Slowloris. However, WebSocket connections are supposed to live longer than that - usually until the client user leaves the page. This problem makes Warp's WebSocket feature almost unusable.

Fighting Slowloris on a WebSocket shouldn't be based on the lifespan of a connection, as even a perfectly legitimate WebSocket connection may live for hours or even days. If a client makes a legitimate WebSocket request and the `Application` *responds* to this, the timeout that is put to this connection needs to be canceled.

There doesn't seem to be a way for a WAI `Application` to do this, as it would be completely ignorant of the timeout `Manager`s that are set and controlled by the WAI server. A WAI server can't selectively apply the timeout either, because as mentioned in the [WAI 2.1 announcement](http://www.yesodweb.com/blog/2014/03/wai-yesod-websockets), there is no longer a distinction between an ordinary `Application` and a WebSocket `Application`. In fact the whole point was to eliminate such distinction.

One makeshift solution I can think of is to get the distinction (like `settingsIntercept`) back. Then we configure the server to handle the interceptor function without Timeout. You probably don't want this.

Another way to deal with it is to redesign the `auto-update` package and provide a function `breakFree` that can be called from any `Application`. This function will inspect the current `ThreadId`, find the timeout `Manager`s that are going to kill this thread, and cancel all of them. A WebSocket `Application`, after successfully processing the initial WebSocket request from the client, may call this function and begin an uninterrupted communication. Ordinary `Application`s (that would be better off with the timeout protection) may simply not call the function.

If you think the latter is a feasible solution, I'm willing to help implement it.

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant
