### ISSUE TITLE
Extension: Add ability to serve pre-compressed GZip files

### ISSUE THREAD

**Issue by tolysz** [yesodweb/wai#316]
Hi,
I had to serve quite large static files JSON (~50MiB -> 6MB compressed) I wonder if there some easy way to store both normal and `something.json` as well as `something.json.gz` and let the `wai` stream the right one with the right header as the response to get `something.json`.

I at this point I had to `gzip` files but keep the original extension and override the `encoding` header, breaking everything non compressed or non compatible browsers.

Or maybe have an option to store only the compressed versions and decompress on demand?

**Comment by snoyberg** [comment]
Closing out old issues, please reopen if still relevant

**Comment by tolysz** [comment]
I had a new idea :)
https://github.com/yesodweb/wai/pull/580
