### ISSUE TITLE
Memory leaks in warp

### ISSUE THREAD

**Issue by Farataa** [yesodweb/wai#318]
Hello,

I have installed next modules and their dependencies:

wai-3.0.2
wai-extra-3.0.2.2
wai-logger-2.2.3
warp-3.0.4

You can see application code here: http://pastebin.com/qBrNwVL6 . Config for this application: http://pastebin.com/kei82XWK

This application receives some
headers in http-request and returns some answer after authentication in
LDAP. On tests I'm seen memory leaks. After exclusion LDAP and other
potential leakers I have got the only one: warp.

Compile options:

ghc -O2 -rtsopts -threaded -auto-all -prof send_code.hs

Execution:

/send_code mailauth.cfg +RTS -i0.1 -hc -xt -p -s

Run test:

ab -c3 -n100000 -H "Auth-Protocol: pop3" -H "Auth-User: test" -H
"Auth-Pass: 123" "http://127.0.0.1:4000/"

And got result:

   1,149,938,952 bytes copied during GC
      25,695,016 bytes maximum residency (81 sample(s))
       8,543,448 bytes maximum slop
              68 MB total memory in use (0 MB lost due to fragmentation)

                                    Tot time (elapsed)  Avg pause  Max pause
  Gen  0      6220 colls,     0 par    0.27s    0.28s     0.0000s    0.0014s
  Gen  1        81 colls,     0 par    1.83s    1.85s     0.0229s    0.0475s

  TASKS: 4 (1 bound, 3 peak workers (3 total), using -N1)

  SPARKS: 0 (0 converted, 0 overflowed, 0 dud, 0 GC'd, 0 fizzled)

  INIT    time    0.00s  (  0.00s elapsed)
  MUT     time    8.60s  ( 30.26s elapsed)
  GC      time    1.24s  (  1.25s elapsed)
  RP      time    0.00s  (  0.00s elapsed)
  PROF    time    0.86s  (  0.88s elapsed)
  EXIT    time    0.01s  (  0.01s elapsed)
  Total   time   10.71s  ( 31.52s elapsed)

  Alloc rate    624,320,438 bytes per MUT second

  Productivity  80.3% of total user, 27.3% of total elapsed

gc_alloc_block_sync: 0
whitehole_spin: 0
gen[0].sync: 0
gen[1].sync: 0

Additionaly, I watch on RSS of process and saw only increment of this parameter, sometime decrement. Repeats of this test only increments RSS. Here is profiling: http://pastebin.com/5X3CVHdK

Check this problem please.

**Comment by kazu-yamamoto** [comment]
One source of memory leak has been fixed. See #326.

**Comment by kazu-yamamoto** [comment]
I close this issue. If you still have space leak, please reopen.
