### ISSUE TITLE
wai-extra 'import System.Posix' prevents windows install (StreamFile.hs)

### ISSUE THREAD

**Issue by Jamedjo** [yesodweb/wai#321]
https://github.com/yesodweb/wai/blob/master/wai-extra/Network/Wai/Middleware/StreamFile.hs#L13

**Comment by Jamedjo** [comment]
Changing this to `import System.PosixCompat.Files (fileSize, getFileStatus)` will probably work as it is used in https://github.com/yesodweb/wai/blob/fc2a2f6043759b97b68e129d03c61f56da54fded/wai-app-static/WaiAppStatic/Storage/Filesystem.hs#L26

**Comment by snoyberg** [comment]
Thanks for the catch, I'll release a fix in the next hour.

**Comment by snoyberg** [comment]
OK, should be fixed by 3.0.4.1 which is now on Hackage, can you confirm? Thanks again for the notification.

**Comment by Jamedjo** [comment]
Yes, that builds now! Thanks.
