### ISSUE TITLE
Unable to allow insecure connections with warp-tls

### ISSUE THREAD

**Issue by adamgundry** [yesodweb/wai#324]
I'm upgrading a Warp 2 application to version 3, but I'm running into problems with recent versions of `warp-tls`. The server can be configured to accept both HTTP and HTTPS connections, which previously worked fine, but now HTTP connections do not receive a response. Here's a minimal example:

    {-# LANGUAGE OverloadedStrings #-}

    import Network.HTTP.Types.Status
    import Network.Wai
    import Network.Wai.Handler.Warp
    import Network.Wai.Handler.WarpTLS

    main = runTLS s defaultSettings app
      where
        s = (tlsSettings cert key) { onInsecure = AllowInsecure }
        app _ k = k $ responseLBS ok200 [] "Hello"
        cert = "/path/to/cert.pem"
        key  = "/path/to/key.pem"

HTTPS connections to port 3000 receive "Hello" as expected, but HTTP connections time out without the server producing a response. If I use `DenyInsecure` instead of `AllowInsecure`, HTTP connections receive the rejection message as expected.

This appears to happen on both GHC 7.6.3 and 7.8.3 with the latest versions of the relevant packages, including `warp-3.0.5.1`, `warp-tls-3.0.1.2`, `wai-3.0.2.1` and `tls-1.2.13`.

Thanks!

**Comment by snoyberg** [comment]
Good catch, I believe the commit I've just pushed fixes this. Waiting on confirmation from @kazu-yamamoto before releasing.

**Comment by adamgundry** [comment]
Thanks very much, quick as always! I've tested that c81177a fixes the bug in the original application.

**Comment by adinapoli** [comment]
Thanks Michael!

**Comment by kazu-yamamoto** [comment]
Please give me two days or so to understand this issue. (I'm a little bit busy now.)

**Comment by snoyberg** [comment]
No problem

**Comment by kazu-yamamoto** [comment]
I think that the solution is correct. But I would like to make the code more readable. `httpOverTls` uses the top level `goNext` while `plainHTTP` defines `newRecv` inside. 

- Can we merge `goNext` and `newRecv`? If so, let's do it.
- Otherwise, I would suggest to lift `newRecv` to the top level. Their names should be symmetric, e.g. `recvPlain` and `recvTLS`.

**Comment by snoyberg** [comment]
Is that better?

**Comment by kazu-yamamoto** [comment]
Yes! I would also change function names. But I will do it by myself.

**Comment by adinapoli** [comment]
Thank you folks for the lightning-fast turnaround!
