### ISSUE TITLE
Performance regression due to getFileStatus

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#328]
Today, I got benchmark of Mighty and nginx. Unfortunately, Mighty cannot beat nginx on a small numbers of cores. I feel this is strange, so I have investigated the source of this problem and found it.

A while back, `fileRange` was introduced to `Response.hs`. Since `fileRange` uses `getFileStatus`, `stat(2)` is called every time when a file is being sent. I believe this is a big performance regression of Warp.

One possible solution is port https://github.com/kazu-yamamoto/mighttpd2/blob/master/Program/Mighty/FileCache.hs from Mighty to Warp. But Mighty wants to use this file cache even if Warp supports the same functionality. I have no idea to expose this cache from Warp to WAI Application.

@snoyberg What do you think?

**Comment by kazu-yamamoto** [comment]
Random thoughts:

-  An application initializes a file cache first then passes it to Warp. In this way, the application and Warp can share the file cache.
- How to pass the file cache to Warp? Adding new Runners? Is so, the number of combination becomes large.
- Adding a new filed to `Settings`? But why are `Scoket` and `ConnectionMaker` special? Should we also prepare new fields for them and just one runner, say `runSettings :: Settings -> Application -> IO ()`?

**Comment by kazu-yamamoto** [comment]
FdCache and FileCache should be integrated.

**Comment by snoyberg** [comment]
I like the `Settings` approach. I'm not sure if we should play with the `Socket` and `ConnectionMaker` aspect, however.

Is it possible to avoid the `stat` call in Warp if the `content-length` response header is set by the application?

**Comment by kazu-yamamoto** [comment]
I'm not sure that `content-length` can solve the problem. But it is a good point. I will consider this approach tomorrow.

**Comment by kazu-yamamoto** [comment]
Here is the results of the patch above

core | 1 | 2 | 4 | 8 | 16
---- | ---- | ---- | ---- | ---- | ----
old | 20,710 | 39,237 | 76,326 | 127,449 | 199,093
new | 25,337 | 46,791 | 97,477 | 146,601 | 228,108

**Comment by kazu-yamamoto** [comment]
- The patch above rescues sophisticated applications. I think that we should merge it. The patch is necessary even if we introduce a file info cache.
- To rescue simple applications, we should introduce a file info cache. 
- I'm not satisfied the performance yet.

**Comment by kazu-yamamoto** [comment]
I should have explained this earlier:

- `old` means that Mighty on warp without the patch.
- `new` means that Mighty on warp with the patch.

**Comment by kazu-yamamoto** [comment]
@snoyberg Do you agree to merge the patch above?

P.S. I'm now exploring some other ideas to improve performance.

**Comment by snoyberg** [comment]
Yes, I see no problem with that patch.

FYI: I'm traveling for the next 1.5 weeks, so apologies in advance if I'm not as responsive as usual. Also, I'm 10 time zones behind where I normally am, so there's that too.

**Comment by kazu-yamamoto** [comment]
After reverting #326, the performance of Mighty got back to what I expect.

core | 1 | 2 | 4 | 8 | 16
---- | ---- | ---- | ---- | ---- | ----
old | 20,710 | 39,237 | 76,326 | 127,449 | 199,093
328 | 25,337 | 46,791 | 97,477 | 146,601 | 228,108
326 | 32,965 | 64,128 | 112,599 | 177,649 | 243,256
