### ISSUE TITLE
wai-handler-launch 3.0.0.1 does not load dynamically on Windows

### ISSUE THREAD

**Issue by ygale** [yesodweb/wai#329]
When compiled on Windows (Win7 64-bit, GHC 7.8.3 64-bit, HP 2013.2.0.0, `--constraint=[pkg installed | pkg <- haskell-platform]`), wai-handler-launch 3.0.0.1 fails with the following error when it is loaded dynamically:

    Loading package wai-handler-launch-3.0.0.1 ... linking ... <interactive>: G:\projects\temp\wai-handler-launch\.cabal-sandbox\x86_64-windows-ghc-7.8.3\wai-handler-launch-3.0.0.1\HSwai-handler-launch-3.0.0.1.o: unknown symbol `snprintf'
    ghc.exe: unable to load package `wai-handler-launch-3.0.0.1'

So it cannot be used in an application using TH.

(It also cannot be used from inside GHCi for testing, which is annoying but far less important.)

It works fine on Windows inside a compiled executable that does not use TH.

**Comment by snoyberg** [comment]
Similar issues:

* https://www.haskell.org/pipermail/haskell-cafe/2014-June/114621.html
* https://ghc.haskell.org/trac/ghc/ticket/9297

I don't have a 64-bit Windows system to test this on, so I'm not going to be able to write a patch. PRs are welcome.
