### ISSUE TITLE
blaze-builder 0.4.0.0

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#335]
blaze-builder 0.4.0.0 has been released. The WAI family should support it.

**Comment by snoyberg** [comment]
We first need support in streaming-commons, which is actually non trivial. @manny-fp has actually been working on that already. I'll follow up with him on status for that and then do relevant version bound bumps.

**Comment by manny-fp** [comment]
@snoyberg PR for streaming-commons: https://github.com/fpco/streaming-commons/pull/18

**Comment by snoyberg** [comment]
@kazu-yamamoto The Warp changes look more complicated than I had imagined. Some of the stuff in streaming-commons may help, but it looks like we're going to have to get our hands dirty with some low-level code either way. Mind having a look to see if I'm overlooking something?

**Comment by manny-fp** [comment]
[Network.Wai.Handler.Warp.IO](https://github.com/yesodweb/wai/blob/fc2a2f6043759b97b68e129d03c61f56da54fded/warp/Network/Wai/Handler/Warp/IO.hs) and [Buffer](https://github.com/yesodweb/wai/blob/fc2a2f6043759b97b68e129d03c61f56da54fded/warp/Network/Wai/Handler/Warp/Buffer.hs) both look pretty easy to update (a similar mechanical change to what I did in streaming-commons).  Should I take a stab at it?  Or is there more to it than this?

**Comment by snoyberg** [comment]
Please do have a look, thanks.

**Comment by manny-fp** [comment]
Should warp continue to support blaze-builder 0.3?  That'll need a bit of CPP.

**Comment by snoyberg** [comment]
That would be ideal.

**Comment by manny-fp** [comment]
See pull request https://github.com/yesodweb/wai/pull/338.

**Comment by snoyberg** [comment]
All packages are now compatible with blaze-builder 0.4.
