### ISSUE TITLE
Support byte range serving

### ISSUE THREAD

**Issue by vagifverdi** [yesodweb/wai#345]
Currently warp does not support multi byte range serving.
Byte range serving is a standard feature of practically all web servers.
It is used to stream audio, video files, large pdfs etc.

http://en.wikipedia.org/wiki/Byte_serving

I think warp right now has a basic support of single range downloads. But most client side applications request multiple byte ranges in one request.

Here's an example code in java how to serve multiple chunks of binary file:

https://gist.github.com/davinkevin/b97e39d7ce89198774b4

The gist is basically perpend each binary chunk with some text:

sos.println();
sos.println("--" + MULTIPART_BOUNDARY);
sos.println("Content-Type: " + contentType);
sos.println("Content-Range: bytes " + r.start + "-" + r.end + "/" + r.total);
 
// Copy single part range of multi part range.
Range.copy(input, output, length, r.start, r.length);

**Comment by vagifverdi** [comment]
A good test client would be adobe acrobat reader on windows. It literally bombards the web server with muti byte range requests. The pdf file needs to be linearized, or saved with Web Fast View option for it to work.

**Comment by kazu-yamamoto** [comment]
Current spec is here: https://tools.ietf.org/html/rfc7233

**Comment by kazu-yamamoto** [comment]
For multi ranges, I guess that sendfile cannot be used. If this is the case, the `writev` branch would help.

**Comment by kazu-yamamoto** [comment]
Just a note: multiple ranges must be canonicalized to resist Apache Killer.

**Comment by snoyberg** [comment]
@kazu-yamamoto Will your planned work on #359 subsume this?

**Comment by kazu-yamamoto** [comment]
I would like to keep this open. @borsboom If you want to change the assignee from you to me, please do it.

**Comment by kazu-yamamoto** [comment]
Two questions about this:

- It is hard to install Acrobat Reader plugin into my Mac. Are there any clients other than Acrobat Reader which support multiple ranges?
- Currently, warp returns a part of the content corresponding to the first range if multiple ranges are specified. How does Acrobat Reader behave when it receives this first part only?

**Comment by kazu-yamamoto** [comment]
I decided to not implement this because:

- There is only one major application for this - Acrobat reader plugin. Since most major Browsers now implement their own PDF viewer, the plugin is less important than before. Moreover, it's difficult for me to install the plugin to my browser.
- Rumors say that the plugin is broken. I don't want to suffer from the interoperability problem.
- If we don't support the multiple ranges, we don't need to change the WAI API.

**Comment by survived** [comment]
Nowadays this is the only way to serve properly MP4 video files. For example, Chrome requires Range requests support to enable feature "jumping over video timeline". Bare range request support may be implemented by writing specific handlers, but multirange is needed for large files and cannot be implemented by writing specific handlers. Shouldn't this issue be reopened again?
