### ISSUE TITLE
Add opportunistic encryption function to WarpTLS

### ISSUE THREAD

**Issue by snoyberg** [yesodweb/wai#355]
http://bitsup.blogspot.com.au/2015/03/opportunistic-encryption-for-firefox.html

Having some simple instructions to get started and then a basic wrapper that adds the necessary headers should be all that's necessary.

**Comment by kazu-yamamoto** [comment]
What kind of instruction are you thinking?

The http2 branch is working. You can use HTTP/2 with/without TLS. However, I should do more work to improve performance. Since I need to write a paper about HRR in April, I will get back to the http2 work in May.

Note that I do "git push -f" to the http2 branch sometime as you may know. Please don't confuse.

**Comment by snoyberg** [comment]
Instructions on how to generate a self-signed certificate and the right way to set the ports, for example.

I didn't realize the http2 branch is so far along, that's very exciting!

**Comment by kazu-yamamoto** [comment]
The draft is here: http://tools.ietf.org/html/draft-ietf-httpbis-alt-svc-05

**Comment by kazu-yamamoto** [comment]
A security hole was found:
https://www.mozilla.org/en-US/security/advisories/mfsa2015-44/

**Comment by snoyberg** [comment]
I saw that too. My understanding is that it was an  implementation bug, not
a hole in the spec, but either way we should wait a bit longer before
implementing this.

**Comment by kazu-yamamoto** [comment]
I will join HTTP/2 meet-up on 14th April and discuss this issue deeply.

**Comment by kazu-yamamoto** [comment]
Relating IDs and an RFC:

- Alt-Svc: -- https://tools.ietf.org/html/draft-ietf-httpbis-alt-svc
- HTTP-TLS: (OE) -- https://tools.ietf.org/html/draft-ietf-httpbis-http2-encryption
- Strict-Transport-Security: (HSTS) -- http://tools.ietf.org/html/rfc6797

**Comment by kazu-yamamoto** [comment]
I cannot explain this deeply because of NDA but Firefox 40 will enable this feature again. It will be released in this Summer. So, we should wait for Firefox 40.

**Comment by snoyberg** [comment]
Closing until Firefox 40 is released.
