### ISSUE TITLE
Sophisticated file handling

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#359]
This is random thoughts to support multiple ranges. (#345)

`wai-app-file-cgi` (base library for `mighttpd2`) also implements `Range:` by itself. To support multiple ranges in `warp`, I would like to remove this duplications.

First, the cache of file info (size, modification time, etc) should be ported from `mighttpd2`. This would drastically improve performance for non-sophisticate WAI applications since the number disk access decreases.

The cache of file info should be visible to WAI applications since they want to log how many bytes are sent without disk access. So, it can be specified through `Settings`. If not specified, it is initialized and used only internally.

The logic of `If-Modified-Since:`, `If-Unmodified-Since:`, and `If-Range:` should be ported from `wai-app-file-cgi`. We should discuss on `ETag:`, `If-Match:`, and `If-None-Match:`.

When `Maybe FilePart` of `ResponseFile` is `Nothing`, it indicates that normal contents are being sent. The range logic should run. Otherwise, range logic should not run. This typical case is to send a status message from a user-custom file.

**Comment by kazu-yamamoto** [comment]
A crazy idea on the file info cache: adding a new member to`Request`, whose type is `FilePath -> IO FileInfo`.

**Comment by awpr** [comment]
HTTP2Applications introduced by #426 are capable of streaming multiple file fragments as part of their normal operation; this makes it possible to implement multipart support for HTTP/2 without copying chunks of file data.

**Comment by kazu-yamamoto** [comment]
@snoyberg Can I use `vault` to disclose the new cache of file information from Warp to applications?

**Comment by snoyberg** [comment]
I don't see a reason why not.

**Comment by kazu-yamamoto** [comment]
Thanks. I will export `getFileInfo` as `pauseTimeout` is exported.

I'm tackling this issue and #345 on HTTP/1.1 now.

**Comment by kazu-yamamoto** [comment]
I'm closing this in favor of #477.
