### ISSUE TITLE
Warp sends truncated files when using sendfile

### ISSUE THREAD

**Issue by reiddraper** [yesodweb/wai#371]
Tested with warp 3.0.5.2 and 3.0.12.1, and on Linux and Mac OSX.

Sample Main.hs.

```haskell
module Main where

import Network.Wai
import Network.Wai.Handler.Warp
import Network.HTTP.Types

main :: IO ()
main = run 3000 $ \_ rsp -> rsp $ responseFile status200 [] "foo" Nothing
```

Write to the file `foo`:

```shell
$ echo foobarbaz > foo
$ ./Main.hs

$ curl -v localhost:3000/
<snip>
Content-Length: 10
<snip>
foobarbaz
```

Everything looks good. Now edit foo, while leaving the server running:

```shell
$ echo foobarbaz >> foo

$ curl -v localhost:3000/
<snip>
Content-Length: 20
<snip>
foobarbaz
```

Curl hangs, and eventually times out. This little experiment appears to be non-determinstic, as well. Disabling send-file when running the test seems to never exhibit the bug (`-f -allow-sendfilefd`).  My hunch is there is some timing issue with re-using file descriptors to pass to sendfile. You may have more luck reproducing this by significantly changing the file size between the first and second curl.

**Comment by snoyberg** [comment]
This looks like the file descriptor cache, pinging @kazu-yamamoto. Can you try disabling that cache and see if it resolves your problem?

**Comment by reiddraper** [comment]
I have not yet been able to reproduce the issue with a `setFdCacheDuration` of 0. The [apache documentation](http://httpd.apache.org/docs/2.2/mod/mod_file_cache.html) seems to suggest this is a known issue with caching file-descriptors and using sendfile:

> This file handle caching is done once at server start or restart, only. So whenever one of the cached files changes on the filesystem you have to restart the server (see the Stopping and Restarting documentation). To reiterate that point: if the files are modified in place without restarting the server you may end up serving requests that are completely bogus. You should update files by unlinking the old copy and putting a new copy in place. Most tools such as rdist and mv do this.

**Comment by snoyberg** [comment]
In that case, should we just update the documentation and consider this working as expected? Would you be interested in sending a PR for an appropriate doc fix (i.e., somewhere that may have helped you)?

**Comment by kazu-yamamoto** [comment]
This is a common problem of caching. We should clarify doc or change the default value to 0.

**Comment by reiddraper** [comment]
Setting the default to 0 (no file descriptor cache) seems like a sensible compromise between performance (still using sendfile) and correctness. In production, with truly static assets, users can crank this up to 10 or 30 seconds.

**Comment by snoyberg** [comment]
Kazu: since the file descriptor code is yours, do you want to make a
decision on this?

**Comment by kazu-yamamoto** [comment]
Let's set the default to 0 and clarify the issue and write a recommended value (eg 10 seconds) for productions in the doc.

Since it is in the golden week (a long national holidays) in Japan, I cannot take time. @snoyberg Would you take care of this?

**Comment by snoyberg** [comment]
I've made the modification in de64974. Can you guys review to make sure the text is clear?

**Comment by snoyberg** [comment]
Thanks for the review guys, code is now on Hackage. Closing.
