### ISSUE TITLE
Is there max file size limit for warp

### ISSUE THREAD

**Issue by rnons** [yesodweb/wai#372]
I'm using warp provided by wai-app-static as my file server. However, it seems that it doesn't serve large files well. The output of curl is

```
> GET /a_large_file.tar.gz HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 192.168.1.105:3030
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 2961192960
< Accept-Ranges: bytes
< Date: Mon, 04 May 2015 02:49:05 GMT
* Server Warp/3.0.12 is not blacklisted
< Server: Warp/3.0.12
< Content-Type: application/x-tgz
< last-modified: Thu, 30 Apr 2015 18:11:05 GMT
<
{ [data not shown]
* transfer closed with 2961192960 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 2961192960 bytes remaining to read
``` 
The OS is Fedora-21 32bit. The version of wai-app-static is 3.0.1

I also tested it on a Mac 64bit, large file works fine. Maybe something is missing in my Fedora machine?

**Comment by snoyberg** [comment]
Very interesting, looks like an integer overflow issue somewhere. My guess is this is because your Fedora machine is 32 bit. I'm looking into this on my 32-bit Windows machine right now.

**Comment by snoyberg** [comment]
I haven't been able to reproduce this on Windows, and don't have access to any other 32-bit compilers at the moment. @kazu-yamamoto do you have any thoughts on this one?

**Comment by rnons** [comment]
I set up a vagrant box running Ubuntu 14.04 32bit on a Mac machine. I can reproduce this.

**Comment by snoyberg** [comment]
One other thing that would be nice to know: can you reproduce this on a
64-bit Linux using a 32-bit GHC?

**Comment by rnons** [comment]
I'm not sure. I will set up a vbox later. BTW, the ghc version is 7.10

**Comment by kazu-yamamoto** [comment]
I doubt `simple-sendfile`. But it has the following FFI:

```
foreign import ccall unsafe "sendfile"
    c_sendfile :: Fd -> Fd -> Ptr COff -> CSize -> IO (#type ssize_t)
```

The sendfile manual on Linux says:

```
       ssize_t sendfile(int out_fd, int in_fd, off_t *offset, size_t count);
```

So, it seems to me that the FFI is correct. I would like to know what C types `COff` and `CSize` refer to actually on 32bit Linux.

**Comment by kazu-yamamoto** [comment]
@rnons Would you share your vagrant binary with us?

**Comment by kazu-yamamoto** [comment]
I would like to know what value is returned by `test "a_large_file.tar.gz"` on 32bit Linux where test is:

```
import Control.Applicative
import System.Posix.Types
import qualified System.PosixCompat.Files as P

test :: FilePath -> IO FileOffset
test file = P.fileSize <$> P.getFileStatus file
```

**Comment by rnons** [comment]
@kazu-yamamoto it returns 2621110001, which is the file size according to `ls -l`

**Comment by kazu-yamamoto** [comment]
@rnons Thanks. So, System.PosixCompat works well.

If I provide a special version of sendfile which displays debug information, can you try it and send the debug messages?

**Comment by rnons** [comment]
Sure

**Comment by kazu-yamamoto** [comment]
@rnons Would try the `debuginfo` branch of my simple-sendfile repo? This displays debug information to stdout. Please try this with the big file and send me debug information (where numbers become minus).

https://github.com/kazu-yamamoto/simple-sendfile/tree/debuginfo

**Comment by rnons** [comment]
```
vagrant@vagrant-ubuntu-trusty-32:~/test$ warp
Serving directory /home/vagrant/test on port 3000 with ["index.html","index.htm"] index files.
sendfileFd PartOfFile
sendfileFd off: 0
sendfileFd off': 0
sendfileFd len: 2621110001
sendfileFd len': 2621110001
sendfileloop offp: 0xb7204d04
sendfileloop len: 2621110001
```

Does it help? Or do you still need the vagrant image? Do you have any suggestion where can I upload it? It is ~370M

**Comment by rnons** [comment]
Sorry, I'm mistaken, the vagrant image is around ~5G

**Comment by kazu-yamamoto** [comment]
According the debug information, no underflow happens here. Before sharing the vagrant image, please run the following code and tell me the result:

```haskell
import Foreign.C.Types
import Foreign.Storable
import System.Posix.Types

main :: IO ()
main = do
    print $ sizeOf (undefined :: CSize)
    print (maxBound :: CSize)
    print $ sizeOf (undefined :: COff)
    print (maxBound :: COff)
```

**Comment by rnons** [comment]
```
4
4294967295
8
9223372036854775807
```

**Comment by kazu-yamamoto** [comment]
Also, I would like to know the result of the following C code:

```c
#include <stdio.h>
#include <sys/types.h>

int main () {
  printf("size_t: %lu\n", sizeof(size_t));
  printf("off_t: %lu\n", sizeof(off_t));
}
```

**Comment by rnons** [comment]
size_t: 4
off_t: 4

**Comment by kazu-yamamoto** [comment]
Good reference: https://groups.google.com/forum/#!topic/yesodweb/7AhYtCu0oIA

**Comment by kazu-yamamoto** [comment]
Your sendfile() cannot send a file whose size is over 2^31 according to size_t size.

It is strange that COff size is 8 while off_t size is 4.

**Comment by kazu-yamamoto** [comment]
Does your Linux have sendfile64()? If so, would you send the signature of sendfile64() from its manual?

**Comment by rnons** [comment]
It seems I dont's have sendfile64?
When I type `man sendfile64`, it prints the same content as `man sendfile`.
The signature is `ssize_t sendfile(int out_fd, int in_fd, off_t *offset, size_t count);`

**Comment by kazu-yamamoto** [comment]
Uhhhm. So, it means that your sendfile() cannot send large files due to size_t.

**Comment by kazu-yamamoto** [comment]
Oh. Please give a look at `sys/sendfile.h`. What is the signature of sendfile64()?

**Comment by rnons** [comment]
```
#ifndef _SYS_SENDFILE_H
#define _SYS_SENDFILE_H	1

#include <features.h>
#include <sys/types.h>

__BEGIN_DECLS

/* Send up to COUNT bytes from file associated with IN_FD starting at
   *OFFSET to descriptor OUT_FD.  Set *OFFSET to the IN_FD's file position
   following the read bytes.  If OFFSET is a null pointer, use the normal
   file position instead.  Return the number of written bytes, or -1 in
   case of error.  */
#ifndef __USE_FILE_OFFSET64
extern ssize_t sendfile (int __out_fd, int __in_fd, off_t *__offset,
			 size_t __count) __THROW;
#else
# ifdef __REDIRECT_NTH
extern ssize_t __REDIRECT_NTH (sendfile,
			       (int __out_fd, int __in_fd, __off64_t *__offset,
				size_t __count), sendfile64);
# else
#  define sendfile sendfile64
# endif
#endif
#ifdef __USE_LARGEFILE64
extern ssize_t sendfile64 (int __out_fd, int __in_fd, __off64_t *__offset,
			   size_t __count) __THROW;
#endif

__END_DECLS

#endif	/* sys/sendfile.h */
```

**Comment by kazu-yamamoto** [comment]
I would like to invite @crosser  to this discussion since he suggested to use sendfile() instead of sendfile64() in simple-sendfile.

**Comment by snoyberg** [comment]
@kazu-yamamoto If there's a way of programmatically detecting that sendfile can't support large files (sizeof CSize?) we could modify warp to bypass the optimization in those cases, right? I suppose such a fix could even be used to allow for files larger than 2^64 bytes ;)

**Comment by kazu-yamamoto** [comment]
OK. sendfile64() still uses size_t. No hope for sendfile() on 32bit Linux.

**Comment by kazu-yamamoto** [comment]
@snoyberg Yeah. We need to fall back to the pread()/writev() approach in such cases. *Fortunately*, we have such a branch: https://github.com/yesodweb/wai/tree/writev

**Comment by kazu-yamamoto** [comment]
I understand that the intention of sendfile() AIP. If the size of file is over size_t size, we should call sendfile() repeatedly.

**Comment by kazu-yamamoto** [comment]
@rnons Would you also run the following C code? off_t size should be 8, I hope.

```c
#define _GNU_SOURCE 1

#include <stdio.h>
#include <sys/types.h>

int main () {
  printf("size_t: %lu\n", sizeof(size_t));
  printf("off_t: %lu\n", sizeof(off_t));
}
```

**Comment by rnons** [comment]
```
size_t: 4
off_t: 4
```

**Comment by kazu-yamamoto** [comment]
OK. Thanks.

**Comment by crosser** [comment]
Who summoned me? ;-)
I think [this](https://mail.haskell.org/pipermail/glasgow-haskell-users/2012-February/021864.html) (and the following thread) is relevant.
The problem is (was at the time) that when you are compiling a package with C code using FFI, the C code does not know what is the value of _FILE_OFFSET_BITS in the existing Haskell runtime. I was suggesting that the "best" solution would be for FFI headers to export this value. Or as a "second best" solution, that the packages containing C code use autoconf(-like) magic to figure the bit-ness of the system on which they are being compiled, and pray that GHC runtime used the same bit-ness.

**Comment by crosser** [comment]
In other words, simple-sendfile _ought_ to use sendfile(), _not_ sendfile64(). But for this to compile to the right thing on both 32 and 64 bit systems, it also needs to use -D_FILE_OFFSET_BITS=64 _if and only if_ GHC itself was build with this definintion.

**Comment by kazu-yamamoto** [comment]
To my understanding, we should do two things for Linux:

- simple-sendfile should divide a large file according to the `CSize` size and repeat calling sendfile() for the blocks. This solves @rnons's problem.
- `_FILE_OFFSET_BITS` should be set to a right value when simple-sendfile is compile to ensure that `off_t` and `COff` be the same value. I guess that Setup.hs should check the `COff` size and define `_FILE_OFFSET_BITS` to 64 if the `COff` size is 8.

**Comment by kazu-yamamoto** [comment]
@rnons Would you try the following? Does this solve your problem?

https://github.com/kazu-yamamoto/simple-sendfile/tree/sizet

**Comment by rnons** [comment]
@kazu-yamamoto Great, it works fine. Thank you very much.

**Comment by kazu-yamamoto** [comment]
@rnons Thank you for your report!

So, the first problem has been fixed. I would leave the second problem as is since it is difficult for me to implement it. I will re-consider if the second problem actually happens.

I will release a new version of simple-sendfile soon.

**Comment by rnons** [comment]
@kazu-yamamoto I'm sorry. When I reported "it works fine", the downloading was still in progress. However, I just found that it stopped at 2047M

```
> GET /large_file.dmg HTTP/1.1
> User-Agent: curl/7.35.0
> Host: 127.0.0.1:3000
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Length: 2621110001
< Accept-Ranges: bytes
< Date: Mon, 18 May 2015 06:13:57 GMT
* Server Warp/3.0.13 is not blacklisted
< Server: Warp/3.0.13
< Content-Type: application/x-apple-diskimage
< last-modified: Tue, 09 Sep 2014 21:48:45 GMT
<
{ [data not shown]
 81 2499M   81 2033M    0     0  23.0M      0  0:01:48  0:01:28  0:00:20 22.0M* transfer closed with 473626354 bytes remaining to read
 81 2499M   81 2047M    0     0  23.0M      0  0:01:48  0:01:28  0:00:20 21.6M
* Closing connection 0
curl: (18) transfer closed with 473626354 bytes remaining to read
```
And the warp prints out 
```
Network.SendFile.Linux.sendfileloop: failed (Value too large for defined data type)
```

**Comment by kazu-yamamoto** [comment]
@rnons I pushed a commit to the `sizet` branch, which sets `_FILE_OFFSET_BITS` to 64. Would you try this again?

**Comment by kazu-yamamoto** [comment]
Uhhm. 2621110001 - 2^30 - 2^30 = 473626353.

**Comment by rnons** [comment]
same result here

**Comment by kazu-yamamoto** [comment]
@rnons I pushed one more commit to the `sizet` branch. Please try.

I think this problem is caused because `off_t` is 32bit. (2^30 + 2^30) results in overflow (`EOVERFLOW`). We need to ensure to use sendfile() which uses `__off64_t`.

**Comment by rnons** [comment]
Sorry, same result here

**Comment by kazu-yamamoto** [comment]
@rnons Do you understand how to ensure using `__off64_t` in sendfile() on your Linux?

**Comment by kazu-yamamoto** [comment]
`cc -E <the file below>` generates on 64bit Linux:

```c
extern ssize_t sendfile (int __out_fd, int __in_fd, __off64_t *__offset, size_t __count) __asm__ ("" "sendfile64") __attribute__ ((__nothrow__ , __leaf__))
```
So, `Linux.hsc` seems good.

```c
#define _LARGEFILE64_SOURCE 1
#define _FILE_OFFSET_BITS 64

#include <sys/sendfile.h>
```

@rnons How sendfile() is expanded on 32bit Linux?

**Comment by rnons** [comment]
```
# 271 "/usr/include/i386-linux-gnu/sys/types.h" 2 3 4
# 24 "/usr/include/i386-linux-gnu/sys/sendfile.h" 2 3 4
# 37 "/usr/include/i386-linux-gnu/sys/sendfile.h" 3 4
extern ssize_t sendfile (int __out_fd, int __in_fd, __off64_t *__offset, size_t __count) __asm__ ("" "sendfile64") __attribute__ ((__nothrow__ , __leaf__));

extern ssize_t sendfile64 (int __out_fd, int __in_fd, __off64_t *__offset,
      size_t __count) __attribute__ ((__nothrow__ , __leaf__));
```

I don't understand how to ensure using __off64_t in sendfile() on my Linux.

**Comment by kazu-yamamoto** [comment]
@rnons Thank you for your quick response. It seems that the current code ensures that sendfile() uses `__off64_t`. So, I have no idea why this new problem happens.

One more try: what happens if you replace sendfile() with sendfile64() in the FFI part of Linux.hsc?

```haskell
foreign import ccall unsafe "sendfile64"
    c_sendfile :: Fd -> Fd -> Ptr COff -> CSize -> IO (#type ssize_t)
```

Also, this code is worth trying:

```haskell
foreign import ccall unsafe "sendfile64"
    c_sendfile :: Fd -> Fd -> Ptr (#type __off64_t)-> CSize -> IO (#type ssize_t)
```

**Comment by rnons** [comment]
The first version works! :tada: 

The second version doesn't build

```
Network/Sendfile/Linux.hsc:104:33:
    Couldn't match type `COff' with `Int64'
    Expected type: Ptr Int64
      Actual type: Ptr COff
```

**Comment by kazu-yamamoto** [comment]
Good.

Does anyone know why "sendfile" does not work and "sendfile64" work on 32bit Linux? Note that necessary macros are surely defined.

**Comment by kazu-yamamoto** [comment]
Doesn't GHC respect macros when linking C functions?

**Comment by kazu-yamamoto** [comment]
- If the `COff` size is 8, use `sendfile64`
- Otherwise, use `sendfile`
- Setup.hs checks the `COff` size and define a C macro accordingly
- Either `sendfile` or `sendfile64` is selected by the C macro

Is this feasible?

**Comment by crosser** [comment]
For what it's worth, it is my understanding that it's _wrong_ to use sendfile64() call and/or __off64_t type. It is also wrong to try send a large file it in 4G chunks. _If_ your system is able to give you a handle for a >4G file, then sendfile() _will_ accept 64bit offset, as long as the program is compiled with proper defines. You need some magic to find these defines, at build time. _None_ of the magic should be necessary in the code itself, it should be sufficient to always use sendfile() and off_t.

I think that back then, I sent a patch to the build system to @kazu-yamamoto that should have detected the right defines and provide them to the compiler. Would it be possible to test it in this case?

**Comment by crosser** [comment]
This was my patch, as of Feb 2012. I am not sure that it will work, or be usable at all on Windows, but maybe it's worth to try...
```
From 0e85051a3c65f0add375e4054db987c8aa17aca6 Mon Sep 17 00:00:00 2001
From: Eugene Crosser <crosser@average.org>
Date: Thu, 16 Feb 2012 18:34:46 +0400
Subject: [PATCH] Use autoconf to detect LARGEFILE support


Signed-off-by: Eugene Crosser <crosser@average.org>
---
 Network/Sendfile/BSD.hsc   |    2 ++
 Network/Sendfile/Linux.hsc |    1 +
 Network/Sendfile/MacOS.hsc |    1 +
 README                     |    4 ++++
 configure.ac               |   15 +++++++++++++++
 simple-sendfile.cabal      |   12 +++++++++++-
 6 files changed, 34 insertions(+), 1 deletions(-)
 create mode 100644 README
 create mode 100644 configure.ac

diff --git a/Network/Sendfile/BSD.hsc b/Network/Sendfile/BSD.hsc
index 09459ca..b022c74 100644
--- a/Network/Sendfile/BSD.hsc
+++ b/Network/Sendfile/BSD.hsc
@@ -15,6 +15,8 @@ import Network.Socket
 import System.Posix.IO
 import System.Posix.Types (Fd(..), COff)
 
+#include "HsConfig.h"
+
 {-|
    Simple binding for sendfile() of BSD.
 
diff --git a/Network/Sendfile/Linux.hsc b/Network/Sendfile/Linux.hsc
index 82b7864..aa2ea5a 100644
--- a/Network/Sendfile/Linux.hsc
+++ b/Network/Sendfile/Linux.hsc
@@ -17,6 +17,7 @@ import System.Posix.Files
 import System.Posix.IO
 import System.Posix.Types (Fd(..))
 
+#include "HsConfig.h"
 #include <sys/sendfile.h>
 
 {-|
diff --git a/Network/Sendfile/MacOS.hsc b/Network/Sendfile/MacOS.hsc
index 2effcde..e07318f 100644
--- a/Network/Sendfile/MacOS.hsc
+++ b/Network/Sendfile/MacOS.hsc
@@ -20,6 +20,7 @@ import Network.Socket
 import System.Posix.IO
 import System.Posix.Types (Fd(..))
 
+#include "HsConfig.h"
 #include <sys/types.h>
 
 {-|
diff --git a/README b/README
new file mode 100644
index 0000000..f5aa1cf
--- /dev/null
+++ b/README
@@ -0,0 +1,4 @@
+To build this package using Cabal directly from darcs, you must run
+"autoreconf" before the usual Cabal build steps (configure/build/install).
+autoreconf is included in the GNU autoconf tools.  There is no need to run
+the "configure" script: the "setup configure" step will do this for you.
diff --git a/configure.ac b/configure.ac
new file mode 100644
index 0000000..1dbcf2c
--- /dev/null
+++ b/configure.ac
@@ -0,0 +1,15 @@
+AC_INIT([Haskell simple sendfile interface], [0.2.x], [kazu@iij.ad.jp], [simple-sendfile])
+
+dnl ** Modeled after Haskell's "unix" package **
+
+AC_CONFIG_SRCDIR([Network/Sendfile.hs])
+
+AC_CONFIG_HEADERS([Network/Sendfile/HsConfig.h])
+
+AC_C_CONST
+
+dnl ** Enable large file support.  NB. do this before testing the type of
+dnl    off_t, because it will affect the result of that test.
+AC_SYS_LARGEFILE
+
+AC_OUTPUT
diff --git a/simple-sendfile.cabal b/simple-sendfile.cabal
index 13afd25..e84e8e4 100644
--- a/simple-sendfile.cabal
+++ b/simple-sendfile.cabal
@@ -10,9 +10,19 @@ Description:            Cross platform library for the sendfile system call.
                         are the bottleneck of web servers.
 Category:               Network
 Cabal-Version:          >= 1.6
-Build-Type:             Simple
+Build-Type:             Configure
+
+extra-source-files:
+                config.guess config.sub install-sh
+                configure.ac configure
+                Network/Sendfile/HsConfig.h.in
+extra-tmp-files:
+                config.log config.status autom4te.cache
+                Network/Sendfile/HsConfig.h
 
 Library
+  include-dirs: Network/Sendfile
+  includes:     HsConfig.h
   if impl(ghc >= 6.12)
     GHC-Options:        -Wall -fno-warn-unused-do-bind
   else
-- 
1.7.2.5
```

**Comment by kazu-yamamoto** [comment]
Where can I find `HsConfig.h.in`?

**Comment by crosser** [comment]
It should be created by `autoreconf` (as described in the README).

**Comment by kazu-yamamoto** [comment]
Thanks. I now have `HsConfig.h.in`. Unfortunately, I don't understand the intention of this patch:

- Even on 64bit Linux, autoconf does not set `_FILE_OFFSET_BITS` to 64.
- Even if `_FILE_OFFSET_BITS` is set to 64 properly, GHC does not respect C header files when linking.

What we need to do is replace the `"sendfile"` string to the `"sendfile64"` string in the FFI if the COff size is 8. I don't think the patch achieves this.

**Comment by kazu-yamamoto** [comment]
@rnons As suggested in haskell-cafe, I implemented dynamic dispatch. Please try this:

https://github.com/kazu-yamamoto/simple-sendfile/tree/switch

I confirmed that this works well on 64bit Linux.

**Comment by rnons** [comment]
It doesn't work.

```
{ [data not shown]
 81 2499M   81 2036M    0     0   161M      0  0:00:15  0:00:12  0:00:03  165M* transfer closed with 473626354 bytes remaining to read
 81 2499M   81 2047M    0     0   161M      0  0:00:15  0:00:12  0:00:03  162M
* Closing connection 0
curl: (18) transfer closed with 473626354 bytes remaining to read
```

**Comment by kazu-yamamoto** [comment]
@rnons I'm really sorry. I made a terrible mistake. I pushed a fix. Please give one more try to the `switch` branch.

**Comment by rnons** [comment]
It works fine. Thank you. :+1:

**Comment by kazu-yamamoto** [comment]
I have released a new version.

@rnons I really thank you for your patient testing.

**Comment by crosser** [comment]
@kazu-yamamoto :

> Even on 64bit Linux, autoconf does not set _FILE_OFFSET_BITS to 64.
> Even if _FILE_OFFSET_BITS is set to 64 properly, GHC does not respect C header files when linking.

There is no need to define `_FILE_OFFSET_BITS` on 64bit system. Such system always has 64bit off_t. 32bit systems may use 32bit off_t or 64bit off_t. If you run `configure` on a 32bit system that _supports_ >4Gb files, it will define `_FILE_OFFSET_BITS=64`, and then libc headers will translate `sendfile()` function call into `sendfile64` syscall under the hood, invisible to you. And `off_t` will be a 64 bit type. If you run `configure` on a 32bit system that _does not_ support files >4Gb, `_FILE_OFFSET_BITS` won't be set (or set to 32, I am not sure), and `sendfile()` function will be translated to 32bit `sendfile` syscall.

Once again, the distinction is only important on 32bit systems. Only on such systems, both 32bit and 64bit file API exists. On 64bit systems, file API is always 64bit. Therefore `configure` does not do anything "interesting" on such systems.

> What we need to do is replace the "sendfile" string to the "sendfile64" string in the FFI if the COff size is 8. I don't think the patch achieves this.

There is no need to "replace" anything. You are trying to do at runtime what libc headers are designed to do for you automatically at compile time. This is possible, but error prone, and, in my opinion, "wrong".

**Comment by kazu-yamamoto** [comment]
> There is no need to define _FILE_OFFSET_BITS on 64bit system. Such system always has 64bit off_t. 32bit systems may use 32bit off_t or 64bit off_t.

I understand 64bit Linux stuff. Thanks.

> If you run configure on a 32bit system that supports >4Gb files, it will define _FILE_OFFSET_BITS=64, and then libc headers will translate sendfile() function call into sendfile64 syscall under the hood, invisible to you. 

If my understanding is correct, this interpretation is not quite correct. "under the hood" can surely apply to C files but cannot to Haskell files.

On 32bit Linux which support 64bit off_t, C files are linked to `sendfile64()` thanks to "under the hood" magic. But hsc2hs does not replace `"sendfile"` to `"sendfile64"`, so `sendfile()` is linked. This is why you felt "error prone", I guess.

**Comment by crosser** [comment]
When your .hsc file calls C `sendfile()` while proper defines are present, it will turn to a call to `sendfile64` in the compiled code, without the need to mention `sendfile64` in the code explicitly. The same way as in the "standard" `unix` module, `Common.hsc` uses "normal" name for `stat()`, and still in the compiled version, 64bit stat() is used.

I am saying that `simple-sendfile` module _ought_ to use the same approach as "standard" `unix` module. I.e. always use generic function names, and let the OS/build system magic to distinguish between 32bit and 64bit calls.

I feel that the approach of "manually" deciding between 32bit and 64bit APIs is more error prone than relying on the OS/build system.

**Comment by kazu-yamamoto** [comment]
> When your .hsc file calls C sendfile() while proper defines are present, it will turn to a call to sendfile64 in the compiled code, without the need to mention sendfile64 in the code explicitly. The same way as in the "standard" unix module, Common.hsc uses "normal" name for stat(), and still in the compiled version, 64bit stat() is used.

It seems to me that `__hscore_stat`, not `stat`, is used in the unix package of GHC 7.10.1.

Moreover, according to @rnons's experiment, `senfile64()` is not linked for `"sendfile"` even if necessary macros are defined. For more information, please read discussion above.

**Comment by crosser** [comment]
@kazu-yamamoto, indeed `stat()` function is called via some pointer hidden deep in Base, but for example `lseek()` is called directly, as far as I can tell. `lseek()` has an `off_t` argument and returns `off_t` result. I am 80% sure that my suggested approach will work. I have no 32bit system at hand to verify it, I will try to arrange such test system and check it.

I am not convinced that the tests mentioned in this ticket where accurate enough to prove that my theory is wrong.

**Comment by kazu-yamamoto** [comment]
I confirmed that `lseek()` is used directly. Looking into the difference between `lseek()` and `sendfile()`, `lseek()` is used as `"unistd.h lseek"` but `sendfile()` was used as just `"sendfile"`. I'm wondering if I should have written `"sys/sendfile.h sendfile"` with the macros.

@crosser BTW, what is your concern of the current code (i.e. dynamic switching)?

**Comment by kazu-yamamoto** [comment]
@rnons Would you take time to give one more try to this branch?

https://github.com/kazu-yamamoto/simple-sendfile/tree/autoconf

You need to run "autoreconf" before "cabal configure; cabal test". If this succeeds, the source of confusion is that `"sys/sendfile.h "` is missing.

**Comment by rnons** [comment]
test pass
```
Running 1 test suites...
Test suite spec: RUNNING...
Test suite spec: PASS
Test suite logged to: dist/test/simple-sendfile-0.2.18-spec.log
1 of 1 test suites (1 of 1 test cases) passed.
```
But download doesn't work
```
{ [data not shown]
* transfer closed with 2621110001 bytes remaining to read
  0 2499M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
curl: (18) transfer closed with 2621110001 bytes remaining to read
```

**Comment by crosser** [comment]
My basic concern is that dual 32bit/64bit interface was _designed_ with compile-time dispatch in mind, and with the goal of hiding the duality from most of the source code. Adhering to this principle seems the Right Thing to do, and when done correctly, is potentially less prone to breakage in edge cases.

I have set up 32bit VM and run existing tests successfully. I will create a proper test with a file >4Gb and report when I get results.

**Comment by rnons** [comment]
I just tested a 4318M file with simple-sendfile-0.2.20

```
{ [data not shown]
  5 4318M    5  222M    0     0  3793k      0  0:19:25  0:01:00  0:18:25     0* transfer closed with 4294967296 bytes remaining to read
  5 4318M    5  222M    0     0  3793k      0  0:19:25  0:01:00  0:18:25     0
* Closing connection 0
curl: (18) transfer closed with 4294967296 bytes remaining to read
```

**Comment by crosser** [comment]
I am trying to make proper testset with files bigger than 4Gb (which is challenging because it's so easy to exhaust system resources, even with sparse files), and am getting interesting results. At the moment, it seems that the problem is not in the different limitations of `off_t` on 32bit and 64bit systems, but in the different limitations of `size_t`. That would explain why `-D_FILE_OFFSET_BITS=64` does not help.

I will be back when I have definite results.

**Comment by crosser** [comment]
@rnons, may I ask you to run this program on your 32bit system and post the results:
```
#!/usr/bin/env runhaskell

import System.Posix.Types
import Data.Bits

x = 0 :: FileOffset
y = 0 :: ByteCount

main = do
  putStrLn $ "FileOffset: " ++ show (bitSize x)
  putStrLn $ "ByteCount : " ++ show (bitSize y)
```

**Comment by rnons** [comment]
FileOffset: 64
ByteCount : 32

**Comment by crosser** [comment]
I was wrong when I said the FFI will automatically call the right version of sendfile() depending on the value of _FILE_OFFSET_BITS. [This link](https://wiki.haskell.org/GHC/Using_the_FFI#Importing_C_functions_that_turn_out_to_be_CPP_macros) explains how such case can be addressed. I created a pull request to simple-sendfile with all necessary updates for the decision to be made at compile time, and with tests involving a (sparse) file bigger than 4 Gb.

**Comment by kazu-yamamoto** [comment]
Closing this issue. Let's continue on the simple-sendfile repo if necessary.
