### ISSUE TITLE
1getCurrentTime1 in auto-update README

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/wai#379]
The [current auto-update README](https://github.com/yesodweb/wai/tree/4842250618772e2fadccb53510583704cb1ddb00/auto-update) has the words "1getCurrentTime1" and "1IORef1". I guess this was meant to be `getCurrentTime` and `IORef`? This just seemed like a crazy typo to happen twice so I figured I'd open an issue.

**Comment by kazu-yamamoto** [comment]
Fixed in ca9321ca93cc713d5dc22f901c432537720b69c3.

Thank you for your report!
