### ISSUE TITLE
A new buffer management

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#381]
@snoyberg I would like to ask you to review my branch: https://github.com/yesodweb/wai/tree/kazu-master

This code includes:

- Removing `connReadBuffer`, which is not used anywhere, from `Connection`
- Merging @martin-bailey's read buffer management. This does not improve performance for HTTP/1.1 on my measurement. But I hope this is good for HTTP/2. Note that this code introduce `connBufferPool` to `Connection`.
- Setting the size of write buffer to 16K which is the maximum size of TLS record and HTTP/2 frame payload.

This code eases my HTTP/2 development. One concern is that footprint of warp would be bigger since 16K buffers are used for read and write while the original one uses 4K. I welcome discussions.

**Comment by snoyberg** [comment]
I didn't do a deep dive of this, but based on what I saw now and what I remember from when @martin-bailey originally raised this, I have no problem with the change.

**Comment by kazu-yamamoto** [comment]
Thanks. I merged the kazu-master branch to master.
