### ISSUE TITLE
warp: no exception upon an empty request

### ISSUE THREAD

**Issue by feuerbach** [yesodweb/wai#382]
I registered an exception handler through `setOnException.`

When I send some junk instead of a request, I see an exception, as expected:

```
Warp: Invalid first line of request: "asdf"
```

However, if I send a single newline, the client gets back `500 Something went wrong`, but no exception is printed.

I think the property that any 500 error is logged on the server side is a very desirable one.

This is warp-3.0.2.3; apologies if this has been fixed in a later version.

**Comment by kazu-yamamoto** [comment]
I would like to understand your suggestion correctly. You are talking about two cases: junk and a single line. Do you want to

- send 500 response and
- record 500 log and
- display warnings

for both cases?

**Comment by feuerbach** [comment]
I don't understand the "display warnings" bit, but regarding the first two aspects, I don't see why the two invalid requests would lead to different behaviors. Are you saying the difference is intentional?

**Comment by kazu-yamamoto** [comment]
> I don't understand the "display warnings" bit

Something like the following:

    Warp: Invalid first line of request: "asdf"

> but regarding the first two aspects, I don't see why the two invalid requests would lead to different behaviors. Are you saying the difference is intentional?

I think that's not intentional.

I'm not opposing your suggestions. I just want to know what you wish.

**Comment by feuerbach** [comment]
> Something like the following:
> 
> Warp: Invalid first line of request: "asdf"


Right, that was what I meant. This should be the result of installing an `setOnException` handler.

**Comment by kazu-yamamoto** [comment]
Relating to #218.

According to 8913a3d97cb47fb08ee728cfc0a7c185dba8f1d3, this behavior is intentional. We need to discuss what behavior is reasonable.

**Comment by kazu-yamamoto** [comment]
Never mind. #218 is not relating to this issue.

**Comment by kazu-yamamoto** [comment]
What I understand so far:

- Junk header (including CRLF): sending 500 + exception handler
- A single CRLF: sending 500

I would be nice if we log 500 when sending 500. @feuerbach Do you agree?

The difference of these behaviors come from: 2c15f796e28124e71a3c877ee9b20ce827984e45
With this patch, we cannot distinguish a single CRLF and a connection close.

@snoyberg What is the intention of this code? Isn't it good enough for `onE` to ignore `ConnectionClosedByPeer`? The patch above implements this. I confirmed that this code distinguishes a single CRLF and a connection close.

**Comment by snoyberg** [comment]
I believe it comes from differences in how clients deal with pipelining: some of them send an extra CRLF between requests (like they're supposed to) but some don't. We currently just ignore CRLFs as the beginning. This has never been a problem in the past. @feuerbach what's the case where these missing exceptions is causing problems?

**Comment by kazu-yamamoto** [comment]
@snoyberg OK. It makes sense that `onE` ignores `NotEnoughLines []`. But why `headerLines` returns `NotEnoughLines []` when the connection is closed?

**Comment by snoyberg** [comment]
I believe it's because there's not way to distinguish between "client completely closed the connection" and "client closed half of the connection." In a non-pipelining case, it would be perfectly reasonable for a client to send a request, close the send half of its socket, and then expect a response on the receive half.

**Comment by kazu-yamamoto** [comment]
When a client does half-close and Warps throws `NotEnoughLines []`, `closeConn` is called in `fork`. So, it seems to me that there is no chance for Warp to send a response to the client. Am I missing something?

**Comment by snoyberg** [comment]
I'm not sure if there's a good reason on this, and I'm not really should what the alternative is that you're looking for instead. I don't have a problem if you want to change the behavior on this case.

**Comment by feuerbach** [comment]
> @feuerbach what's the case where these missing exceptions is causing problems?

The problem is that a server may return an error reponse (500) without leaving any local evidence. I don't know whether this specific case should be an error condition. If it is, we should see the error in the logs and in the exception handler; if not, then the client shouldn't get 500.

If what the client and the administrator see differ, then I argue that's a bug.

**Comment by snoyberg** [comment]
The 500 in this case is sent just as a courtesy (I can't remember which issue triggered it). Warp really wants to just drop the connection on the floor, but an incorrectly written client may be expecting some kind of a response, so we send one. I'm really not too particular about any specific behavior here, but I favor _not_ throwing an exception since I'd consider it a false flag here.

**Comment by feuerbach** [comment]
Perhaps I misunderstand the purpose of `setOnException`; what is it meant to accomplish?

**Comment by snoyberg** [comment]
It's meant to let you get notified when something *really* goes wrong. A connection dying because no data was sent from the other side just doesn't fall into my category of something I'd want to be alerted about.

**Comment by feuerbach** [comment]
Well it seems to throw exceptions (`Warp error: receiveloop: resource vanished (Connection reset by peer)`) every time a connection is terminated with an RST (which is pretty normal here), so there's that.

I guess what I'm asking is, is it meant for warp developers or administrators?

**Comment by snoyberg** [comment]
If by "warp developers" you mean just Kazu and myself: no. It's meant for people writing sites/applications using Warp. The Yesod scaffolding uses it, for example.

**Comment by feuerbach** [comment]
Right. So imagine a warp application that provides some kind of API. Say your user comes to you and says "hey, we got this 500 Something went wrong from your app". You look at your exception logs and don't see anything. I find it rather unfortunate.

**Comment by snoyberg** [comment]
I don't feel strongly about this one. If you'd like to send a PR to change the behavior in this case, I'm fine with it. I'm personally OK with the current behavior.

**Comment by gregwebs** [comment]
It seems to me that Michael is arguing that there is a client error. In that case the error code should not be 500 (maybe a 400 or 422)

**Comment by kazu-yamamoto** [comment]
@gregwebs Right. We should categorize exceptions into 400 group and 500 group. (I think that 422 is not correct. I guess that @grepwebs meant 412.)

Anyway, I will take care of this issue. I will consider reasonable behavior which most users like and implement it. Please wait for a while.

**Comment by kazu-yamamoto** [comment]
@snoyberg Please merge #386 if you think OK.

We should add `Since: ` for new exported APIs when we release a new version.
