### ISSUE TITLE
new sendfile appoarch

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#383]
The sendfile function defined in WarpTLS has performance problems because:

- It does not make use of FdCache
- It does not pack headers and a body into a single TLS record

To solve this problem, I implemented readSendFile. For all platforms, it tries to pack headers and body into a singale TLS record. For Unix, it makes use of FdCache.

File descriptors can be shared among Haskell threads when sendfile() is used. This because sendfile() takes offset and length as arguments. It does not change the internal information of file descriptors in the kernel. We can emanate this with pread() with send().

To integrate sendfile() and pread()/send(), I removed `connSendFileOverride` and introduced `FileId`.

The code above is available from: https://github.com/yesodweb/wai/tree/read-send-file

@snoyberg Would you review the code? It would be appreciated if you tested it on Windows.

Not tested well. I will write some test cases tommorow.

**Comment by kazu-yamamoto** [comment]
I have added test cases.

**Comment by kazu-yamamoto** [comment]
Pinging @snoyberg

**Comment by snoyberg** [comment]
I haven't looked at the code in detail yet. I'm pushing one Windows build fix, and reporting the following test failures on Windows:

```
Failures:

  1) Response, range requests, ("2-3","23",Just "2-3/16")
       expected: "23"
        but got: "23456789abcdef"

  2) Response, range requests, ("5-8","5678",Just "5-8/16")
       expected: "5678"
        but got: "56789abcdef"

  3) Response, partial files, (2,2,"23")
       expected: "23456789abcdef"
        but got: "23"

  4) Response, partial files, (0,2,"01")
       expected: "0123456789abcdef"
        but got: "01"

  5) Response, partial files, (3,8,"3456789a")
       expected: "3456789abcdef"
        but got: "3456789a"

  test\ResponseSpec.hs:104: (best-effort)
  6) Response.fileRange gets an error if a file does not exist
       expected: Left "attic/nonexist: getFileStatus: does not exist (No such file or directory)"
        but got: "3456789a"

  test\ResponseSpec.hs:104: (best-effort)
  6) Response.fileRange gets an error if a file does not exist
       expected: Left "attic/nonexist: getFileStatus: does not exist (No such file or directory)"
        but got: Left "getPermissions: does not exist (No such file or directory)"

  test\RunSpec.hs:274: (best-effort)
  7) Run, chunked bodies, in chunks
       uncaught exception: IOException of type OtherError (<socket: 1196>: hPutBuf: failed (Unknown error))

  test\SendFileSpec.hs:51: (best-effort)
  8) SendFile.readSendFile sends a file correctly (1)
       expected: ExitSuccess
        but got: ExitFailure 1

  test\SendFileSpec.hs:53: (best-effort)
  9) SendFile.readSendFile sends a file correctly (2)
       expected: ExitSuccess
        but got: ExitFailure 1

  test\SendFileSpec.hs:55: (best-effort)
  10) SendFile.readSendFile sends a file correctly (3)
       expected: ExitSuccess
        but got: ExitFailure 1
```

Let me know if you'd like me to review any of these in particular.

**Comment by kazu-yamamoto** [comment]
Thanks! Would you also attach the test result of the `master` branch on Windows so that I can identify which are specific to this topic branch?

**Comment by kazu-yamamoto** [comment]
I pushed a fix to the read-send-file branch. Please try this first. f1e0350d7148c94025ae46e36eac7e2f2bc7f2cc

**Comment by snoyberg** [comment]
Newest read-send-file results on Windows:

```
  test\ResponseSpec.hs:104: (best-effort)
  1) Response.fileRange gets an error if a file does not exist
       expected: Left "attic/nonexist: getFileStatus: does not exist (No such file or directory)"
        but got: Left "getPermissions: does not exist (No such file or directory)"

  test\RunSpec.hs:274: (best-effort)
  2) Run, chunked bodies, in chunks
       uncaught exception: IOException of type OtherError (<socket: 1212>: hPutBuf: failed (Unknown error))

  test\SendFileSpec.hs:51: (best-effort)
  3) SendFile.readSendFile sends a file correctly (1)
       expected: ExitSuccess
        but got: ExitFailure 1

  test\SendFileSpec.hs:53: (best-effort)
  4) SendFile.readSendFile sends a file correctly (2)
       expected: ExitSuccess
        but got: ExitFailure 1

  test\SendFileSpec.hs:55: (best-effort)
  5) SendFile.readSendFile sends a file correctly (3)
       expected: ExitSuccess
        but got: ExitFailure 1
```

Testing master next...

**Comment by snoyberg** [comment]
On Windows:

```
  test\ResponseSpec.hs:104: (best-effort)
  1) Response.fileRange gets an error if a file does not exist
       expected: Left "attic/nonexist: getFileStatus: does not exist (No such file or directory)"
        but got: Left "getPermissions: does not exist (No such file or directory)"

  test\RunSpec.hs:274: (best-effort)
  2) Run, chunked bodies, in chunks
       uncaught exception: IOException of type OtherError (<socket: 1088>: hPutBuf: failed (Unknown error))
```

**Comment by kazu-yamamoto** [comment]
Thank. Three more tests should be passed.

The `readSendFile` code enclosed by `#ifdef WINDOWS` works well on Linux/Mac (if I change the `#ifdef WINDOWS` to `#if 1`).  So, I guess that the `"cmp"` program does not exist on Windows. What kind of commands should we use on Windows?

BTW: is it OK with you to merge this branch to master?

**Comment by snoyberg** [comment]
I don't know of an equivalent of `cmp` that can be guarantee present on Windows.

I'm OK with this merging to master.

**Comment by kazu-yamamoto** [comment]
Thanks. Merged.
