### ISSUE TITLE
warp should support receiving secret data.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [yesodweb/wai#385]
@vincenthz has the securemem package which auto-scrubs memory on free.  warp should support something like this in a type-safe manner so that there is no possibility for secret data to leak outside of its containing buffer. 

I do not think this can be bolted on to warp, but must be supported at the type level from the socket read to the upper applications. 

https://hackage.haskell.org/package/securemem-0.1.9/docs/Data-SecureMem.html

**Comment by snoyberg** [comment]
I don't have any plans for how to implement this, do you want to take a crack at a PR?

**Comment by kazu-yamamoto** [comment]
I would close this issue. Please reopen if necessary.
