### ISSUE TITLE
cleaning up APIs

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#387]
`Network.Wai.Handler.Warp` exporting low level APIs and internal APIs. But we have `Network.Wai.Handler.Warp.Internal`, too. I would like to move them to `Network.Wai.Handler.Warp.Internal` so that `Network.Wai.Handler.Warp` gets simpler.

@snoyberg What do you think?

**Comment by snoyberg** [comment]
I'd like to have a deprecation cycle for whatever we're going to move, but honestly, I'm not too terribly concerned about it. Yes, doing something like this is a good idea, thank you for raising it.

**Comment by kazu-yamamoto** [comment]
OK. I will do two things:

-- Preparing a new rich `Network.Wai.Handler.Warp.Internal`
-- Making the low level ones and the internal ones in `Network.Wai.Handler.Warp.Internal` *deprecated*

One more question: `Network.Wai.Handler.Warp.Internal` has deprecated APIs. May I remove them? Or is it too early?

**Comment by kazu-yamamoto** [comment]
And please decide the next version number of Warp? I should write "Since: 3.X.Y" for new ones. I guess it should be 3.1.0.

**Comment by kazu-yamamoto** [comment]
Please merge #388. This does 1). But this does not do 2) because there is not a simple way to make reexported ones deprecated. The deprecated pragma must be used with declaration. To implement 2) for functions, we need a lot of boilerplates which I don't think pay. For types, it seems to me that 2) is impossible.

In the patch, the new document of `Network.Wai.Handler.Warp` just says "The following APIs will move to Network.Wai.Handler.Warp.Internal" in the Internal section.

@snoyberg Do you think that this is good enough? Or perhaps, we could remove the Internal section completely since there is just one user: WarpTLS.

**Comment by snoyberg** [comment]
I think of we announce the plan to remove functions, wait a week or two, and then do it, we can do basically whatever we want.

**Comment by kazu-yamamoto** [comment]
@snoyberg I will do the following:

- Setting the version to 3.1.0
- Removing the settingsXXX functions on github
- Leaving the internal ones on the top module and writing a document that these will be removed in 3.2.0
- Announcing this cleanup by yesodweb blog

Make sense?

**Comment by kazu-yamamoto** [comment]
All but blog are done on the master branch.

**Comment by snoyberg** [comment]
Yes sounds good

**Comment by kazu-yamamoto** [comment]
OK. I will write a blog article next week.
