### ISSUE TITLE
Incorrect docs for logStdout and logStdoutDev

### ISSUE THREAD

**Issue by levinotik** [yesodweb/wai#396]
RequestLogger was refactored in aa7d6318871f2d07cff8cb1c6bb2ceaa9ad2b15b, but the docs were not updated to reflect that change. It still states that `logStdout` and `logStdoutDev` are implemented on top of "logCallback" and "logCallbackDev"

```
-- | Production request logger middleware.
-- Implemented on top of "logCallback", but prints to 'stdout'
logStdout :: Middleware
logStdout = unsafePerformIO $ mkRequestLogger def { outputFormat = Apache FromSocket }
```

**Comment by snoyberg** [comment]
Good catch. Would you be able to send a PR to fix that?

**Comment by levinotik** [comment]
I was going to do that instead of creating the issue, but I'm not clear on what the docs *should* say. Should it just say `-- Implemented on top of 'RequestLogger'`? or should it mention apache as well?

**Comment by snoyberg** [comment]
Hmm, maybe mentioning "built on top of" is completely unnecessary. Simply saying what it does may be sufficient, especially since anyone can view source if desired.

**Comment by levinotik** [comment]
Ok, thanks. I'll prepare a quick PR.

**Comment by levinotik** [comment]
PR here https://github.com/yesodweb/wai/pull/397 sorry about the bad commit message formatting

**Comment by snoyberg** [comment]
Thanks!
