### ISSUE TITLE
Do not call the exception handler for timeouts

### ISSUE THREAD

**Issue by ndmitchell** [yesodweb/wai#398]
I do:

    runSettings (setOnException exception) ...

    exception :: Maybe Request -> SomeException -> IO ()
    exception r e
        | Just (_ :: InvalidRequest) <- fromException e = return ()
        | otherwise = print e

I don't want to print out invalid requests, so I skip them. I'd also rather not print out `TimeoutThread`, since these seem to be entirely internal Warp details? I suggest not calling `setOnException` for them at all. Alternatively, give a robust way to suppress them by exporting the exception type.

Or is there a better way to print the exceptions I care about?

**Comment by snoyberg** [comment]
Check out [defaultShouldDisplayException](http://haddock.stackage.org/nightly-2015-07-09/warp-3.0.13.1/src/Network-Wai-Handler-Warp-Settings.html#defaultShouldDisplayException), which is probably the behavior you're looking for.

**Comment by ndmitchell** [comment]
Thanks Michael, that is indeed what I'm after!
