### ISSUE TITLE
RC4 is dyning

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#400]
Now [RFC 7465](https://tools.ietf.org/html/rfc7465): "Prohibiting RC4 Cipher Suites" is published. We need to consider when we should remove RC4 from WarpTLS.

**Comment by snoyberg** [comment]
I'm OK removing it now. @vincenthz any thoughts on the matter?

**Comment by kazu-yamamoto** [comment]
FYI: http://www.rc4nomore.com/

**Comment by meteficha** [comment]
Thanks for the pointer.  +1 on removing.

**Comment by kazu-yamamoto** [comment]
If we agree to remove RC4, we need to decide when we do it: WarpTLS 3.1.0 or 3.2.0? I will release WarpTLS 3.1.0 in this week.

**Comment by snoyberg** [comment]
I'd say 3.1. This is just changing the default, not removing the capability
entirely, right?

**Comment by kazu-yamamoto** [comment]
Right.

So, what about providing`defaultTraditionalTlsSettings` which includes RC4?

**Comment by snoyberg** [comment]
Shrug. I'm fine with it, though I'm not convinced it's necessary. If you
want to go that route, feel free

**Comment by kazu-yamamoto** [comment]
Please see the commit above to know what I want to do exactly.

**Comment by kazu-yamamoto** [comment]
If we have `defaultTlsSettings` and `traditionalTlsSettings`, we can be more active to make `defautlTlsSettings` more modern. I would to discuss to remove re-negociation from `defaultTlsSettings`, too.

**Comment by erikd** [comment]
+1 on removing RC4
+1 on removing  re-negociation from `defaultTlsSettings`

**Comment by kazu-yamamoto** [comment]
I was wrong. The smart constructors (e.g. `tlsSettings`) modifiy `defaultTlsSettings`. `chainCertFiles` etc are not exported. So, we cannot modify `chainCertFiles` in `traditionalTlsSettings`.

@snoyberg What is the intention to hide `chainCertFiles` etc? Can we export them?

**Comment by snoyberg** [comment]
It's a backwards compatibility hack. A better approach would be to export setters like `setChainCertFiles` that will ensure that internal invariants are kept about in-memory vs in-file storage.

**Comment by kazu-yamamoto** [comment]
@snoyberg OK. We should not export these field names.

**Comment by kazu-yamamoto** [comment]
Now, things are clear to me.

`traditionalTlsSettings`:

- There is no way to control renegotiation of the "tls" lib so to satisfy the tests provided by https://www.ssllabs.com/ssltest/. I will bring this issue to the "tls" lib itself.
- There is no smart constructors which can modify `traditionalTlsSettings`.
- So, let's not define `traditionalTlsSettings`.

RC4:

- Let's remove RC4 now.
- The current doc is misleading. We should move the smart constructor part first, field names second. This leads users to use smart constructors first, then modify `tlsCiphers` if necessay.

I implemented this all and am satisfied. Please review the current code, everyone.

**Comment by kazu-yamamoto** [comment]
The renego issue now goes to https://github.com/vincenthz/hs-tls/issues/112.

**Comment by snoyberg** [comment]
LGTM

**Comment by kazu-yamamoto** [comment]
Let's close this.
