### ISSUE TITLE
Warp sends an empty data frame if no data is immediately available after the headers.

### ISSUE THREAD

**Issue by awpr** [yesodweb/wai#403]
This isn't illegal, but it's wasteful, and some clients don't handle it correctly.

This also appears to happen when a streaming application pushes an empty Builder, since it wakes up the waiter but does not write any actual payload to the frame.

**Comment by kazu-yamamoto** [comment]
Are you talking about `ResponseStream`?

**Comment by kazu-yamamoto** [comment]
`Builder` is not an instance of `Eq`. I have no idea to tell a Builder is empty or not.

**Comment by awpr** [comment]
Yes, for ResponseStream.  I have a change stashed currently that makes this work, by checking the amount of data that was actually written by the Builders, and skipping the frame if it was zero bytes.

I initially saw this happen when there was nothing in the output queue after sending headers, so there were no Builders at all.  Then I checked to see what would happen when sending an empty Builder.  So there are two separate causes, but both can be avoided with the same technique: if no data was written, do nothing instead of sending the frame.

**Comment by kazu-yamamoto** [comment]
Thanks. I'm waiting for your pull request.

**Comment by kazu-yamamoto** [comment]
Let's close this.
