### ISSUE TITLE
Warp treats exceeding the concurrency limit as a connection error.

### ISSUE THREAD

**Issue by awpr** [yesodweb/wai#404]
Per http://http2.github.io/http2-spec/index.html#rfc.section.5.1.2, servers are required to treat this as a stream error.  Warp should reset the offending stream instead of terminating the connection.  The relevant code is Receiver.hs:158.

I have a potential fix that I'll push to a fork shortly.

**Comment by awpr** [comment]
Proposed fix is https://github.com/awpr/wai/commit/2b8459979798ca9a88426f5482913023d4276ef3.

With this, Warp resets the offending stream, but treats further messages on it as stream errors.  I think that's a separate bug, though, since I don't see any code for ignoring frames for recently-reset streams.

**Comment by kazu-yamamoto** [comment]
I would like to have the test case in [h2spec](https://github.com/summerwind/h2spec) to see that the bug exists and is fixed after applying patch. @awpr Is it possible to do so?

**Comment by awpr** [comment]
This already appears to exist at https://github.com/summerwind/h2spec/blob/master/5_1.go#L307.  Perhaps it's always getting skipped when run against Warp?

**Comment by kazu-yamamoto** [comment]
Strange. Warp always passes the 5.1.2 test case of h2spec. @awpr Does warp fail the test in your environment?

Anyway, your patch looks perfect to me.

**Comment by awpr** [comment]
It does pass that test case because closing the connection is an allowable reaction here -- see the comments on the pull request.

**Comment by kazu-yamamoto** [comment]
I have just read it. Sorry for your inconvenience.
