### ISSUE TITLE
Warp/WAI gets an F from SSL Labs 

### ISSUE THREAD

**Issue by AaronFriel** [yesodweb/wai#412]
See [this test](https://www.ssllabs.com/ssltest/analyze.html?d=reactr.io&latest) for an example. 

SSL Labs says that it does not support secure renegotiation, but it appears the `tls` and `warp-tls` source both set `supportedSecureRenegotiation = True`.

**Comment by kazu-yamamoto** [comment]
Please see https://github.com/vincenthz/hs-tls/issues/112.

**Comment by kazu-yamamoto** [comment]
BTW, I'm planning to hack the tls library to get A+. :)

**Comment by AaronFriel** [comment]
Your patch gets me an A-. Awesome work, @kazu-yamamoto! 

https://www.ssllabs.com/ssltest/analyze.html?d=reactr.io
