### ISSUE TITLE
blaze-builder vs bytestring-builder

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#422]
The current code cannot be compiled with blaze-builder < 0.4 as reported in #420:

```
Network/Wai/Handler/Warp/HTTP2/Sender.hs:241:35:
    Couldn't match expected type ‘Data.ByteString.Builder.Internal.Builder’
                with actual type ‘Blaze.ByteString.Builder.Internal.Types.Builder’
    NB: ‘Data.ByteString.Builder.Internal.Builder’
          is defined in ‘Data.ByteString.Builder.Internal’
              in package ‘bytestring-0.10.6.0’
        ‘Blaze.ByteString.Builder.Internal.Types.Builder’
          is defined in ‘Blaze.ByteString.Builder.Internal.Types’
              in package ‘blaze-builder-0.3.3.4’
    In the first argument of ‘B.runBuilder’, namely ‘bb’
    In a stmt of a 'do' block:
      (len, signal) <- B.runBuilder bb datBuf room
```
This is because the HTTP/2 code does not support blaze-builder < 0.4.

@snoyberg Would you explain the current policy for blaze-builder? Do we have to support the old blaze-builder? Why not simply throw blaze-builder away and support bytestring-builder only?

**Comment by snoyberg** [comment]
If you put a lower bound on blaze-builder for >=0.4, then you can just use bytestring-builder. Otherwise, you'll end up in a situation where wai allows blaze-builder-0.3, and warp doesn't prevent it with bounds.

**Comment by kazu-yamamoto** [comment]
Do you think we should support blaze-builder < 0.4 in warp at this moment?

**Comment by snoyberg** [comment]
I don't feel strongly about it. If it's easy, I'd say yes. Otherwise, don't
bother

**Comment by kazu-yamamoto** [comment]
It's not difficult to implement it but it takes time. Moreover, it is difficult for me to test the implementation. And there are a lots of other things to do.

I would remove the support for blaze-builder and switch to bytestring-builder.

**Comment by snoyberg** [comment]
OK no objection

**Comment by kazu-yamamoto** [comment]
For `Response.hs`, `chunkedTransferEncoding` and `chunkedTransferTerminator` are necessary. Are there alternatives?

If not, I would use blaze-builder >= 0.4 only here.

**Comment by kazu-yamamoto** [comment]
See c43251b0db4dbd6b243152f743f569e919c389c8.

**Comment by snoyberg** [comment]
I'm unaware of alternatives, I'd agree with using blaze-builder for those functions.

**Comment by kazu-yamamoto** [comment]
Thanks. I will merge this patch.
