### ISSUE TITLE
Http2 question

### ISSUE THREAD

**Issue by seanwestfall** [yesodweb/wai#427]
Does http2 get turned on automatically in yesod? I got a running yesod 1.4.1 example server running on GHC version 7.10.2, and it runs warp 3.1.3, but it's still be served via HTTP 1.1, at least according to the header. Does something need to be configured in yesod for it to start using HTTP/2? Or how do I know yesod is running HTTP2 other than via the response header?

This is the response header I got in Chrome 44.0.2403.157 (64-bit).
```
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Date: Mon, 31 Aug 2015 08:11:13 GMT
Server: Warp/3.1.3
Content-Type: text/html; charset=utf-8
Set-Cookie: _SESSION=lyn7nyaZ0ZZJOJ6yvWtMdSAkv9FV34B3wahYLLWjNcuL2ssnLHYCdsxAIFR46W4zn1/DmUh4Jawc6b4T0KGWrDfBELNz+FOwkw/VvJ2vZxGbd9chyhUpbP2jwbfF4H7V/d/c5LJfqOw=; Path=/; Expires=Mon, 31-Aug-2015 10:11:12 GMT; HttpOnly
Vary: Accept, Accept-Language
```

**Comment by kazu-yamamoto** [comment]
Chrome and Firefox require TLS to use HTTP/2. HTTP/2 is negotiated by TLS (the ALPN extension).

**Comment by awpr** [comment]
In more detail: Warp doesn't yet support non-TLS HTTP/2 upgrades.  If the browser sends the header "Upgrade: h2c", Warp will ignore it and continue serving over HTTP/1.1.  Over TLS, though, we always go through ALPN negotiation and advertise 'h2-someversion', and the browser will choose HTTP/2 if it supports it.

For non-TLS connections the only way to get into HTTP/2 currently is to use the magic connection prefix for HTTP/2-only requests ("PRI * something..."), which I don't think any browsers currently do (because it intentionally makes connections to old HTTP servers fail).

So, for now, as far as web browsers are concerned, Warp HTTP/2 support is effectively only enabled over TLS.

**Comment by seanwestfall** [comment]
Hmm, thanks for the response:
On Chrome 44, when viewing the default yesod through https://127.0.0.1:3443/, the request header says this (in parsed format): 
```
:authority:127.0.0.1:3443
:method:GET
:path:/
:scheme:https
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding:gzip, deflate, sdch
accept-language:en-US,en;q=0.8
cache-control:max-age=0
cookie:_SESSION=1T5NXhWQeOAiAP027XzCqacgTARr45ymKlYXBJeydM9V7V7JongVXtRcqvfihDEkZvr9b+HZPDSzZiMDSoD4QzkVRjTGCjdf1pASf2RMliTnaxY94w9smZI/m2xC2n62nMlXW1aYG5Y=
upgrade-insecure-requests:1
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
```
Chrome doesn't include anything to indicate you're viewing a site through http2 -- in fact you can't even switch the header response from 'view parsed' to 'view source' -- maybe because it can't read the http2 format..

Though in Firefox 38.0.5, the response header says:
```
Content-Type: text/html; charset=utf-8
Date: Wed, 02 Sep 2015 05:33:47 GMT
Server: Warp/3.1.3
Set-Cookie: _SESSION=aOSe+T11KAzWxSdxCxng8gIAUpaBmxLPsi3CVaf298REvCYIVMmzJpLoL+4QybhLSskFWeDDO0pghmPGiti70gVTpSWSqRcGIQHwBh22AJUmDiMwjuJPs1TX3o8/28SYiEPSEsfzWFw=; Path=/; Expires=Wed, 02-Sep-2015 07:33:42 GMT; HttpOnly
Vary: Accept, Accept-Language
X-Firefox-Spdy: h2
```
X-Firefox-Spdy: h2 indicates it's a http2 site. So I guess it's working! Good job, and cool project guys!

**Comment by awpr** [comment]
You can also check active HTTP/2 sessions in chrome://net-internals.

**Comment by kazu-yamamoto** [comment]
Using the native developer tool of Firefox and Chrome, you can check which they are using.

**Comment by awpr** [comment]
I didn't know this until just now: you can enable displaying the protocol in the Network requests table as described by https://ma.ttias.be/view-http-spdy-http2-protocol-google-chrome/.
