### ISSUE TITLE
Warp fails to install on OpenBSD

### ISSUE THREAD

**Issue by cimmanon** [yesodweb/wai#428]
Adding OpenBSD to the list of operating systems that should include Hashable in the cabal file doesn't work because OpenBSD does not have `sendfile()`.

```
Downloading warp-3.1.3...
Configuring warp-3.1.3...
Building warp-3.1.3...
Preprocessing library warp-3.1.3...

Network/Wai/Handler/Warp/FdCache.hs:29:8:
    Could not find module `Data.Hashable'
    It is a member of the hidden package `hashable-1.2.3.3'.
    Perhaps you need to add `hashable' to the build-depends in your .cabal file.
    It is a member of the hidden package `hashable-1.2.2.0'.
    Perhaps you need to add `hashable' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
Failed to install warp-3.1.3
```

**Comment by awpr** [comment]
Does it work if you add "-f -allow-sendfilefd" to the cabal command-line?  That should force it not to use `sendfile()` even when it thinks it's on an OS that supports it.

**Comment by cimmanon** [comment]
No, that doesn't change anything.

**Comment by awpr** [comment]
Ah, FdCache.hs imports it unconditionally, so you'd need to add hashable to the build-depends (outside the part that's conditional on allow-sendfilefd) -- what you did before was presumably adding it to the whitelist of OSes that support sendfile.  For a real fix, we should probably move the hashable build-depends entry to everything but Windows (since the whole file is stubbed out to be a no-op on Windows).

**Comment by cimmanon** [comment]
Yes, adding hashable to the build-depends outside the conditional lets it install, but the resulting library can't be used.  I don't know if this linking problem is related or a separate issue.

```
 Loading package warp-3.1.3 ... linking ... ghc: /home/adam/servanttest/.cabal-sandbox/lib/x86_64-openbsd-ghc-7.8.4/warp-3.1.3/libHSwarp-3.1.3.a: unknown symbol `warpzm3zi1zi3_NetworkziWaiziHandlerziWarpziMultiMap_Tom_con_info'
ghc: unable to load package `warp-3.1.3'
Failed to install wai-app-static-3.1.1
```

**Comment by awpr** [comment]
Oh, the cabal file gives a hint there: it builds MultiMap only if we're using sendfile, but FdCache also uses MultiMap.  Try moving the MultiMap "Other-modules" line to the same place as the hashable dependency.

**Comment by kazu-yamamoto** [comment]
I hope the patch above solves the problem.

**Comment by kazu-yamamoto** [comment]
I would like to close this. Please reopen if necessary.
