### ISSUE TITLE
Safari does not work with new Warp TLS

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#429]
@tathougies reported in http://www.yesodweb.com/blog/2015/08/ssl-server-test

Probably we should add 3DES.

**Comment by kazu-yamamoto** [comment]
`TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384`, which is not specified in Warp TLS, is selected. `TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256` should be selected. I think that this is a bug of the tls library.

**Comment by tathougies** [comment]
Bug already filed on the tls library github, but I'm afraid I lack the expertise to be able to adequately debug.

tls bug: https://github.com/vincenthz/hs-tls/issues/119

**Comment by kazu-yamamoto** [comment]
Safari does not implement SHA512 correctly. https://github.com/Caligatio/jsSHA/issues/3

I know that the tls library of golang also has this bug. Sigh.

I would propose to remove SHA384 and SHA512 from `supportedHashSignatures`.

**Comment by kazu-yamamoto** [comment]
Cc: @AaronFriel Just for your information.

**Comment by kazu-yamamoto** [comment]
@tathougies  Don't worry. I will take care of this tomorrow.

**Comment by AaronFriel** [comment]
I'm opposed to adding 3DES, that's a clear regression in terms of security. I don't think it's worth it to support 3DES by default, at least.

The quick fix seems to be to do as @kazu-yamamoto suggested and remove SHA384 and SHA512 based ciphers. SHA256 is not considered insecure by anyone, so this isn't a security issue. (It's not like we'd be removing support for all SHA-2 based ciphers, just two problematic ones.)

I hope an issue has been filed with Apple re: SHA384 and SHA512?

**Comment by kazu-yamamoto** [comment]
I have removed SHA 384 and SHA 512. I don't add 3DES. I confirmed that the patch above rescue Safari 8 and golang tls.

**Comment by AaronFriel** [comment]
Very peculiar. I haven't looked at the other thread in detail. Does `tls` implement SHA384/512 incorrectly or is it golang and Safari?

**Comment by kazu-yamamoto** [comment]
I believe that golang and Safari suck. When Safari received a SHA512 signature, it returns an alert.

**Comment by kazu-yamamoto** [comment]
I have released a new version.
