### ISSUE TITLE
Range requests not working with http2

### ISSUE THREAD

**Issue by dylex** [yesodweb/wai#431]
It looks like http2 file range responses don't work.  There's no accept-ranges header in responses, and requests with range headers always return a full 200 rather than a 206.  (This complely breaks video streaming.)  Do I have to do something different to make this work in http2 or manually implement range handling?

(On a separate note, as we've had a number of issues with http2, is there anyway to disable it completely? I tried to manually override the upgrade handler in tls but didn't get it to work.)

**Comment by awpr** [comment]
I think the currently-released version doesn't implement that (see https://github.com/yesodweb/wai/blob/warp-tls/3.1.3/warp/Network/Wai/Handler/Warp/HTTP2/Sender.hs#L275 which just always selects the full file); however I have an über-pull-request going that includes a change implementing it, namely https://github.com/yesodweb/wai/commit/7c34e4582ccfabafd9903b1ff12ac3a5a4e823dc (see #426).

This reminds me it forgets to set accept-ranges, but that's easy enough to fix.

For disabling HTTP/2: I'm not aware of a way to disable it, but it shouldn't be too difficult to add an alternative no-HTTP2 run function (similar to https://github.com/yesodweb/wai/blob/4c110f4f499e4bba524e128200a6d569c76ee784/warp-tls/Network/Wai/Handler/WarpTLS.hs#L233) or a Bool in the Settings to disable it.

**Comment by dylex** [comment]
That looks exciting, thanks! I've been trying to figure out whether you actually need to include accept-ranges in http/2.  Clients appear to request ranges automatically even without it, but it's not clear.  Probably it's safer to include it.  I'll give your PR a shot when I can and see if it makes our app work.

We've downgraded to wai 3.0 again for now. I'd vote that incompletely implemented features weren't just silently enabled by default, but oh, well.

**Comment by awpr** [comment]
IIRC servers that don't support range serving are required (or maybe encouraged?) to ignore Range headers and send 200 OK with the full contents, so it seems like clients should be safe to send Range headers regardless of the Accept-Ranges header.  Indeed "A client MAY generate range requests without having received this header field for the resource involved."

I don't actually see how the Accept-Ranges header could be useful -- if you're getting the header, you've already sent the request for the resource, so it can't be used to decide whether to request a range.  Maybe it was meant to be used in conjunction with HEAD requests?

**Comment by dylex** [comment]
For HTTP1, I can say for sure that accept-ranges is required for a number of browsers, at least for video streaming.  Many browsers (including safari and IE, and older chrome and firefox) send a speculative GET for the full resource, and when they see an accept-ranges, send a new request with a range header, otherwise they assume it won't work. I haven't done enough testing with http2, but the browsers that support it also don't need accept-ranges for http1 either anymore.

**Comment by dylex** [comment]
FWIW basic http2 streaming range requests are now working with warp 3.1.4 on chrome and firefox/39, chrome/45, and safari/7. We can do more extensive next week, but generally looks good, thanks!

**Comment by dylex** [comment]
We're still getting sporadic SPDY/connection errors in both chrome and firefox, even without range requests.  Is there any way to turn off http2 altogether?

**Comment by dylex** [comment]
This seems now to work well across Chrome, Firefox, and Edge.

**Comment by kazu-yamamoto** [comment]
@dylex Does it mean that cfe9824 solves your problem?

**Comment by dylex** [comment]
Along with 7c34e4582ccfabafd9903b1ff12ac3a5a4e823dc yes, now that we've been able to test it properly, byte range requests (and video streaming) seem to be handled properly.

**Comment by kazu-yamamoto** [comment]
@dylex Thanks.
