### ISSUE TITLE
A next release

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#434]
I'm now trying to fix two vulnerabilities of Warp. After I fix them, I would like to release new Warp (and WAI). Before that, I would like to make consensus on versions:

- The next WAI version is 3.1.0 since it provides `Network.WAI.HTTP2`.
- The next Warp version is 3.2.0 because of new APIs such as `runHTTP2`.
- The HTTP/2 features in WAI 3.1.0 and in Warp 3.2.0 are trial and subject to change. We will release solid versions WAI 3.2.0 and Warp 3.3.0.

@snoyberg Do you agree to export the new module `Network.WAI.HTTP2`? Just in case where you don't understand: `Application` can serve for both HTTP/1 and HTTP/2 seamlessly. `HTTP2Application` can make use of HTTP/2 specific features including server push.

@snoyberg May I remove the internal APIs from `Network.WAI.Handler.Warp`? Or is it too early? http://hackage.haskell.org/package/warp-3.1.3/docs/Network-Wai-Handler-Warp.html#g:9

@awpr Do you agree with this direction?

**Comment by awpr** [comment]
Sounds good to me.  Warp will need to change the lower bound on the WAI dependency to 3.1.0 then, right?

**Comment by kazu-yamamoto** [comment]
Exactly.

**Comment by kazu-yamamoto** [comment]
@snoyberg Pinging.

**Comment by snoyberg** [comment]
It doesn't look like these are breaking changes. Exposing a new module should be a minor version bump. AFAICT, the original modules have been unchanged in behavior.

Removing the internal APIs _would_ be a major version bump, but if there are no other major breaking changes in this release, I'd recommend doing that bump separately, so that people still on the current major version don't get stuck without the new functionality.

**Comment by kazu-yamamoto** [comment]
OK. So,

- the next wai is 3.0.4.0
- the next warp is 3.1.4 requiring wai >= 3.0.4.0

**Comment by snoyberg** [comment]
:+1:

**Comment by kazu-yamamoto** [comment]
@snoyberg I would like upload wai 3.0.4.0 but I don't have the right to do so. Please add me to its maintainer group.

**Comment by snoyberg** [comment]
Done

**Comment by kazu-yamamoto** [comment]
@snoyberg Than you!

**Comment by kazu-yamamoto** [comment]
I have released wai 3.0.4.0 and warp 3.1.4.

@awpr Thank you for your contribution!
