### ISSUE TITLE
Collaborating with http-types

### ISSUE THREAD

**Issue by charleso** [yesodweb/wai#439]
[Both](https://github.com/yesodweb/wai/search?utf8=%E2%9C%93&q=hContentRange) [warp/Network/Wai/Handler/Warp/Types.hs](https://github.com/yesodweb/wai/blob/c5001a0fb8100a425e68b09a38c32b83bd69384f/warp/Network/Wai/Handler/Warp/Types.hs#L36) and [wai/Network/Wai/Internal.hs](https://github.com/yesodweb/wai/blob/ac96dc569708a5a3c7df9906ddd2a9f58ff30a2d/wai/Network/Wai/Internal.hs#L167) define  `hContentRange`. This leads to the following:

```
Network/Wai/Handler/Warp/Response.hs:107:43:
    Ambiguous occurrence ‘parseByteRanges’
    It could refer to either ‘Network.Wai.Handler.Warp.RequestHeader.parseByteRanges’,
                             imported from ‘Network.Wai.Handler.Warp.RequestHeader’ at Network/Wai/Handler/Warp/Response.hs:54:48-62
                             (and originally defined
                                at Network/Wai/Handler/Warp/RequestHeader.hs:138:1-15)
                          or ‘Network.Wai.Internal.parseByteRanges’,
                             imported from ‘Network.Wai.Internal’ at Network/Wai/Handler/Warp/Response.hs:58:1-27

Network/Wai/Handler/Warp/Response.hs:394:25:
    Ambiguous occurrence ‘hAcceptRanges’
    It could refer to either ‘Network.Wai.Handler.Warp.Types.hAcceptRanges’,
                             imported from ‘Network.Wai.Handler.Warp.Types’ at Network/Wai/Handler/Warp/Response.hs:57:1-37
                             (and originally defined
                                at Network/Wai/Handler/Warp/Types.hs:40:1-13)
                          or ‘Network.Wai.Internal.hAcceptRanges’,
                             imported from ‘Network.Wai.Internal’ at Network/Wai/Handler/Warp/Response.hs:58:1-27

Network/Wai/Handler/Warp/Response.hs:406:39:
    Ambiguous occurrence ‘hContentRange’
    It could refer to either ‘Network.Wai.Handler.Warp.Types.hContentRange’,
                             imported from ‘Network.Wai.Handler.Warp.Types’ at Network/Wai/Handler/Warp/Response.hs:57:1-37
                             (and originally defined
                                at Network/Wai/Handler/Warp/Types.hs:37:1-13)
                          or ‘Network.Wai.Internal.hContentRange’,
                             imported from ‘Network.Wai.Internal’ at Network/Wai/Handler/Warp/Response.hs:58:1-27
```

From [warp/Network/Wai/Handler/Warp/Response.hs](https://github.com/yesodweb/wai/blob/c5001a0fb8100a425e68b09a38c32b83bd69384f/warp/Network/Wai/Handler/Warp/Response.hs)

``` haskell
import Network.Wai.Handler.Warp.Types
import Network.Wai.Internal
...
addContentRange beg end total hdrs = (hContentRange, range) : hdrs
```

I believe this might have been introduced here: https://github.com/yesodweb/wai/commit/7c34e4582ccfabafd9903b1ff12ac3a5a4e823dc

**Comment by awpr** [comment]
The error message doesn't really match your prose -- it refers to ambiguity of `parseByteRanges`, not `hContentRange`.  Nonetheless I bet the issue here is that wai 3.0.4.0 doesn't work with warp < 3.1.4 because of this ambiguity.

You should be able to work around it by explicitly requesting warp 3.1.4 or avoiding wai 3.0.4.0, but I'm not really sure what the best way to address this is in general.  We might be able to go back and release warp 3.1.3.1 to add an identifier list to that import, but that doesn't help with '==3.1.3' constraints.

**Comment by charleso** [comment]
@awpr Apologies, copied the wrong error message in my haste. There was about `hContentRange` as well. I've fixed my compiler errors locally already by restricting `wai`, but just thought you might like to know.

**Comment by charleso** [comment]
Have updated the error to the full thing

**Comment by kazu-yamamoto** [comment]
I think the best way to solve this is define `Content-Range` in http-types.

@aristidb Are there any reasons to not define `Content-Range` in http-types? It is a standard header defined in https://tools.ietf.org/html/rfc7233#section-4.2

**Comment by awpr** [comment]
+1 to having hContentRange in http-types, but the issue I'm unsure about is what to do about wai-3.0.4.0 breaking compatibility with all versions of warp that import the whole Network.Wai.Internal module and also define parseByteRanges.  Renaming Wai's version of parseByteRanges is problematic since it would break warp 3.1.4.

**Comment by kazu-yamamoto** [comment]
Uhhm. It sounds like that we should have bumped major versions. (#434)

**Comment by kazu-yamamoto** [comment]
BTW. What is the best position for `parseByteRanges`? In http-types?

**Comment by awpr** [comment]
Actually, yeah, I do remember wondering why it wasn't in `http-types`.

My understanding is it's not normally required to bump major versions for *adding* exported names.  The only reason it was a problem here is that we imported the whole module with "import Network.Wai.Internal".  In general I don't think it's possible to make any change to a package's exports at all while maintaining compatibility with code that does that.

**Comment by kazu-yamamoto** [comment]
Let's contribute `hContentRange` and `parseByteRanges` to http-types. @aristidb Are you OK with this?

However, I have no idea on how to solve the current mismatch except just asking upgrading wai and warp.

**Comment by awpr** [comment]
Apparently it's possible to amend package metadata on Hackage after-the-fact.  I think we should apply the upper bound < 3.0.4.0 to some number of old warp versions so they will continue to build.

**Comment by aristidb** [comment]
hContentRange is in http-types 0.9. I'd be open for parseByteRanges in
http-types if it doesn't add dependencies.

Andrew Pritchard <notifications@github.com> schrieb am Di., 6. Okt. 2015 um
00:20 Uhr:

**Comment by kazu-yamamoto** [comment]
`parseByteRanges` has been merged into http-types on github.

**Comment by kazu-yamamoto** [comment]
http-types v0.9.1 including `parserByteRanges` has been released.

**Comment by kazu-yamamoto** [comment]
Fixed. Let's close.
