### ISSUE TITLE
wai-extra FTB: requires network >= 2.6.1.0

### ISSUE THREAD

**Issue by ygale** [yesodweb/wai#446]
The cabal file for wai-extra claims that wai-extra works with versions of network that are quite old: network >= 2.2.1.5. However, the module `Network.Wai.Middleware.RequestLogger.JSON` now references the constructor `SockAddrCan` of `SockAddr`, imported from `Network.Socket`. That only was introduced in a very recent version of network: 2.6.1.0.

Since the network package is commonly pinned to a not-too-recent version to avoid build complexities on Windows, this cabal error causes widespread build failures for wai-extra.

**Comment by snoyberg** [comment]
I've increased the lower bound.

**Comment by snoyberg** [comment]
Also, out of curiosity: what does FTB stand for? I did a quick search, but
none of the results sound like something I'd ever hear you say ;)

**Comment by ygale** [comment]
Thanks!

FTB is Debian slang, for "fails to build".

**Comment by ygale** [comment]
I was about to hit send on a PR and you beat me :)
