### ISSUE TITLE
Build error in wai-extra 3.0.11

### ISSUE THREAD

**Issue by nek0** [yesodweb/wai#447]
building wai-extra version 3.0.11 as a dependency of my own project results in this error:
```
Network/Wai/Middleware/RequestLogger.hs:132:27:
    No instance for (Data.String.IsString B.Builder)
      arising from the literal ‘""’
    In the first argument of ‘newIORef’, namely ‘""’
    In a stmt of a 'do' block: builderIO <- newIORef ""
    In the expression:
      do { t1 <- getCurrentTime;
           date <- liftIO getdate;
           builderIO <- newIORef "";
           res' <- recordChunks builderIO res;
           .... }
```

Can somebody please look into this, I don't really understand, what's going on there.

**Comment by gregwebs** [comment]
Looks like  this is fixed on master already. @awpr do you want me to release the fix to hackage?

**Comment by awpr** [comment]
The one I fixed was only in wai, not wai-extra.  It's another instance of
the same problem, though -- looks like it was introduced by the JSON
logging PR.  We have the same choices here: bump blaze-builder to 0.4 or
add 'fromByteString' on string literals used as Builders.

**Comment by gregwebs** [comment]
Thanks! I will make the change and release a new version of wai-extra

**Comment by nek0** [comment]
can this find its way into hackage, please?

**Comment by gregwebs** [comment]
its up as 3.0.11.1
