### ISSUE TITLE
How to disable http/2?

### ISSUE THREAD

**Issue by dylex** [yesodweb/wai#450]
We've been testing every released version of warp and warp-tls and are still getting ERR_SPDY_PROTOCOL_ERROR in recent chrome and network errors in firefox with warp 3.1.6 and warp-tls 3.1.3 and all other packages updated. This causes serious enough problems that we cannot put any of these in production, but keeping warp 3.0.4.2 in production is becoming more difficult because of incompatibilities with other packages. Is there some option just to disable http2 until things work properly?

**Comment by dylex** [comment]
For clarity, this is using `runTLS`. I tried setting `onALPNClientSuggest = Nothing` but it seems to just ignore this and set it back. The problems primarily happen whenever there is a cookie request header -- otherwise most things work. I'd be happy to try to diagnose, but I'm not sure the best way to get a trace (wireshark can't decrypt with DH and the browsers complain if you disable it; enabling warp-debug doesn't seem to do anything). I'll gladly write a PR to add an HTTP2 option to `TLSSettings` or `Settings` if you'll accept it.

**Comment by kazu-yamamoto** [comment]
I would like to provide a way to disable HTTP/2.
