### ISSUE TITLE
Splitting "Set-Cookie:" headers

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#455]
Cookie and Set-Cookie should be split to increase the compression ratio of HPACK. In Warp, multiple Cookie headers in a request are now concatenated. But a Set-Cookie in a response is not split.

https://github.com/yesodweb/wai/blob/master/warp/Network/Wai/Handler/Warp/HTTP2/HPACK.hs#L25

@dylex @ptek Are you interested in implementing this feature?

**Comment by dylex** [comment]
I'm not sure I understand. The "set-cookie" header is not allowed to contain multiple cookies either in http 1.1 or 2, and http 1.1 responses already may contain multiple set-cookie headers. Only the "cookie" header is treated specially in http/2.

**Comment by kazu-yamamoto** [comment]
Uhhm. The author of h2o said to me that h2o splits set-cookie. I will check.

**Comment by dylex** [comment]
It doesn't seem to. It looks like it was incorectly merging them at some point, though: h2o/h2o#427

**Comment by kazu-yamamoto** [comment]
I was chatted with the author of h2o and confirmed that h2o does not split set-cookie. Sorry for bothering you guys. Let's close this.
