### ISSUE TITLE
Using a later resolver and stack.yaml file.

### ISSUE THREAD

**Issue by urbanslug** [yesodweb/wai#456]
In an attempt to add a new package https://github.com/urbanslug/wai I ran into an issue because the resolver for wai is 2.17.

Is there is a reason wai can't use a resolver such as 3.* ? Since I am depending on ide-backend 0.10 onwards which isn't in the resolver for 2.* If we must keep the current resolver I 
could look for a fix in the extra deps section of the stack.yaml file.

Also just generally upgrading the stack file to a later "model".

**Comment by snoyberg** [comment]
No, no problem. PR welcome!
