### ISSUE TITLE
Wai-App-Static: How do you define a custom 404 page?

### ISSUE THREAD

**Issue by jhickner** [yesodweb/wai#464]
Hello,

I couldn't find this in the docs or on hackage - how do you specify a custom 404 page for wai-app-static?

Thanks!

**Comment by snoyberg** [comment]
There's no hook available for that yet, but it should be pretty easy to add. Want to take a shot at adding a setting for this?

**Comment by jhickner** [comment]
Sure. I think the simplest approach would be to add a new setting that lets you specify a `MimeType` and a `ByteString` payload to send in case of 404, then insert some new logic into the `NotFound` handler here that delivers it. The `MimeType` setting would be optional and default to `text/plain` and the `ByteString` setting would be optional as well and default to the current value of "File not found". Sound OK?

```haskell
response NotFound = sendResponse $ W.responseLBS H.status404
                        [ ("Content-Type", "text/plain")
                        ] "File not found"
```

**Comment by snoyberg** [comment]
How about just making it an Application to handle not founds, to allow for
maximum extensibility?

**Comment by snoyberg** [comment]
Yup, I think so
