### ISSUE TITLE
Setting 'secure' flag on cookie yields 401

### ISSUE THREAD

**Issue by abailly** [yesodweb/wai#474]
I have a scotty application using warp and I use cookies to transport authentication tokens. So I set `HttpOnly` and `Secure` flags on the cookie. But then requests going through plain HTTP are rejected with `401 Unauthorized`. I thought those flags were only meant for use by client but it seems they are also verified by warp. This is annoying because our server is running in plain HTTP behing a nginx server working in reverse proxy mode and which itselfs uses HTTPS.

Am I misunderstanding how things should work? Is there a way to disable that behaviour?

**Comment by snoyberg** [comment]
I believe what's happening is that the client is not sending the cookie over HTTP (due to `Secure`), and as a result your application is failing due to the missing auth information. Is it possible that the client is sending an insecure request to nginx?

**Comment by abailly** [comment]
Ah. What happens here is that I am working only in integration tests so this means I am using wreq hence under the hood http-client to make the request. And because we are in tests the server runs in HTTP mode and not HTTPS and the client rightfully rejects passing the cookie back to the server over an insecure link. This makes sense, indeed. 

The problem could be solved by running the application within a secured server, e.g. warp-tls instead of warp but it seems scotty uses directly warp under the hood. I will investigate how to run it with warp-tls instead...
