### ISSUE TITLE
Correct logging for files

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#475]
Only `sendResponse` knows the correct size to be sent and the final status. For instance, if `sendResponse` processes `Range:`, the size to be sent would be changed and the status would be change from 200 to 206.

Unfortunately, there is no fields to specify logging actions in `Response`. So, my wai applications cannot record correct logs for files.

@snoyberg Are there any ways to implement correct logging for files?

**Comment by snoyberg** [comment]
The two ways I can see are:

1. Move the Range handling logic into a middleware instead of Warp itself
2. Allow Warp to receive a setting which will be the logging function

If (1) can be implemented without hurting performance, it's probably the cleaner solution, but I'm not sure that's possible.

**Comment by kazu-yamamoto** [comment]
Thanks. I will try (2).

**Comment by kazu-yamamoto** [comment]
Done. This works quite well for me.
