### ISSUE TITLE
Streaming data to warp/wai over http1.1 returns invalid chunked-encoding response.

### ISSUE THREAD

**Issue by jb55** [yesodweb/wai#476]
`<big-data.csv curl --http1.1 --data-binary @- 'http://localhost:8999'`

Mysteriously enough it works fine if the input is less than 1024 bytes!

If it's larger then that, I get this message from curl:

```
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
```

When I switch to `--http1.0` it works fine. I'm testing this with [streaming-wai](https://hackage.haskell.org/package/streaming-wai). I've yet to try other streaming-wai libs but I'm not convinced it's an issue with that yet.

I realize this is a pretty vague bug report, so I plan on putting together a minimal failing example for this soon, but I thought I'd throw this up here in the meantime.

**Comment by kazu-yamamoto** [comment]
This report makes sense to me.

HTTP/1.0 uses one-shot connection by default. So, Warp does not use HTTP chunk for HTTP/1.0 by default.

Anyway, this report suggests that chunk of Warp has a bug. I'm waiting for a minimal example.

**Comment by Vlix** [comment]
@jb55 Can you remember if you ever managed to fix this, and if it's important enough to pour time into this, or can this issue be closed? (`streaming-wai` is also 7 years old now)
