### ISSUE TITLE
Too weak lower bound on http-types

### ISSUE THREAD

**Issue by snoyberg** [yesodweb/wai#479]
```
[23 of 35] Compiling Network.Wai.Handler.Warp.File ( Network/Wai/Handler/Warp/File.hs, .stack-work/dist/x86_64-osx/Cabal-1.22.4.0/build/Network/Wai/Handler/Warp/File.o )

/Users/michael/Documents/wai/warp/Network/Wai/Handler/Warp/File.hs:143:37:
    Not in scope: ‘H.hContentRange’
    Perhaps you meant one of these:
      ‘H.hContentLength’ (imported from Network.HTTP.Types.Header),
      ‘H.hContentLength’ (imported from Network.HTTP.Types),
      ‘H.hContentType’ (imported from Network.HTTP.Types.Header)

/Users/michael/Documents/wai/warp/Network/Wai/Handler/Warp/File.hs:160:41:
    Not in scope: ‘H.hAcceptRanges’

--  While building package warp-3.1.9 using:
      /Users/michael/.stack/setup-exe-cache/setup-Simple-Cabal-1.22.4.0-x86_64-osx-ghc-7.10.2 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.22.4.0 build lib:warp --ghc-options " -ddump-hi -ddump-to-file"
```

@kazu-yamamoto Like previously, I'd recommend avoiding usage of the new values, and instead just using the raw strings.

**Comment by kazu-yamamoto** [comment]
I'm OK with acc8f8c710352ba2a35c1bc458ed05f3eb34b088.

**Comment by snoyberg** [comment]
OK, I'll cherry-pick to master.

**Comment by kazu-yamamoto** [comment]
When https://travis-ci.org/yesodweb/wai/builds/95300667 shows all greens, we should release new warp and warp-tls. May I ask you to do so?

**Comment by snoyberg** [comment]
I'd like to wait until I get my new Stack/Cabal split Travis setup going too, any objection? I'll merge that in without your review if you're OK with it.

**Comment by kazu-yamamoto** [comment]
No objection. I'm not in hurry. I guessed you are in hurry because of yesod. You can release whenever you like.

For new Stack/Cabal, I'm OK if the three major GHCs are supported.

**Comment by snoyberg** [comment]
No, there's no hurry from my side either actually, I already put a workaround into yesod-bin for this, so there's no pressure. I just happen to have time to work on this now :)

**Comment by kazu-yamamoto** [comment]
@snoyberg I think that you forgot to push tags. Please push them.

**Comment by snoyberg** [comment]
Which tag is missing? I released warp-3.1.10, and the tag warp/3.1.10 is in the repo. I made no release of warp-tls.

**Comment by kazu-yamamoto** [comment]
I cannot see `warp/3.1.10` yet.

**Comment by snoyberg** [comment]
I see it here: https://github.com/yesodweb/wai/tree/warp/3.1.10

**Comment by kazu-yamamoto** [comment]
298b92362a77214ff5b20ff8d2d7b25f119b27e3 is not on the master. Which branch does it belong to?

**Comment by kazu-yamamoto** [comment]
OK. No branch. In this case, we need to do `git fetch --tags`. I understand.

**Comment by snoyberg** [comment]
Sorry, I pushed the missing commits to master.
