### ISSUE TITLE
warp-3.1.10 fails to compile on WINDOWS

### ISSUE THREAD

**Issue by andygill** [yesodweb/wai#481]
warp is looking for http-date's modules, which are conditionally compiled out of WINDOWS.

Specifically:

    import  Network.HTTP.Date

in `Network/WAI/Handler/Warp/Date.hs` needs to be #ifdef'd out on WINDOWS, or equivalent.

**Comment by snoyberg** [comment]
@kazu-yamamoto are you able to look into this?

**Comment by kazu-yamamoto** [comment]
I will take care of this tomorrow.

**Comment by kazu-yamamoto** [comment]
@andygill Does 34d8981230ec0a942284fba5fe600e750d44d9c6 solve your problem?

**Comment by andygill** [comment]
I'm not sure - I've not got access to a WINDOWS machine. I'll get the student that uses WINDOWS to try it. (From looking at the patch, it should work)

**Comment by RyanGlScott** [comment]
34d8981230ec0a942284fba5fe600e750d44d9c6 appears to fix the build for me on Windows with GHC 7.10.2, but it does produce some warnings (if you care about making it `-Wall`-compliant):

```
[ 9 of 34] Compiling Network.Wai.Handler.Warp.Date ( Network\Wai\Handler\Warp\Date.hs, interpreted )

Network\Wai\Handler\Warp\Date.hs:21:1: Warning:
    The import of `formatTime' from module `Data.Time' is redundant

Network\Wai\Handler\Warp\Date.hs:22:1: Warning:
    The import of `posixSecondsToUTCTime'
    from module `Data.Time.Clock.POSIX' is redundant
```

**Comment by andygill** [comment]
I debugged the problem live on a student's WINDOWS laptop, and don't remember who it was I was helping. So Ryan's build is good enough for me. Thanks Ryan! Should I close the ticket?

**Comment by kazu-yamamoto** [comment]
@RyanGlScott Thank you for your reports. I pushed a commit to prevent the warnings.
