### ISSUE TITLE
runHTTP2TLS doesn't respect setInstallShutdownHandler

### ISSUE THREAD

**Issue by fhsjaagshs** [yesodweb/wai#483]
Given the following:

    settings :: Settings
    settings = setInstallShutdownHandler installShutdown defaultSettings
      where
         installShutdown killSockets = do
           void $ installHandler sigTERM (handler killSockets) Nothing
           void $ installHandler sigINT (handler killSockets) Nothing
         handler killSockets = Catch $ killSockets >>  putStrLn "shut down"

    app :: Application
    app = -- any app will do

If I use

    runHTTP2TLS defaultTlsSettings settings (promoteApplication app) app

The signal handlers won't be installed. However, when I do

    runHTTP2Settings settings (promoteApplication app) app

the signal handlers will be installed. 

In plain warp, the following code path happens:

`runHTTP2Settings` > `runServeSettings` > `runServeSettingsSocket` > `settingsInstallShutdownHandler set closeListenSocket`. This installs my handler properly.

However, in `warp-tls`:

`runHTTP2TLS` > `runServeTLS` > `runServeTLSSocket` > `runServeTLSSocket'` > `runServeSettingsConnectionMakerSecure`, which runs the accept loop. Nowhere along this chain is my `installHandler` action called.

For the time being, I wrote this function:

    runHTTP2TLSHandled :: TLSSettings -> Settings -> HTTP2Application -> Application -> IO ()
    runHTTP2TLSHandled tset set wai2 wai = withSocketsDo $
      bracket (bindPortTCP (getPort set) (getHost set)) sClose $ \socket -> do
          settingsInstallShutdownHandler set (sClose socket)
          runHTTP2TLSSocket tset set socket wai2 wai

**Comment by kazu-yamamoto** [comment]
Relating to #470.

**Comment by kazu-yamamoto** [comment]
This API is obsoleted. If another APIs have this issue, please open another issue.
