### ISSUE TITLE
Warp doesn't use sendfile() on Solaris.

### ISSUE THREAD

**Issue by patrickt** [yesodweb/wai#484]
Line 101 of warp.cabal: 
`if (os(linux) || os(freebsd) || os(darwin)) && flag(allow-sendfilefd)`

I'm not sure what the correct `os()` invocation is for Solaris (`sunos`?), but Solaris has supported sendfile for ages.

**Comment by jaredmorrow** [comment]
According to the cabal docs, it uses the `System.Info.os` call.  So in SmartOS's case, it should be: `os(solaris2)`

```
GHCI version 7.10.2: http://www.haskell.org/ghc/  :? for help
Prelude> System.Info.os
"solaris2"
```

**Comment by patrickt** [comment]
Actually, you'd need a new .hsc file in simple-sendfile, so never mind.
