### ISSUE TITLE
Does not handle correctly multiple Cookie headers in HTTP/2 requests

### ISSUE THREAD

**Issue by abailly** [yesodweb/wai#486]
I have started using warp-tls-3.1.3 and encounter an issue with Cookies. When a user-agent send multiple `Cookie` headers, only the first one gets parsed and supernumerary headers are dropped. 

AFAICT this is indeed conformant to [RFC625](http://tools.ietf.org/html/rfc6265#section-5.4). But according to [HTTP/2](https://http2.github.io/http2-spec/#CompressCookie) specification, multiple Cookie headers are allowed. I have googled a bit and found a similar issue in [netty](https://github.com/netty/netty/issues/4457) where I got my understanding of this issue. 

Am I missing something? Is there a way to instruct browser to use HTTP/1.1?

**Comment by kazu-yamamoto** [comment]
Multiple cookie values are concatenated into a single one. If you don't see multiple values in a single cookie, it's a bug. Please give us examples.

**Comment by abailly** [comment]
Tentative unit tests in #487

**Comment by kazu-yamamoto** [comment]
@abailly Can you try https://github.com/yesodweb/wai/tree/http2-starting-over? This branch has efficient code to make multiple cookies to a single on HTTP/2. It will be merged to the master soon but it breaks backward compatibility.

**Comment by abailly** [comment]
Sure. Are the tests I provide meaningful and correct?

**Comment by abailly** [comment]
I tried to run the given unit tests against branch `http2-starting-over` but got same issue.

**Comment by kazu-yamamoto** [comment]
First of all, your test case for HTTP/2 uses HTTP/2, not HTTP/1.1.

Which do you talk about, HTTP/1.1 or HTTP/2?

- HTTP/1.: Multiple cookies are not allowed. Warp does not concatenate multiple cookies into a single one.

- HTTP/2: Clients are still able to send a single cookie. But HTTP/2 layer divided it into multiple so that HPACK works efficiently. HTTP/2 code of Warp concatenates multiple cookies into a single one and passes it to WAI applications.

**Comment by abailly** [comment]
I assume you meant it uses HTTP/1.1 instead of HTTP/2. How can I trigger
use of HTTP/2 ? Sorry I am not familiar with HTTP/2 yet...

I triggered this issue because I have seen Firefox sending multiple cookie
headers so not sure I understand your second comment. I will fix first test
case to make it pass, I agree current behavior is compliant with standards.



Le mercredi 16 décembre 2015, Kazu Yamamoto <notifications@github.com> a
écrit :

> First of all, your test case for HTTP/2 uses HTTP/2, not HTTP/1.1.
>
> Which do you talk about, HTTP/1.1 or HTTP/2?
>
>    -
>
>    HTTP/1.: Multiple cookies are not allowed. Warp does not concatenate
>    multiple cookies into a single one.
>    -
>
>    HTTP/2: Clients are still able to send a single cookie. But HTTP/2
>    layer divided it into multiple so that HPACK works efficiently. HTTP/2 code
>    of Warp concatenates multiple cookies into a single one and passes it to
>    WAI applications.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yesodweb/wai/issues/486#issuecomment-165008459>.
>


-- 
-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by kazu-yamamoto** [comment]
Sorry. Fixed the comment above.

**Comment by kazu-yamamoto** [comment]
Let me confirm. Are you sure that Firefox uses HTTP/1.1? Did you confirm it, for instance, by tcpdump?

**Comment by abailly** [comment]
Definitely not sure, only checked from the firefox debug window and from
our logs. In our logs protocol shows http/2 and in firefox window I can see
multiple cookies sent, as well as when I dump the raw request content. I am
confused again... What is the simplest way to activate HTTP/2 in tests ?

-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by kazu-yamamoto** [comment]
Use develop tool in Firefox. It shows HTTP/1.1 or HTTP/2 for every requests.

**Comment by abailly** [comment]
I would rather do it in a unit test... I will check in the code then.

-- 
Arnaud Bailly

twitter: abailly
skype: arnaud-bailly
linkedin: http://fr.linkedin.com/in/arnaudbailly/

**Comment by creativeprogramming** [comment]
I confirm this issue, i'm not a netty direct user, but I'm using vert.x 3 that uses netty 4.1.1 and when a client negotiates http/2 i cannot read all the cookies in the cookie header (i got just one cookie of many).

If i disable ALPN instead i get all the cookies.

**Comment by kazu-yamamoto** [comment]
I believe this problem does not exist. Consider:

```
{-# LANGUAGE OverloadedStrings #-}
import Network.Wai
import Network.HTTP.Types (status200)
import Network.Wai.Handler.Warp (run)
import Data.ByteString.Lazy.Char8

application req respond = do
    print req
    respond $ responseLBS status200 [("Content-Type", "text/plain")] (pack $ show req)

main = run 3000 application
```

And test with nghttp:

```
% nghttp -H "cookie: a=b" -H "cookie: c=d" http://127.0.0.1:3000/
Request {requestMethod = "GET", httpVersion = HTTP/2.0, rawPathInfo = "/", rawQueryString = "", requestHeaders = [("Host","127.0.0.1:3000"),("Cookie","a=b; c=d"),("Accept","*/*"),("Accept-Encoding","gzip, deflate"),("User-Agent","nghttp2/1.17.0")], isSecure = True, remoteHost = 127.0.0.1:56554, pathInfo = [], queryString = [], requestBody = <IO ByteString>, vault = <Vault>, requestBodyLength = KnownLength 0, requestHeaderHost = Just "127.0.0.1:3000", requestHeaderRange = Nothing}
```

**Comment by kazu-yamamoto** [comment]
I confirmed that multiple cookies are actually sent with tcpdump and Wireshark.
Let's close.
