### ISSUE TITLE
Weak ThreadId still leaks threads

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#488]
It is well known that threads are leaked if we hold their `ThreadId`s. That's why we are using `Weak ThreadId` in Warp. Even if we hold `Weak ThreadId`s, stacks of the threads are released. However, other data structures relating to the threads are not released. We can watch this by `+RTS -hT`.

I believe that this is a bug of GHC. Probably relating to: https://ghc.haskell.org/trac/ghc/ticket/10812

Since the timeout manager takes actions every 30 seconds, the data structures are leaked for 30 seconds maximum. This can be easily fixed to introduce `IORef` to `onTimeout`.

**Comment by kazu-yamamoto** [comment]
@snoyberg In addition to introduce `IORef` to `onTimeout`, I would like to add a new API - `killManager` which actually kills the timeout manager immediately. This is very important for HTTP/2 since a timeout manager is launched for every HTTP/2 connection. After closing an HTTP/2 connection, the manager should go away immediately. For this, I would like to introduce ` reaperKill` to `Reaper`. 

I have already confirmed that this works well on my local branch. @snoyberg What do you think?

**Comment by snoyberg** [comment]
I don't see any problem with such a change.

**Comment by kazu-yamamoto** [comment]
Done in the merged branch above. We use ThreadId instead of Weak ThreadId and ensure that ThreadId is released quickly.

**Comment by kazu-yamamoto** [comment]
@snoyberg I would like to release a new version of auto-update. Would you add me to the maintainer list?

**Comment by snoyberg** [comment]
Added

**Comment by kazu-yamamoto** [comment]
Thanks. Released.
