### ISSUE TITLE
WAI 3.2

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#489]
Let's perpare WAI 3.1:

- wai: 3.0 -> 3.1- bumps up because of breaking change. 
- warp 3.1 -> 3.2 - bumps up because of breaking change. I will also remove the internal APIs from `Network.Wai.Handler.Warp`
- warp-tls 3.1 -> 3.2 - bumps up because of breaking change.

**Comment by kazu-yamamoto** [comment]
@snoyberg For number consistency, should we use 3.2 for wai, too?

**Comment by snoyberg** [comment]
Yes, I'd say jump straight to 3.2 for wai.

**Comment by kazu-yamamoto** [comment]
I'm satisfied with the current master. The performance of HTTP/2 is comparable with that of HTTP/1.1. 

@snoyberg My concern is Travis CI failures which I don't figure out. Would you take a look?

**Comment by snoyberg** [comment]
The failures are valid; the warp version number was bumped, but some of the other packages have restrictive upper bounds. Should be easy to resolve.

**Comment by snoyberg** [comment]
I've just pushed a commit to hopefully resolve the build failures.

**Comment by snoyberg** [comment]
Alright, Travis is passing again.

**Comment by kazu-yamamoto** [comment]
Thanks. But the version of warp was not bumped to 3.2 yet. I don't know why f232956 is necessary.

**Comment by snoyberg** [comment]
Mistake on my part, the only change necessary was upgrading the http2 package version in the stack.yaml file. I've pushed two more changes for this.

**Comment by kazu-yamamoto** [comment]
Thanks.

Are you OK to release WAI 3.2 series maybe in the beginning of the next year?

**Comment by snoyberg** [comment]
I'd say let's do it now, before LTS 4 is released. Is it ready to go?

**Comment by kazu-yamamoto** [comment]
OK.

I will release wai 3.2 first, then warp and warp-tls.

**Comment by kazu-yamamoto** [comment]
Done.

**Comment by kazu-yamamoto** [comment]
@snoyberg Would you release wai-conduit for wai 3.2?

**Comment by snoyberg** [comment]
There are a number of packages that require a bounds bump, I'll take care
of that.

**Comment by wiz** [comment]
Hmm.. Hackage was hit with 3.2, but changelog weren't updated.

**Comment by kazu-yamamoto** [comment]
It's my fault. Sorry. Unfortunately, I'm now on winter vacation. I will take care of this in the next year.

**Comment by kazu-yamamoto** [comment]
Closing in favor of #500.
