### ISSUE TITLE
wai-websockets not exception safe

### ISSUE THREAD

**Issue by danielkeller** [yesodweb/wai#491]
When I throw an exception from a websockets server app run with `websocketsOr`, I get `WebSocket connection to '...' failed: Invalid frame header` (in chrome). However, when I throw an exception in the same way from a server run from `Network.WebSockets.runServer`, I don't get any error.

**Comment by Vlix** [comment]
I believe this has been fixed in the following commits:

* 000a181079a80eaf2f54efbfb8f8a302f106d497
* 23c7a07682b3183fab6b822b9570c5fcd02f7484
* 2b622b3baa13b523fcfdd2ed487e7b5ddb48d391
