### ISSUE TITLE
Does not build on Windows 7 (nor 10 apparently).

### ISSUE THREAD

**Issue by mark4asp** [yesodweb/wai#492]
I'm trying to install warp because I want to install hoogle, and it's a dependency. The build log gives no additional information.  What's the best way to proceed?  Can I download, build and install it locally? If so will it matter if I install a later warp?

Here is the command line dialog:

C:\Programs>cabal install warp-3.1.10
Resolving dependencies...
Configuring warp-3.1.10...
Building warp-3.1.10...
Failed to install warp-3.1.10
Build log ( C:\Users\mark\AppData\Roaming\cabal\logs\warp-3.1.10.log ):
Building warp-3.1.10...
Preprocessing library warp-3.1.10...

Network\Wai\Handler\Warp\Date.hs:18:8:
    Could not find module `Network.HTTP.Date'
    Perhaps you meant
      Network.HTTP.Base (needs flag -package-key HTTP-4000.2.20@HTTP_5XqAraNG0KY3iQ8yoFqqWa)
      Network.HTTP.Auth (needs flag -package-key HTTP-4000.2.20@HTTP_5XqAraNG0KY3iQ8yoFqqWa)
      Network.HTTP.Base64
    Use -v to see a list of the files searched for.
cabal: Error: some packages failed to install:
warp-3.1.10 failed during the building phase. The exception was:
ExitFailure 1

**Comment by snoyberg** [comment]
You can use `cabal unpack warp` to unpack to a local directory, and then
build inside that.

**Comment by ndmitchell** [comment]
@snoyberg, I don't see why unpacking warp first would be desirable at all? Surely that just introduces more opportunities to get it wrong.

I note there is version 3.1.11 now out, but I've got no idea what that contains (#497), and it won't build for, but that itself has build issues (#495).

**Comment by kazu-yamamoto** [comment]
The "http-date" package should be installed. Usually, it is automatically installed when you are installing warp. I don't know what happened.

**Comment by kazu-yamamoto** [comment]
I will release warp 3.1.12 including fixes for both issues very soon.

**Comment by mark4asp** [comment]
Rather than mess about, I reinstalled EclipseFP and Haskell (using a later version) and hoogle works now.
