### ISSUE TITLE
What happened to HTTP2 Server push in the latest commits?

### ISSUE THREAD

**Issue by fhsjaagshs** [yesodweb/wai#502]
Since the HTTP2 code was removed from WAI, what happened to HTTP2 server push? I see there is an error thrown in `warp/Network/Wai/Handler/Warp/HTTP2/Receiver.hs` by `processStreamGuardingError` when a `FramePushPromise` is encountered. Does this mean it's no longer implemented? If that's the case, would a pull request implementing server push be accepted at this time?

**Comment by awpr** [comment]
That code means that the server will treat PUSH_PROMISE frames sent _by the client_ as an error, which is the only sensible behavior.

The server push changes to Warp (and probably a few of my bug fixes as well) were removed along with the alternate WAI HTTP/2 interface, which changed all responses to a streaming style, introducing unforeseen overhead (for synchronization).  As far as I know, that's the only problem with my series of changes, so the server push implementation hiding in the history should be just fine -- it's probably just a matter of playing forward most of the same changes and adjusting the APIs along the way (and double-checking performance at the end).

**Comment by fhsjaagshs** [comment]
Are there any plans for a new HTTP2 interface?

**Comment by kazu-yamamoto** [comment]
@fhsjaagshs Please read #470.

The current performance of HTTP/2 is almost the same as that of HTTP/1. :-)

The next target is server push and TLS issues (which you can find according to the `tls` label). I'm now snow under on writing a paper about HTTP/2. But after finishing it, I will try them.
