### ISSUE TITLE
Handling of missing host header field

### ISSUE THREAD

**Issue by sir-murray** [yesodweb/wai#503]
http://tools.ietf.org/html/rfc7230#section-5.4

> A server MUST respond with a 400 (Bad Request) status code to any
> HTTP/1.1 request message that lacks a Host header field and to any
> request message that contains more than one Host header field or a
> Host header field with an invalid field-value.

To test I used this:

```haskell
{-# LANGUAGE OverloadedStrings     #-}
{-# LANGUAGE QuasiQuotes           #-}
{-# LANGUAGE TemplateHaskell       #-}
{-# LANGUAGE TypeFamilies          #-}
import Yesod
import Data.Text.Encoding (decodeUtf8)
import Network.Wai (requestHeaders)

data Test = Test

mkYesod "Test" [parseRoutes|
/ HomeR GET
|]

instance Yesod Test

getHomeR :: Handler Html
getHomeR = do
    r <- waiRequest
    let host = maybe "[None]" decodeUtf8 (lookup "host" . requestHeaders $ r)
    defaultLayout [whamlet|#{host}|]

main :: IO ()
main = warp 3000 Test
```

Missing Host:
```
λ nc localhost 3000
GET / HTTP/1.1

HTTP/1.1 200 OK
Date: Wed, 06 Jan 2016 10:28:57 GMT
Server: Warp/3.1.3.1 + Yesod/1.4.15 (core)
Content-Length: 76
Content-Type: text/html; charset=utf-8
Set-Cookie: _SESSION=zXJ8hMJRzjdLbu0FUm6NcbUFNycmuMf7OUbOnspmtYz4L1OwTiyfGhTiUWLhGuAomC7EK6lrO/0Tx03nHUIn4IVTMk7G/jaVmeX1CaWbaFsUu2RxmcJA2LSOUatYQtkiquK+dQ9BOWI=; Path=/; Expires=Wed, 06-Jan-2016 12:28:49 GMT; HttpOnly
Vary: Accept, Accept-Language

<!DOCTYPE html>
<html><head><title></title></head><body>[None]</body></html>
```

More than one host header:
```
λ nc localhost 3000
GET / HTTP/1.1
Host: dave
Host: lisa

HTTP/1.1 200 OK
Date: Wed, 06 Jan 2016 10:33:25 GMT
Server: Warp/3.1.3.1 + Yesod/1.4.15 (core)
Content-Length: 74
Content-Type: text/html; charset=utf-8
Set-Cookie: _SESSION=YkPKCtQZxis+ply4e2kmkT1Ln/rLyac6mSgaM8M+sO0vToJTSPKJ783sIaX9qVyUC0k6RSTfVnZGmqEAp0zLZUfMjRCX+9mnFq0QWESm0P7ogN50kTb2opprSIDOSAbpOWl3VtWSPLo=; Path=/; Expires=Wed, 06-Jan-2016 12:33:16 GMT; HttpOnly
Vary: Accept, Accept-Language

<!DOCTYPE html>
<html><head><title></title></head><body>dave</body></html>
```
Invalid host header:
```
λ nc localhost 3000
GET / HTTP/1.1
Host: dave,lisa

HTTP/1.1 200 OK
Date: Wed, 06 Jan 2016 10:34:16 GMT
Server: Warp/3.1.3.1 + Yesod/1.4.15 (core)
Content-Length: 79
Content-Type: text/html; charset=utf-8
Set-Cookie: _SESSION=l20ogGiiIt59La3m+xQokw0iT987Xr5jx5NEgWH3ioSCbtEvcPct4KE6RS4kcQz5tr5grKhAgzHr9+tpkXPeyLFejblAhhVjAHlqSVf1ed4YYUsknMVVIb1yFmJk1Pbhk6ITNVBSfdc=; Path=/; Expires=Wed, 06-Jan-2016 12:34:06 GMT; HttpOnly
Vary: Accept, Accept-Language

<!DOCTYPE html>
<html><head><title></title></head><body>dave,lisa</body></html>
```

**Comment by meteficha** [comment]
How do other popular servers (i.e., Apache, nginx, IIE) handle these corner cases?  Answering this question will give us an idea about the question that matters the most: how many clients out there would no longer work given a stricter implementation?

**Comment by sir-murray** [comment]
Apache returns 400 on missing host but works fine with the other two:

```
λ nc localhost 80
GET / HTTP/1.1

HTTP/1.1 400 Bad Request
```
```
λ nc localhost 80
GET / HTTP/1.1
Host: dave,lol

HTTP/1.1 200 OK
```
```
λ nc localhost 80
GET / HTTP/1.1
Host: dave
Host: lisa

HTTP/1.1 200 OK
```

I don't have nginx but [this](http://serverfault.com/questions/740597/nginx-allow-requests-without-a-host-header) implies it returns 400 for missing host field.

I doubt there are many(if any) clients that send multiple hosts or an invalid host.

**Comment by sir-murray** [comment]
A lot of websites use shared hosting so the Host header field is pretty much necessary to use the internet at all nowadays.
See here:
http://stackoverflow.com/questions/535053/which-webbrowsers-use-http-1-1-by-default

Looks like unless you want to support Netscape 1.1 this should not be an issue.

**Comment by meteficha** [comment]
Thanks for the research, @sir-murray, it looks like it would be better for us to stand by the standard then.

**Comment by snoyberg** [comment]
I'm not convinced of the value of this:

* The desired functionality can be achieved outside of Warp via a middleware (or in the application) trivially. The reverse is not true: once we change Warp's behavior, no one can regain its current functionality.
* It doesn't simplify the application writer's job: due to the presence of HTTP 1.0, you still need to consider the case of missing or multiple host headers.
* It's convenient to write simple tests with minimal request headers, and this will require all such tests to be modified. (I know I've done such things in the past.)
* There doesn't seem to be a concrete benefit to doing this besides be compliant with the spec, though in this case the spec is specifically avoiding the principle of "be lenient in what you accept."

**Comment by sir-murray** [comment]
I'm happy to validate this in my application, I just thought something like this belongs in warp if it's meant to be compliant.

Also I notice now, it should only do the check if the request is in fact HTTP/1.1
But I'll only fix that if you decide you want to merge it.

**Comment by snoyberg** [comment]
@kazu-yamamoto do you want to weigh in here?

Two things I think would be completely unobjectionable would be:

* Adding a new middleware to wai-extra to perform this check
* Add the feature to Warp as a setting, with the default turned off

Less objectionable would be a settings with the default turned on, but still not on obvious "yes we should."

**Comment by kazu-yamamoto** [comment]
I'm snow under now. Let me tackle this on in the next week.

**Comment by snoyberg** [comment]
Thanks Kazu!

**Comment by kazu-yamamoto** [comment]
Just FYI about Warp implementation:

- HTTP/1.0: `requestHeaderHost` is always `Nothing`
- HTTP/1.1: `requestHeaderHost` is `Just the-last-Host:` if any. Otherwise, `Nothing`.
- HTTP/2: `requestHeaderHost` is `Just the-value-of-:authority` if exists. If not, `Just the-first-Host:` if any. Otherwise, `Nothing`.

**Comment by kazu-yamamoto** [comment]
If multiple Host:s should be treated as 400, what about the case where other important headers are duplicated?

**Comment by kazu-yamamoto** [comment]
What can we rescue if we implement 400 for multiple Host:?

**Comment by snoyberg** [comment]
If we implement 400 inside Warp itself, there is no opportunity at all for applications to recover, which is where my reservations about this feature come from.

**Comment by kazu-yamamoto** [comment]
I would like to leave Warp as it is for this issue.
