### ISSUE TITLE
Move warp-tls to cryptonite

### ISSUE THREAD

**Issue by ndmitchell** [yesodweb/wai#514]
The author of your various aes libraries in warp-tls (@vincenthz) says these packages are deprecated in favour of cryptonite. I suggest you move your library over to the new dependencies. See http://tab.snarc.org/posts/haskell/2015-06-02-announcing_cryptonite.html

**Comment by kazu-yamamoto** [comment]
`warp-tls.cabal` requires tls >= 1.3.2. On the other hand, `cprng-aes` is necessary for tls < 1.3.0. So, let's remove the dead code to remove the dependency to `cprng-aes`.

**Comment by kazu-yamamoto** [comment]
@snoyberg Please close this issue if you are OK with the patch above.

**Comment by vincenthz** [comment]
looking good to me.

**Comment by snoyberg** [comment]
LGTM, thanks @kazu-yamamoto!
