### ISSUE TITLE
What is the Maybe Integer logger parameter?

### ISSUE THREAD

**Issue by chris-martin** [yesodweb/wai#521]
I think this could use some documentation:

    settingsLogger :: Request -> H.Status -> Maybe Integer -> IO ()
    -- ^ A log function. Default: no action.

I surmise that the `Maybe Integer` is a response body length, but what I can't exactly tell is: In what circumstances is it `Nothing`?

**Comment by snoyberg** [comment]
@kazu-yamamoto can you comment on this?

**Comment by kazu-yamamoto** [comment]
Yes. `Integer` is body length. `Nothing` is used when the length is unknown in advance. (e.g. streaming).

A pull request to improve the documentation is welcome.

**Comment by kazu-yamamoto** [comment]
Done. Let's close.
