### ISSUE TITLE
Negative file size in directory listing on 32-bit Linux

### ISSUE THREAD

**Issue by huggablemonad** [yesodweb/wai#524]
The file size shows `-1,855,979,520 B`. The actual size is `2.3G` (`2,438,987,776 B`). I'm running `warp-3.2.3` on 32-bit Linux.

![warp-int-overflow](https://cloud.githubusercontent.com/assets/17948023/13941331/7f25dd5c-f021-11e5-93fb-73984d3a2821.jpg)
The file downloads fine (tested with `wget` and `vivaldi` browser).

**Comment by snoyberg** [comment]
Can you give the latest code on master a shot? I pushed a potential fix.

**Comment by huggablemonad** [comment]
Yup, the fix works. Thanks!

![warp-dir-list](https://cloud.githubusercontent.com/assets/17948023/13984541/d1e07550-f131-11e5-9d9e-84d6d56847b3.jpg)
