### ISSUE TITLE
How to use it with let's encrypt certificate?

### ISSUE THREAD

**Issue by Chimaku** [yesodweb/wai#533]
I want to use Servant + Warp (wai) with HTTPS. I've generated a certificate of "let's encrypt". What do I do next? 

And why does it say "**Support for SSL is now obsoleted. HTTP/2 can be negotiated by ALPN. API docs and the README are available at http://www.stackage.org/package/warp-tls.**" at https://hackage.haskell.org/package/warp-tls?

**Comment by kazu-yamamoto** [comment]
To use TLS, you need to install warp-tls. I have not used let's encrypted yet but I think that you can specify server's certificate, chain file and secret key to `TLSSettings`.

SSLv1 and SSLv2 are obsoleted by IETF. We should use TLS 1.2 (or TLS 1.1 or TLS 1.0 if necessary). That's why warp-tls stopped using SSL anymore.

**Comment by Chimaku** [comment]
> SSLv1 and SSLv2 are obsoleted by IETF. We should use TLS 1.2 
how should I do that?

I have this:

 
    import Network.Wai
    import Network.Wai.Handler.Warp
    import Servant
    import Network.Wai.Handler.WarpTLS

    startApp :: IO ()
    startApp = do
      let port = 3345
      let tls = tlsSettings "certificate.csr" "key.pem"
      runTLS tls (setPort port defaultSettings) app
 

And an error  "empty certificate chain". It's on localhost. My certificate generated as follows:

    openssl genrsa -out key.pem 2048
    openssl req -new -key key.pem -out certificate.csr
    openssl x509 -req -in certificate.csr -signkey key.pem -out certificate.pem

All of the files of certificated are in the folder of my application.

**Comment by alexanderkjeldaas** [comment]
The message "Support for SSL is now obsoleted." is very confusing for those that use SSL and TLS interchangeably.

As you probably know, the name TLS has no technical meaning in itself, and was just chosen to avoid a lawsuit from Netscape.  Thus a lot of people use "SSL" for the whole range of protocols, including all the TLS ones.

**Comment by kazu-yamamoto** [comment]
@alexanderkjeldaas Thank you for pointing it out.

Is "SSLv1 and SSLv2 are obsoleted by IETF. We should use TLS 1.2 (or TLS 1.1 or TLS 1.0 if necessary). " fair enough?

**Comment by alexanderkjeldaas** [comment]
Sounds good to me.

**Comment by kazu-yamamoto** [comment]
Done.
Thank you!
