### ISSUE TITLE
wai-handler-launch should not launch a browser if server startup failed ?

### ISSUE THREAD

**Issue by simonmichael** [yesodweb/wai#537]
In https://github.com/simonmichael/hledger/issues/226, if server startup fails, eg because of the port being in use, I don't want to show users a useless browser window. 

I think we could propagate exceptions from the forked server thread back to the parent, which would prevent the launch. And/or, we could expose the monitored server starting and the cross-platform browser launching as separate features, allowing more control.

**Comment by snoyberg** [comment]
Sounds like a good change, either setOnBeforeMainLoop or the new
withApplication function may be useful. Interested in sending a PR?

**Comment by simonmichael** [comment]
Here's one that seems to work. I hope adding async is acceptable..

**Comment by snoyberg** [comment]
Resolved by PR #541
