### ISSUE TITLE
How can I change a header in middleware?

### ISSUE THREAD

**Issue by Chimaku** [yesodweb/wai#545]
My goal is redirect to "example.com" if the requested domain is "www.example.com". How can I do that with middleware?

      app :: Application
      app req respond = do
        case requestHeaderHost req of
          Just host -> do
            -- if it has  "www" then 
            -- case ...... of 
              True -> respond =<< redirect' status302 [] "example.com"  -- ok
              False -> ---???? how to make it proceed to "startApp" or  just further

          Nothing -> error "it should never reach it"
        
      startApp :: IO ()
      startApp = do
        let tls = tlsSettings ......
        runTLS tls (.....) app

Note that it's  a **Servant** app, but since Servant is built on top on Wai, I'm asking my question here.

The question is my code: in case of False, how can I make it proceed? 
Also I'm not certain that the "app" is actually middleware. Is it?

**Comment by snoyberg** [comment]
Have you looked at examples of other middlewares in wai-extra? They should provide pretty clear guidance on how to modify requests and responses in middlewares.

**Comment by kazu-yamamoto** [comment]
I would close this issue. Please reopen if necessary.
