### ISSUE TITLE
Right way to write a middleware that inspects request body?

### ISSUE THREAD

**Issue by singpolyma** [yesodweb/wai#548]
I have this middleware:

```
kikHmacCheck :: ByteString -> Middleware
kikHmacCheck token app request respond = do
   body <- LZ.toStrict <$> strictRequestBody request
   if show (hmacGetDigest (hmac token body) :: Digest SHA1) == sig then
         app request respond
      else
         respond  $ responseLBS unauthorized401 [] (s"Signature verification failed")
   where
   sig = T.toLower $ decodeUtf8 $ fromMaybe empty $ lookup (s"X-Kik-Signature") $ requestHeaders request
```

Pretty simple.  But because it needs to inspect the request body, then when the actual application calls `strictRequestBody` or anything else, it just gets blank.  This seems like a very unexpected side-effect from the application author's point of view (adding a middleware should not cause my body to dissapear!) -- is there any way I can "put the body back" so that downstreams see it properly?

**Comment by singpolyma** [comment]
If I import `.Internal`, I can use a helper like this to generate a new `IO ByteString` with the right behaviour and shove it onto the request I pass on:

```
valueThenEmpty :: ByteString -> IO (IO ByteString)
valueThenEmpty x = do
   value <- newIORef (LZ.fromStrict x)
   return $ atomicModifyIORef value $ \x -> (x, empty)
```

**Comment by snoyberg** [comment]
That's exactly what you have to do. I believe some of the middlewares in wai-extra demonstrate the technique.

**Comment by kazu-yamamoto** [comment]
I would close this issue. Please reopen if necessary.
