### ISSUE TITLE
warp-tls: Please document how to serve HTTP and HTTPS from the same server

### ISSUE THREAD

**Issue by joshtriplett** [yesodweb/wai#55]
I'd like to serve both HTTP and HTTPS from the same Yesod-based application, using the same event loop.  In my case, I'd like to have all HTTP requests redirect to HTTPS; other applications might wish to serve some requests via HTTP and other requests via HTTPS.  Either way, I don't want to have to run a separate application or web server just to serve these redirects.  Please consider adding documentation (to warp-tls or some other appropriate place) showing how to handle both HTTP and HTTPS from the same Yesod app.

**Comment by EDmitry** [comment]
Did you find a solution to this? I am also interested in how to achieve this.
