### ISSUE TITLE
ChaCha20 and Poly1305 as equal preference to AES-GCM

### ISSUE THREAD

**Issue by DemiMarie** [yesodweb/wai#550]
ChaCha20-Poly1305 should be supported and should be equally preferred (assuming AES-GCM hardware support) or strongly preferred (otherwise) to AES-GCM, as ChaCha20-Poly1305 is faster in software and much easier to harden vs. timing attacks.

AES256-GCM should also be supported.

**Comment by kazu-yamamoto** [comment]
Right.

I hope that Warp can support them. I'm very sorry but I'm now terribly busy. I have no time to check if cryptonite library supports it.

If it is easy for you to add them to Warp, please give us a pull request.

**Comment by kazu-yamamoto** [comment]
This is done by `tls` and warp-tls is ussing `ciphersuite_strong`.
Let's close.
