### ISSUE TITLE
wai-websockets: forkPingThread writes to socket FD after connection is closed

### ISSUE THREAD

**Issue by mkscrg** [yesodweb/wai#552]
_Demo in a gist here: <https://gist.github.com/mkscrg/8c1d0cb1a1623348eed90f6d76f8121a>_

I'm not sure if this is an issue with `warp`, `wai-websockets`, or `websockets`. Let me know if I'm barking up the wrong tree!

`websockets`'s [`forkPingThread` is a loop](https://github.com/jaspervdj/websockets/blob/6a70dbad8f5efd88c72f287d7a81a0a63cda7c0f/src/Network/WebSockets/Connection.hs#L277) on `sendPing`, which when backed by `warp` and `wai-websockets` [is just `Network.Socket.ByteString.sendAll`](https://github.com/yesodweb/wai/blob/master/warp/Network/Wai/Handler/Warp/Run.hs#L60). The loop goes on pinging even after warp's connection is closed. This is OK, assuming the FD index under the connection is invalid at that moment: `network` throws an exception and the ping thread dies silently as intended.

Unforunately that's not a reliable condition. FD indexes are assigned lowest-first, so it's likely the FD index under the now-closed connection will be reassigned by the time the next ping fires. When that happens the ping is written somewhere unintended!

In the [demo Gist](https://gist.github.com/mkscrg/8c1d0cb1a1623348eed90f6d76f8121a) you can see pings written to FDs used by Postgres connections, which breaks those Postgres connections. The demo has some careful client/server timing to hit the issue consistently. In the wild—we found this bug _in situ_ at Wagon yesterday—the errors are more varied and occurrence less consistent.

Maybe `warp` should guard its `RawResponse` sink, such that it prevents writes after a connection is closed. Alternatively, `websockets`'s ping thread could track its own connection state to avoid the issue.

**Comment by snoyberg** [comment]
Perhaps #549 fixes this?

**Comment by mkscrg** [comment]
#549 does fix it—what timing!
