### ISSUE TITLE
Memory exhaustion with tempFileBackend?

### ISSUE THREAD

**Issue by hce** [yesodweb/wai#560]
Hi, I haven't tested this, but by looking at the type signature, it seems that while files are indeed written to temporary files, what is there to stop me from declaring, say 1 GB of data not as a file but as a parameter? That would still be stored in memory in a ByteString. Since parameters are also sent inside the HTTP Body when doing a file transfer, it is not possible to limit the size of the parameters inside the reverse proxy.

Is there any way to limit the amount of memory the non-file parameters can take per request?

**Comment by snoyberg** [comment]
No, and that's a good point. Interested in sending a PR to add a variant of `tempFileBackend` that allows the caller to provide an arbitrary byte limit to the size of each parameter, and/or the total bytes used by all parameters?

**Comment by hce** [comment]
Yup! Lemme give it a try.

**Comment by hce** [comment]
Looking at the code, it seems that the backend cannot control the number of files and doesn't even have access to the non-file parameters. I considered two options:

a) Add to the backend interface a way to intercept any parameter/file and give it a chance to reject it;
b) Add another variant of parseRequestBody that directly accepts more config options.

IMHO option b) is easier and also more efficient, because it will not be used at all for the normal parseRequestBody call.

The options I plan to add are:
 * Maximum key length (file/parameter name) (default: Just 32)
 * Maximum number of files (default: Just 10)
 * Maximum filesize per file (default: Nothing)
 * Maximum total filesize (default: Nothing)
 * Maximum number of parameters (default: Just 32)
 * Maximum size per parameter (default: Just 8192)
 * Maximum total parameter value size (default: Just 65536)

Sounds ok?

**Comment by snoyberg** [comment]
Yes, sounds good.

**Comment by snoyberg** [comment]
Fixed by your PR, thanks!
