### ISSUE TITLE
feature request: HTTP2 CONNECT method support

### ISSUE THREAD

**Issue by bjin** [yesodweb/wai#561]
HTTP2 spec defines `CONNECT method` in [section 8.3](https://http2.github.io/http2-spec/#CONNECT), and it's most commonly used as tunnel for HTTPS traffic over a proxy server.

A `WAI` application with CONNECT method requires connection takeover and could be implemented with `ResponseRaw`. Unfortunately `ResponseRaw` is not supported in current HTTP2 implementation of `Warp`. In order to run such WAI application, the implementation of HTTP2 `ResponseRaw` is necessary in Warp. I understand that it might be difficult to be implemented in a straightforward way due to HTTP's multiplexing nature. But if it's only about sending/receiving `DATA` frame in single stream, could we make a special case and and leave a dedicated thread for `ResponseRaw` streaming?

**Comment by kazu-yamamoto** [comment]
I think you are right. Could you contribute the code?

**Comment by bjin** [comment]
While the idea seems to be very simple, I think it's not trivial to actually be implemented. And I haven't started reading warp's HTTP2 code. That's why I opened a FR thread first. I do want to have it implemented, and if it's necessary, contribute some code. But it gonna take a much longer time as I imagine.

**Comment by kazu-yamamoto** [comment]
OK. I will try when I find time. 
Could you show me a WAI application which handles CONNECT in HTTP/1.1?
I should start this work by let the application work in HTTP/2.

**Comment by bjin** [comment]
@kazu-yamamoto Thanks! [Here](https://gist.github.com/bjin/4ff5ba18754fcd99cb6681c16b631303) is a simple application. Note that some of the code is taken from `http-reverse-proxy` package.

You can test the proxy server by accessing any HTTPS website with `curl`

```
$ https_proxy=http://localhost:8080 curl -v https://github.com
```

**Comment by bjin** [comment]
Some additional notes: Accoding to HTTP2 specs, `CONNECT` method will have the `host:port` pair in `:authority` header. Both `:scheme` and `:path` will be omitted. You probably need to change the application a bit to make it work.

**Comment by kazu-yamamoto** [comment]
In HTTP/1.1, the proxy app can just write "HTTP/1.1 200 OK". However, it should be encoded with a Headers frame in HTTP/2. What Warp can do is just receive and send Data frames. Warp cannot intercept the status line because it's application specific. So far, I cannot find a good way to encode the status line to a Headers frame.

**Comment by bjin** [comment]
IIUC, this is due to the API design flaw in `ResponseRaw`, right? Would it be possible to add an option to `warp` and encode status line and headers before first occurrence of `\n\n` for ResponseRaw?

**Comment by kazu-yamamoto** [comment]
Cc: @snoyberg

**Comment by kazu-yamamoto** [comment]
I think that `ResponseRaw` does not assume specific applications. Application may or may not send back a status to the browser. This makes things difficult in HTTP/2.

**Comment by awpr** [comment]
I might be missing something, but can't HTTP/2's CONNECT method be implemented with a normal streaming response?

- Get the address/port from the request.
- Initiate the connection; if this fails, respond 500 or whatever code is appropriate.
- Respond 200 with a streaming response:
  - Forward data from the request body to the connection, and from the connection to the stream output, until either is closed.

As far as I can tell, CONNECT only determines the bytes sent over the stream, and shouldn't need to break out of the normal protocol by using ResponseRaw.

**Comment by bjin** [comment]
> Forward data from the request body to the connection, 

You can't forward further data from request body with `ResponseStream`, I'm afraid.

**Comment by awpr** [comment]
Why not?  The request record has an IO action to read a chunk of the request; just run it repeatedly and write the results to the socket.

**Comment by bjin** [comment]
Not exactly sure, but I think request with indefinite length has to be chunk encoded, which would actually break the tunneled traffic. IIRC, `ResponseRaw` was actually created for websocket, which is very similar to HTTP connect tunneling.

**Comment by awpr** [comment]
There's no such thing as chunked encoding in HTTP/2.  The framing mechanism that sits at the core of the protocol gives the same capabilities.  The second paragraph of the HTTP/2 CONNECT spec seems pretty clear that it's not a connection takeover but rather a normal HTTP/2 stream that happens to be implemented by forwarding data chunks.

**Comment by bjin** [comment]
That's interesting. But I'm afraid the same application works with `HTTP2` will then break with `HTTP 1.0` due to chunked encoding. While there might be workaround to this, there are also existing WAI applications utilizing `ResponseRaw`, which won't work with HTTP2.

**Comment by awpr** [comment]
ResponseRaw (connection takeover) fundamentally cannot be implemented for HTTP/2 -- taking over the connection will break all open streams and cause the receiving end to explode trying to interpret arbitrary data as HTTP/2 frames.  It's by design that existing WAI applications using ResponseRaw will serve their fallbacks under HTTP/2.

It sounds like you're asking to change the meaning of ResponseRaw to mean sending/receiving bytes over the individual stream within normal DATA frames.  But that's already exactly what a normal streaming response does in HTTP/2.

CONNECT in HTTP/1.1 and HTTP/2 are totally different things that serve the same purpose -- in HTTP/1.1 it's a connection takeover because the semantics don't fit into the normal protocol; in HTTP/2 it's a normal stream *within* the protocol.  It sounds like the right approach is to query the protocol of the request, and takeover the connection for HTTP/1.*, or respond with a normal stream for HTTP/2.

**Comment by bjin** [comment]
Okay, sounds fair enough. If the purpose of `ResponseRaw` was just a hack to get connection takeover working with `HTTP1.0`, I don't think more support of it should be added either.

@kazu-yamamoto I think current HTTP2 implementation in `warp` requires `:path` to be non-empty. This would actually reject all `CONNECT` requests. An easy fix to bypasses those checks are possible, but I'm not sure if there are any other side effects. Should I open a PR?

**Comment by bjin** [comment]
@kazu-yamamoto I tried to implement an application with `ResponseStream`. It seems that `HEADERS` frame isn't send immediately to the client with `respond ResponseStream`. Instead, streaming body parameter in `ResponseStream` was called (and blocks everything). Do you know if it's the expected behavior or not?

**Comment by kazu-yamamoto** [comment]
I agree with @awpr. We should use `ResponseStream` for `CONNECT` in HTTP/2.

**Comment by kazu-yamamoto** [comment]
> @kazu-yamamoto I think current HTTP2 implementation in warp requires :path to be non-empty. > This would actually reject all CONNECT requests. An easy fix to bypasses those checks are possible, but I'm not sure if there are any other side effects. Should I open a PR?

You are right. `:path` must be omitted with `CONNECT`. Please give us a pull request.

**Comment by kazu-yamamoto** [comment]
> @kazu-yamamoto I tried to implement an application with ResponseStream. It seems that HEADERS frame isn't send immediately to the client with respond ResponseStream. Instead, streaming body parameter in ResponseStream was called (and blocks everything). Do you know if it's the expected behavior or not?

Warp tries to pack data in the sending buffer as much as possible. If you want to send the Headers frame immediately, I guess your application should call the second function to flush.

**Comment by bjin** [comment]
> You are right. :path must be omitted with CONNECT. Please give us a pull request.

@kazu-yamamoto I opened a PR (#572), please take a look. Thanks!
