### ISSUE TITLE
Limit maximal size of referrer cache in HTTP2 push implementation

### ISSUE THREAD

**Issue by meiersi** [yesodweb/wai#565]
Hi @kazu-yamamoto, 

thanks for the nice article on your HTTP2 Push implementation; and thanks for the implementation itself. I wonder what your and the other warp devs' thoughts are on the DOS attack where an attacker floods your push cache by sending lots of cheap GET requests with different referrer headers to a static resource in the configured push-clearing frame. It seems to me that this would allow the attacker to force you into consuming a large amount of memory.

What about using an LRU cache and an upper-bound on the sizes of the referrer headers stored to guarantee bounded resource consumption by the push middleware? The implementation could work along the way of: https://jaspervdj.be/posts/2015-02-24-lru-cache.html.

best regards,
Simon

**Comment by kazu-yamamoto** [comment]
Hi @meiersi,

Yes, that's my concern. And thank you for telling the idea of an LRU cache and how to implement it.
Could you implement it and give us a pull request? I would love to review and merge it.

**Comment by meiersi** [comment]
@kazu-yamamoto you're welcome. I currently don't have spare resources to implement this. Sorry. If I would happen to need it for company work, I'd be happy to do it. However, we're currently not using HTTP2.

**Comment by kazu-yamamoto** [comment]
Now implementing. Tests are necessary.

**Comment by kazu-yamamoto** [comment]
I have implemented MultiMap with limitations (not based on LRU) and released it.
