### ISSUE TITLE
Rewrite middleware contradicts guidance on rawPathInfo

### ISSUE THREAD

**Issue by dbaynard** [yesodweb/wai#571]
Hello,

I’ve been using [Network.Wai.Middleware.Rewrite](https://github.com/yesodweb/wai/blob/master/wai-extra/Network/Wai/Middleware/Rewrite.hs) to convert a URL based on compulsory query parameters to one based on paths, in order to place a site I’m upgrading behind a reverse proxy. It’s a bit of a workaround, but the pattern may be useful more generally.

I’d like to add helper functions and some more examples to this module, but I noticed the two functions explicitly update [`rawPathInfo`](https://github.com/yesodweb/wai/blob/master/wai/Network/Wai/Internal.hs#L35) despite that function’s documentation advising against it.

So before I submit the PR, should my functions modify `rawPathInfo` and `rawQueryString` (as the functions in Network.Wai.Middleware.Rewrite), or not (as the documentation for the raw accessors states)?

---

Brief summary of the PR (to follow pending guidance): 
-   Factors out modification of request from generation of middleware (for use with `WPRModifiedRequest` of the `http-reverse-proxy` library)
-   Extend this to use query parameters in addition to path segments
-   Expose new functions to modify requests based on query parameters

This would add extra exports, but not break current exports from the module.

**Comment by snoyberg** [comment]
Pinging @gregwebs, who I believe initially wrote the Rewrite middleware (https://github.com/yesodweb/wai/commit/acb96bdf922109512825d487da573a6ff67f1abb).

**Comment by dbaynard** [comment]
No response, so I did some digging.

[The 5th comment](https://github.com/yesodweb/wai/issues/325) suggests the current behaviour (modifying `rawPathInfo`) is wrong. In which case, would the change break semantics (in a way discussed in #325 )?

**Comment by snoyberg** [comment]
It would break semantics, but providing an alternatively named function would certainly be OK. I'd still like to hear from @gregwebs though before we merge anything in case there's a specific reason for the middleware to behave as it does now.

**Comment by gregwebs** [comment]
Change it :)

**Comment by dbaynard** [comment]
Ok! I'll link a PR when I get a chance, shortly. I have an example rewriting query parameters to path pieces and back, so I'll add that as documentation, too.

**Comment by dbaynard** [comment]
I’ve added a PR, but it uses `Data.Functor.Identity`, which breaks the build on `ghc < 7.10` as cabal restrictions conflict. The issue is, I think, with `transformers`, but I’m not so sure. 

I’d be grateful for guidance on how to handle this situation.

**Comment by dbaynard** [comment]
I’ve added a PR, but it uses `Data.Functor.Identity`, which breaks the build on `ghc < 7.10` as cabal restrictions conflict. The issue is, I think, with `transformers`, but I’m not so sure. 

I’d be grateful for guidance on how to handle this situation.

Edit: Forgot about the [AMP](https://ghc.haskell.org/trac/ghc/wiki/Migration/7.10)
