### ISSUE TITLE
Wai-App-Statc.

### ISSUE THREAD

**Issue by tolysz** [yesodweb/wai#577]
https://github.com/pcapriotti/optparse-applicative/commit/e4acc2df5d9d1685bcbf37d091b76d93deab1b6d

Breaks [keter-travis] (https://travis-ci.org/snoyberg/keter/jobs/152831587)
```
WaiAppStatic/CmdLine.hs:50:12:
    Not in scope: ‘<>’
    Perhaps you meant one of these:
      ‘<$>’ (imported from Options.Applicative),
      ‘*>’ (imported from Options.Applicative),
      ‘<$’ (imported from Options.Applicative)
...
```

Stuff on hackage needs to have `optparse-applicative < 0.13`

Going forward we need to `import Data.Monoid ((<>))`.

**Comment by snoyberg** [comment]
I just merged a PR to add this, I'll be releasing later today.

**Comment by tolysz** [comment]
I see the change, so the only things left are to edit `hackage` (easy); and cut new version (low prio).

**Comment by tolysz** [comment]
Thanks :)
