### ISSUE TITLE
warp: ambiguous modules in doctest

### ISSUE THREAD

**Issue by bergmark** [yesodweb/wai#579]
The test suite is 

The test-suite for this package has been disabled in stackage because of this issue. If a fix is published to hackage can you please ping me? You may not want to fix this since it's an issue with the combination of these packages, so feel free to close this if so.

Thanks!

```
Network/Wai/Handler/Warp/WithApplication.hs:12:1: error:
    Ambiguous interface for ‘Control.Concurrent.Async’:
      it was found in multiple packages: async-dejafu-0.1.2.2 async-2.1.0
```

**Comment by kazu-yamamoto** [comment]
@snoyberg Do you think that we should fix it in Warp?
I think that async-dejafu should rename its module.

**Comment by snoyberg** [comment]
I'd like that too. However, new idea...

@bergmark What do you think about adding a new setting to Stackage which marks packages as hidden, and tells stackage-curator to hide these packages after registering them, to avoid problems like this? I can imagine that metadata will also be useful for Stack down the road.

**Comment by bergmark** [comment]
@snoyberg good idea! I think that will work out very nicely.

**Comment by snoyberg** [comment]
OK, I've made the relevant modification to both stackage-curator and build-constraints.yaml, so hopefully the tests will pass in the future. Should we close this and address any remaining issues among just the curator team?

**Comment by bergmark** [comment]
Awesome, thanks! It Sounds good to me!
