### ISSUE TITLE
ld (webkit.o): undefined reference to symbol

### ISSUE THREAD

**Issue by leohaskell** [yesodweb/wai#587]
`stack build` (LTS-7.6) on `yesod-minimal` gives the following message:
```
Linking .stack-work/...
/usr/bin/ld: .../libHSwai-handler-webkit-3.0.0.3...a(webkit.o): undefined reference to symbol '__gxx_personality_v0@@CXXABI_1.3'
/usr/lib/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
`gcc' failed in phase `Linker'. (Exit code: 1)
```

I've changed only `Main.hs` and now it looks like this:
```
main :: IO ()
main = run "Webkit Application" app 

app :: Application
app _ respond = bracket_
    (putStrLn "Allocating scarce resource")
    (putStrLn "Cleaning up")
    (respond $ responseLBS status200 [] "Hello World")
```

**Comment by snoyberg** [comment]
You must have also changed the imports and the .cabal file, right? What about the stack.yaml file? wai-handler-webkit isn't in any Stackage snapshots.

**Comment by leohaskell** [comment]
Yes, I changed the imports and I added `wai-handler-webkit-3.0.0.3` as extra-dep to stack.yaml.

**Comment by snoyberg** [comment]
Can you provide your full stack.yaml so it's clear what GHC
version/snapshot you're using? Also, if you can minimize the test case (for
example, come up with an example that demonstrates this problem with just a
WAI application), that would be helpful. Finally, what OS are you on?

**Comment by leohaskell** [comment]
I'm on Arch 4.8.4. Here is the stack.yaml:
```yaml
flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- wai-handler-webkit-3.0.0.3
resolver: lts-7.6
```
And this is the minimal Main.hs:
```haskell
import Network.Wai.Handler.Webkit (run)

main :: IO ()
main = run undefined undefined
```

**Comment by snoyberg** [comment]
I don't have ready access to a Linux machine with the necessary libraries.
Can you try adding this to your .cabal file?

pkgconfig-depends: QtWebKit

**Comment by leohaskell** [comment]
`stack clean` && `stack build` after the change still produces the same output.

**Comment by kazu-yamamoto** [comment]
This is very old, so I would close this. 
Please reopen if necessary.
