### ISSUE TITLE
Multiple Accept headers not combined

### ISSUE THREAD

**Issue by simon-nicholls** [yesodweb/wai#588]
I have some intransigent HTTP client software sending multiple `Accept` headers, instead of a combined `Accept` header:

```
(\"Accept\",\"text/*\"),(\"Accept\",\"application/xhtml+xml\"),(\"Accept\",\"application/atom+xml\"),(\"Accept\",\"application/json\"),(\"Accept\",\"application/xml\"),(\"Accept\",\"application/llsd+xml\"),(\"Accept\",\"application/x-javascript\"),(\"Accept\",\"application/javascript\"),(\"Accept\",\"application/x-www-form-urlencoded\"),(\"Accept\",\"application/rss+xml\")
```

According to `logStdoutDev`, my (Servant) app is handed the first listed `Accept: text/*` and the rest are dropped, whilst my routing responds to JSON, leading to a `406 Not Acceptable`.

But I gather from the following, that multiple field headers are fine for cases where the values can be comma separated:

> A sender MUST NOT generate multiple header fields with the same field name in a message unless either the entire field value for that header field is defined as a comma-separated list [i.e., #(values)] or the header field is a well-known exception (as noted below).

https://greenbytes.de/tech/webdav/rfc7230.html#rfc.section.3.2.2.p.2

**Comment by snoyberg** [comment]
Please provide a reproduction against Warp. However, I'm pretty sure you
want to file this issue with servant.

**Comment by simon-nicholls** [comment]
Hmmm. Though `Servant` and `Spock` both appear to assume there is only a single `Accept` header (perhaps header per name generally) in the `requestHeaders`, it's not strictly a bug at WAI / Warp level unless there are guarantees by WAI about combining headers.

It's more of a feature add, for the convenience of various WAI based web app frameworks. I'll have a look at what exactly Servant is doing, as the content type negotiation there is what I need to have working. In the meantime, at least it's super easy to implement header combining in middleware!

**Comment by Vlix** [comment]
Sounds like something `Middleware` could easily fix? 🤔

**Comment by Vlix** [comment]
I believe the new middleware from #901 resolves this issue so I'm going to close this.
