### ISSUE TITLE
wai-frontend-monadcgi does not drop '?' in query string

### ISSUE THREAD

**Issue by krsch** [yesodweb/wai#590]
When running this simple program:
```haskell
import Network.Wai.Frontend.MonadCGI
import Network.Wai.Handler.Warp
import Network.CGI

main :: IO ()
main =
    run 8811 $ cgiToApp $ handleErrors $ do
        liftIO . print =<< getInputNames
        outputNothing
```
on `curl 'http://localhost:8811/?uid=a&password=123'` the program prints `["?uid","password"]`, while I expected `["uid","password"]`

**Comment by snoyberg** [comment]
Thanks for the report, I've released a new version of Hackage (3.0.0.3) which should resolve the issue.
