### ISSUE TITLE
Thread Killed by Warp's timeout reaper (min. repro. incl.)

### ISSUE THREAD

**Issue by jasonzoladz** [yesodweb/wai#607]
Confirmed on both `Ubuntu 16.04` and `OSX (10.12.2)`.

`resolver: lts-7.18`

Error Message:
(note: the first line of the error is from the `setOnException` call: 

```bash
threadWait: invalid argument (Bad file descriptor)
HS-exe: Thread killed by Warp's timeout reaper
```

Code:

```haskell
{-# LANGUAGE OverloadedStrings, NoImplicitPrelude #-}


module Application where

import           BasicPrelude
import           Network.HTTP.Types.Status
import           Network.Wai
import           Network.Wai.Handler.Warp


app :: Request -> (Response -> IO ResponseReceived) -> IO ResponseReceived
app req respond = respond $ responseLBS status200 [] "Hello Thread Killed by Warp's timeout reaper."

run :: IO ()
run = runSettings settings app
  where
    settings = setTimeout 1 $ setPort 4444 $ setOnException (\r e -> print e) defaultSettings
```

With the given timeout, the error is thrown approximately 1 second after a request is made.  (You can increase it to, say, 20 seconds, and the only result is that you wait longer to see the error after a request is made.  Obviously, if you don't include an explicit timeout, the exception is thrown when the default timeout (_i.e._, 30 seconds) expires following a request.

**Comment by snoyberg** [comment]
Can you clarify which part of this is unexpected? It's unclear from this report what the expected vs actual behavior is.

**Comment by jasonzoladz** [comment]
My expectation -- based only on working with warp previously -- was that I wouldn't see such an error message.  But I gather from your response that this is just normal timeout handling at work.

I've spent a fair amount of time with warp, and I've never seen the message before now.  Though its possible/likely that a library on top (e.g., spock or yesod) was just swallowing the message.
