### ISSUE TITLE
[Question] When is streaming response flushed?

### ISSUE THREAD

**Issue by mitchellwrosen** [yesodweb/wai#608]
The docs state that the `flush` arg to `StreamingBody` is  "provides a means of flushing the data to the client", but it isn't clear to me exactly what this means.

Is it a "default flush behavior override", or is it the only means that data is ever flushed?

If the former, what's the default behavior of when data is flushed?

Thanks!

**Comment by snoyberg** [comment]
It's flushed whenever the buffer is full, unless flushed first. But that's
an implementation detail, an implementation may choose to always flush or
hold everything in memory.

Obviously at the end of the response it also flushes.

**Comment by mitchellwrosen** [comment]
Oh, yes, I suppose the question was referring to `warp` specifically. And one follow up question, is the buffer size configurable? I don't see an option for it in `Settings`.

**Comment by snoyberg** [comment]
I don't believe it can be configured right now, no.

**Comment by mitchellwrosen** [comment]
Thanks, I poked around (for posterity) and I believe this is the current window size (65kb): https://hackage.haskell.org/package/http2-1.6.3/docs/Network-HTTP2.html#v:defaultSettings

Closing!
