### ISSUE TITLE
Regression in warp 3.2.10: Timeout reaper is triggered if socket is kept open

### ISSUE THREAD

**Issue by cocreature** [yesodweb/wai#613]
When building the program below against warp *3.2.9*, everything works as expected. However, using *3.2.10* or *3.2.11*  `Thread killed by Warp's timeout reaper` is printed to stderr when I open [http://localhost:8080](http://localhost:8080) in a browser (I tried firefox and chrome). This error does not occur using curl (even when copying the curl command provided by the browser) and it also doesn’t appear if I click fast enough on `Close idle sockets` on `chrome://net-internals/#sockets`. This strongly suggests that the problem is caused by browsers keeping sockets open for potential reuse. I don’t have the time right atm to bisect and find the exact commit that triggered this bug.

```
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Network.HTTP.Types.Status
import Network.Wai
import qualified Network.Wai.Handler.Warp as Warp

main :: IO ()
main = do
  Warp.runSettings (Warp.setTimeout 1 $ Warp.setPort 8080 Warp.defaultSettings) $ \req respond ->
    respond $ responseLBS status200 [] "Hello World"
```

**Comment by cocreature** [comment]
I just figured out that this happens *only* using the threaded runtime. To make it easier to reproduce I also created a full cabal repo that builds with cabal and stack and demonstrates the bug https://github.com/cocreature/warp-bug

**Comment by cocreature** [comment]
A bisect points to 3eb586636b7f0a9a8e4b4ad456c16efe23847c9e

**Comment by snoyberg** [comment]
Good catch, and thanks for the clear repro steps. I think this is fixed with 35ef1ca27ec50025198dfe6c7f5eabac95d3498f, can you give it a shot?

**Comment by cocreature** [comment]
I can confirm that this fixes the bug for me. However, I noticed that merging #611 also made the bug disappear even without your commit. But maybe it’s just harder to trigger now, I haven’t looked at the actual changes.

It would be great if you could do a bugfix release.

**Comment by snoyberg** [comment]
Yeah, I was curious if #611 would affect this... I've just merged master back into this branch, can you try that as well? Since these are the only changes since the last release, I feel comfortable making the release myself without waiting for @kazu-yamamoto (though Kazu's review is always appreciated).

**Comment by cocreature** [comment]
> I've just merged master back into this branch, can you try that as well?

It still works :)

**Comment by snoyberg** [comment]
Cool, I'll merge/release that PR once Travis goes green.

**Comment by kazu-yamamoto** [comment]
I think that 35ef1ca is a direct solution for 3eb5866.
So, it's OK to merge 35ef1ca.

Now I'm trying to understand the relationship with #611.

**Comment by kazu-yamamoto** [comment]
#611 looks good. It seems to me that including both patches are OK.

**Comment by kazu-yamamoto** [comment]
Now `fork` is complicated and hard to read. I just pushed the refactoring code: c01f8e38b1a16175ed30324890aad26d90bdf054

@snoyberg Please review it.

@cocreature Please test the `613-better-exception-handling` branch.

**Comment by cocreature** [comment]
@kazu-yamamoto I can confirm that it still works.

**Comment by snoyberg** [comment]
Reviewed changes (look great), merged, and released to Hackage. Thanks!

**Comment by cocreature** [comment]
Thans for fixing this so fast!
