### ISSUE TITLE
[warp] Support using separate sockets for HTTP and HTTPS connections?

### ISSUE THREAD

**Issue by iand675** [yesodweb/wai#614]
I guess it's most common for warp(-tls) servers to be run behind NGINX or something similar, but it would be nice to be able to bind separate ports for HTTP vs HTTPS connections.

In particular, traditional public-facing web servers serve HTTP at 80 and HTTPS at 443, and I don't think that's doable currently. Please correct me if I'm wrong.

**Comment by kazu-yamamoto** [comment]
You can run Warp and WarpTLS with `concurrently`.
Mighttpd2 does this:

https://github.com/kazu-yamamoto/mighttpd2/blob/master/src/Server.hs#L166

**Comment by kazu-yamamoto** [comment]
@iand675 Can we close this issue?

**Comment by iand675** [comment]
Yes, closing it is fine. But I think it might be good to mention this strategy in the warp documentation.
