### ISSUE TITLE
New feature request for setting multiple hosts to run warp on

### ISSUE THREAD

**Issue by brent80** [yesodweb/wai#626]
@snoyberg 
I was curious if we could ever get a function like
setHosts  instead of setHost  that takes multiple hosts
example
host: "127.0.0.1", "192.168.1.1", "111.111.111.111"

So you could set the exact NIC's your warp server runs on.
I would like this feature so I could run warp servers on both
local host and a private network, but not a public network.

Feel free to close this if this can't be done or is a bad request.

**Comment by kazu-yamamoto** [comment]
Warp uses the `bind` syscall which takes only one address.
It is difficult to change this architecture.
If you want to bind multiple addresses, just run multiple instances of Warp with `forkIO`.
