### ISSUE TITLE
Gzip middleware does not set Vary: Accept-Encoding

### ISSUE THREAD

**Issue by mithrandi** [yesodweb/wai#627]
I think this should be set for all responses passing through the middleware, because they might be gzipped if the client supplies `Accept-Encoding: gzip`.

**Comment by snoyberg** [comment]
Seems reasonable. Want to send a PR?

On Wed, Jun 14, 2017 at 2:02 PM, Tristan Seligmann <notifications@github.com

**Comment by snoyberg** [comment]
Implemented elsewhere, closing
