### ISSUE TITLE
[autohead] HTTP invalid status line '0'

### ISSUE THREAD

**Issue by creichert** [yesodweb/wai#634]
> HTTP invalid status line '0'

@snoyberg I believe you've already fixed this in: https://github.com/yesodweb/wai/issues/346, https://github.com/yesodweb/wai/commit/f1f658ba6aacb77aeec33b122a8ed3f13700a8f0

- autohead code: https://github.com/yesodweb/wai/blob/master/wai-extra/Network/Wai/Middleware/Autohead.hs#L14

I think the `autohead` middleware may have the same problem but I haven't had luck getting an isolated repro.

---

I'm receiving this bug on two separate hosts (assertible.com, simplyrets.com). It only happens on `HEAD` requests and I'm using the `autohead` middleware.

Basically, I have some automated API/website tests running. This particular bug happens during a `HEAD `request which is testing links in rapid succession.

So, on assertible I have:
```
$ stack list-dependencies | grep '\(warp\|wai\|http-client\)'
http-client 0.5.5
http-client-tls 0.3.3.1
wai 3.2.1.1
wai-extra 3.0.19.1
wai-logger 2.3.0
wai-middleware-static 0.8.1
wai-session 0.3.2
wai-session-postgresql 0.2.1.0
warp 3.2.10
```

On simplyrets I have:
```
$ stack list-dependencies | grep '\(warp\|wai\|http-client\)'
http-client 0.4.31
http-client-tls 0.2.4.1
wai 3.2.1.1
wai-app-static 3.1.6.1
wai-extra 3.0.16.1
wai-logger 2.3.0
wai-middleware-static 0.8.0
wai-session 0.3.2
wai-session-postgresql 0.2.1.0
warp 3.2.8
```

---

##### reports
- **PR FIX** https://github.com/yesodweb/wai/issues/346
- https://github.com/snoyberg/http-client/issues/108
- https://github.com/snoyberg/keter/issues/75
- https://github.com/yesodweb/wai/issues/249

---

#### repro

I've tried reproducing this but not having any luck

```
#!/usr/bin/env stack
-- stack -v runghc --package connection --package http-client --package http-client-tls
{-# LANGUAGE OverloadedStrings #-}

import Prelude

import Control.Concurrent.Async
import Network.HTTP.Client.TLS
import Network.HTTP.Client

main :: IO ()
main = do
    let (Just req) = parseUrlThrow "https://assertible.com/login"
    man <- newManager tlsManagerSettings

    results <- forConcurrently [1..50] $ \_ -> do
        res <- httpLbs req{method="HEAD"} man
        pure (responseStatus res)

    mapM_ print results
```

**Comment by creichert** [comment]
Here's my result in assertible (not shareable yet):

![](https://user-images.githubusercontent.com/526560/28540502-3b5c8806-707b-11e7-80df-fc820d59edc6.png)

**Comment by snoyberg** [comment]
FWIW I tried the following and saw nothing unusual in the output. Perhaps it's an interaction with some other request header, like GZIP?

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-8.12 script
{-# LANGUAGE OverloadedStrings #-}
import Conduit
import Control.Monad
import Data.Conduit.Network
import Data.Conduit.Network.TLS
import Control.Concurrent.Async

main :: IO ()
main = runTLSClient (tlsClientConfig 443 "assertible.com") $ \ad -> concurrently_
  (replicateM_ 5
      $ runConduit
      $ yield "HEAD /login HTTP/1.1\r\nHost: assertible.com\r\n\r\n"
     .| appSink ad)
  (appSource ad $$ stdoutC)
```

**Comment by creichert** [comment]
Thanks for looking into this. It's definitely not a deterministic issue. It's frustrating but I am certain it's only happening on `HEAD` requests.

I'm going to close this issue for now until I have more details or a repro.

**Comment by creichert** [comment]
FTR, here's how often we are seeing it (and every request is a HEAD request):

![](https://user-images.githubusercontent.com/526560/28688721-755a1ee2-72d8-11e7-99a5-c75c9b1250f7.png)

---

I actually removed the `gzip` middleware from the app recently because it was being gzipped by our nginx proxy.

**middlewares we are using:**
- request logging middleware
- autohead
- wai-session (middleware)
- wai-middleware-static

![](https://user-images.githubusercontent.com/526560/28689042-c28ef7e0-72d9-11e7-8857-9e5610d7ce57.png)

One other thing I can think of is the order of the middlewares. I wonder if it's possible there is a bad interaction between the autohead middleware and another.

Any tips for what order middlewares _should_ be in?
