### ISSUE TITLE
travis ci

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#637]
@snoyberg Do you understand why this fails?
Only this job fails at this moment.
"Restarting job" always results in the same.

https://travis-ci.org/yesodweb/wai/jobs/258386862

**Comment by snoyberg** [comment]
It's an out of memory condition for building the Cabal library. I've pushed a commit to force Cabal to be built on its own instead of in parallel with other packages.

**Comment by kazu-yamamoto** [comment]
Great! Thanks.
