### ISSUE TITLE
Warp ignores status code in ResponseFile

### ISSUE THREAD

**Issue by penteract** [yesodweb/wai#644]
When an application passes a responseFile to the continuation, the Warp server ignores the status code sent with it (sending 200 along with the data if the file is present in the filesystem) and does not appear to provide a setting for changing this behaviour. This is a problem when trying to write a custom 404 response using a file.

Minimal example:
```
module Main where

import Network.Wai
import Network.Wai.Handler.Warp
import Network.HTTP.Types

main :: IO ()
main = run 8080 (\req resp ->resp $ responseFile status404 [] "404.html" Nothing)
```

**Comment by snoyberg** [comment]
I've pushed a commit to a separate branch 661257ff6eaad454b83572604013f4998d5478a5 on 644-incorrect-file-status-code) that adds a test demonstrating the problem. I'll try poking at the code a bit more, but I'm not that familiar with the codepaths going on here. @kazu-yamamoto when you're back in action, would you mind having a look at this?

**Comment by kazu-yamamoto** [comment]
This is intentional. Doc from https://hackage.haskell.org/package/warp-3.2.13/docs/Network-Wai-Handler-Warp-Internal.html#v:sendResponse

> Applications are categorized into simple and sophisticated. Sophisticated applications should specify Just to Maybe FilePart. They should treat the conditional request by themselves. A proper Status (200 or 206) must be provided.
>
> Simple applications should specify Nothing to Maybe FilePart. The size of the specified file is obtained by disk access or from the file infor cache. If-Modified-Since, If-Unmodified-Since, If-Range and Range are processed. Since a proper status is chosen, Status is ignored. Last-Modified is inserted.

You should specify `Just` to `responseFile` to use your status code.

**Comment by penteract** [comment]
Thanks
