### ISSUE TITLE
wai-handler-launch needs updating on hackage/stackage

### ISSUE THREAD

**Issue by simonmichael** [yesodweb/wai#646]
wai-handler-launch is not in recent stackage, keeping eg hledger-web out as well. Perhaps a hackage release including https://github.com/yesodweb/wai/pull/645 will resolve it.

**Comment by snoyberg** [comment]
Thanks for the ping, new version released.

**Comment by simonmichael** [comment]
Thanks Michael.

**Comment by snoyberg** [comment]
No problem. BTW, I forgot to ask earlier: you interested in being added as a maintainer here on Github and on Hackage?

**Comment by simonmichael** [comment]
Thanks, but I must decline for now.

**Comment by snoyberg** [comment]
No problem

**Comment by simonmichael** [comment]
wai-handler-launch [seems](https://www.stackage.org/package/wai-handler-launch) to have dropped out of stackage around 7/25, I haven't figured out why. 

I want to re-enable hledger-web, which requires it, and I'm not sure if the stackage builder will automatically pull it from hackage.

Should wai-handler-launch be added to build-constraints.yaml ?

**Comment by snoyberg** [comment]
It's not necessary to add it in, dependencies are automatically pulled in.
If you'd like to add it manually to build-constraints.yaml, you can, but
just added hledger-web will do the same thing.

**Comment by simonmichael** [comment]
I see, thanks for the help!
