### ISSUE TITLE
Payload Too Large in WAI is 500 instead of 413

### ISSUE THREAD

**Issue by michalrus** [yesodweb/wai#647]
Would it be possible here:

https://github.com/yesodweb/wai/blob/a1cb17ff79887e0c33be7fb975b5a0f559e2cf45/wai-extra/Network/Wai/Parse.hs#L634

… to throw something that’d turn into a standard `413 Payload Too Large` response instead of a scary `500 Internal Server Error` with `Maximum size exceeded` logged only to app’s stdout/err (by default)?

This causes https://github.com/haskell-servant/servant-multipart/issues/9 also. :slightly_smiling_face: 

Thank you!

**Comment by snoyberg** [comment]
I don't see a problem with such a change, what do you think @kazu-yamamoto?

@michalrus You interested in sending a PR?

**Comment by kazu-yamamoto** [comment]
I think that we should change this to 413.

**Comment by michalrus** [comment]
Great to hear that you both agree! I’ll take a look at how similar cases are handled over the weekend. If anyone wants to do it earlier, please, do. =)

Thank you!

**Comment by vlatkoB** [comment]
Quite a complex and low-level library.
Where does the `error` get turned into HTTP error code? Tried:
```haskell
- Just max'' | cur > max'' -> E.throwIO $ HTTP2.ConnectionError HTTP2.FrameSizeError "Payload Too Large"
- Just max'' | cur > max'' -> E.throwIO $ HTTP2.ConnectionError (HTTP2.UnknownErrorCode 418) "Payload Too Large"
```
But it doesn't get turned into proper status. The only `catch` on `ConnectionError` I found is in `frameReceiver` (`sendGoaway`) in `Network/Wai/Handler/Warp/HTTP2/Receiver.hs`, but seems that one is not the right one.
 A little help, please.

**Comment by alpmestan** [comment]
I think it's `warp`'s default exception handler that just turns any exception that's not caught by that point into a 500 response: https://github.com/yesodweb/wai/blob/b29e2705d0b4035a17227a8669c6430eb7c9d067/warp/Network/Wai/Handler/Warp/Settings.hs#L174

**Comment by vlatkoB** [comment]
@alpmestan Thanks for the pointer. :-)
I added 413 (Payload too large) and 431 (Headers too large)

Interestingly, Linux and MacOS tests pass, but Windows fails in 1 test.

**Comment by kazu-yamamoto** [comment]
#741 has been merged.
