### ISSUE TITLE
TLS Handshake error with self-signed certificate

### ISSUE THREAD

**Issue by Superpat** [yesodweb/wai#650]
I'm using runTLS with default settings and a certificate generated through the instructions on hackage, but I get a handshake failure every time I make a request to my api from my client.

`HandshakeFailed (Error_Misc "user error (unexpected type received. expecting handshake and got: Alert [(AlertLevel_Fatal,UnknownCa)])")`

```haskell
startApp :: [Text] -> IO ()
startApp args = do
    port  <- lookupEnvDefault "SERVANT_PORT" 8080
    env   <- lookupEnvDefault "SERVANT_ENV" Production
    logTo <- case listToMaybe args of
        Just filename -> return $ File filename
        Nothing       -> lookupEnvDefault "SERVANT_LOG" STDOut
    pool    <- Pool.createPool openConnection PGS.close 1 10 5
    logger  <- makeLogger logTo
    midware <- makeMiddleware logger env
    let settings = setPort port defaultSettings
    FL.pushLogStrLn logger
        $  FL.toLogStr
        $  "Listening on port "
        ++ tshow port
        ++ " at level "
        ++ tshow env
        ++ " and logging to "
        ++ tshow logTo
        ++ " with args "
        ++ unwords args
    configuredApp <- app (Config pool logger)
    Warp.runTLS Warp.defaultTlsSettings settings $ midware $ myCors $ configuredApp
```

I generated my certificate with:
```bash
openssl genrsa -out key.pem 2048
openssl req -new -key key.pem -out certificate.csr
openssl x509 -req -in certificate.csr -signkey key.pem -out certificate.pem
```

The client is an elm app created with create-elm-app and running on the webpack-dev-servers with https enabled.

**Comment by paul-rouse** [comment]
Is your client configured to accept a self-signed certificate?  It looks to me as if the client is the side which is complaining.

**Comment by Superpat** [comment]
Yeah I just figured that out this morning. I can accept the cert in my browser and a direct call to my api will work, as will a call with curl. So it's definitly on the elm  / webpack side.

Thanks anyways!
