### ISSUE TITLE
Possible to expose some of the internal types from HTTP2 implementation?

### ISSUE THREAD

**Issue by ghost** [yesodweb/wai#655]
Hi,

First, thank you for all your work on the Warp and Wai software. I recently read the paper here:
http://www.mew.org/~kazu/doc/paper/http2-haskell-2016.pdf and you guys have put a lot of work in to writing a performant server.

**The point:**
I want to use some of the code and types from the HTTP2 code handling in the Warp server here, but it isn't currently exposed:

https://github.com/yesodweb/wai/tree/master/warp/Network/Wai/Handler/Warp/HTTP2

Is there any chance you could expose some of those types in the public API?

**Background:**
I am working on a stream multiplexing library compatible with the libp2p project (https://github.com/libp2p). Something like http-conduit but with HTTP2 muxing support.

Without going into too much detail, the main idea is to provide a simple API to open new multiplexed byte streams on a connection, using various multiplexing protocols such as SPDY, HTTP2 and others. 
The connection could be established using various protocols: TCP, WebSockets, etc.

I would like to use the io-streams and the Warp library to provide a function something like:
`newStream :: Connection -> Context -> IO (InputStream ByteString, OutputStream ByteString)`

However, I'm not sure if the Application type in Warp is a good fit to represent that kind of thing. It has type 
`type Application = Request -> (Response -> IO ResponseReceived) -> IO ResponseReceived` that doesn't fit with the streaming API.

I would like to use some of the more low level code from your HTTP2 implementation in Warp to implement the streaming API, to get all the performance benefits of your work, but without having to use the Application type from Warp. Something like using the http2 equivalent of the http-conduit library. 

I can't do that without copying code though, unless those types and functions available in the public API or in a seperate library (similar to http-client or http-conduit). Is it something you would look at?

Thanks Again
Quoc-An

**Comment by kazu-yamamoto** [comment]
I'm very sorry for this really late response.
If you wish, please add what you need to the `Internal` module and give us a pull request.

**Comment by kazu-yamamoto** [comment]
Ping @kneedler

**Comment by CMCDragonkai** [comment]
I'll have a look into this.

**Comment by kazu-yamamoto** [comment]
The next version of `http2` will expose a lot of `Internal` modules. You can check here: https://github.com/kazu-yamamoto/http2
