### ISSUE TITLE
Warp: memory leak with lots of incoming requests

### ISSUE THREAD

**Issue by koterpillar** [yesodweb/wai#664]
A simple Warp application will consume more and more memory if a large amount of requests is sent, and eventually run out of open files.

## Steps to reproduce:

Run this Warp application:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-10.1 script

{-# LANGUAGE OverloadedStrings #-}
module Main where

import Control.Concurrent

import Network.HTTP.Types

import Network.Wai
import Network.Wai.Handler.Warp

main = run 8080 $ \_ respond -> do
  threadDelay 100
  respond $ responseLBS status200 [] "Hello World"
```

Note the memory consumption of the executable (47 MB on my machine).

Overload it with requests (requires [vegeta](https://github.com/tsenart/vegeta/)):

```shell
echo 'GET http://localhost:8080/' | vegeta attack -duration 60s -rate 20000 -output result.vegeta
```

## Expected result:

Regardless of the errors, Warp executable memory consumption remains the same.

## Actual result:

After the run, the memory consumption of the Warp executable increases. On my machine, after one run it was 347 MB, and then after another run the executable terminated with:

```
Network.Socket.accept: resource exhausted (Too many open files)
```

System information:

```
command -v sw_vers && sw_vers # OS X only
command -v uname && uname -a # Kernel version
command -v stack && stack --version
command -v stack && stack ghc -- --version
command -v stack && stack list-dependencies
```

```
/usr/bin/sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.2
BuildVersion:	17C88
/usr/bin/uname
Darwin L3227 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
/usr/local/bin/stack
Version 1.6.3 x86_64 hpack-0.20.0
/usr/local/bin/stack
The Glorious Glasgow Haskell Compilation System, version 8.0.2
/usr/local/bin/stack
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?
```

**Comment by koterpillar** [comment]
I have created a demo repository at https://github.com/koterpillar/warpleak/tree/1d12429cdb0031b09e723101cde05c16d2626ec2.

If I roll back the package versions to:

```
extra-deps:
- warp-3.1.12
- http2-1.3.1
- wai-3.0.5.0
- bytestring-builder-0.10.6.0.0
```

The memory usage is roughly stable at 400 MB even after multiple runs, however, the message `Network.Socket.accept: resource exhausted (Too many open files)` is repeated multiple times per run.

**Comment by kazu-yamamoto** [comment]
Does this occur even with Warp 3.2?
Warp 3.2.9 fixed a space leak. #586

**Comment by koterpillar** [comment]
Yes, this occurs on 3.2.13. Unlike #586, I'm not using streaming at all.

**Comment by kazu-yamamoto** [comment]
This may be relating to #649.

**Comment by kazu-yamamoto** [comment]
Sorry but my winter vacation has just started. I will get back to this issue after 10th Jan.

**Comment by kazu-yamamoto** [comment]
> The memory usage is roughly stable at 400 MB even after multiple runs, however, the message Network.Socket.accept: resource exhausted (Too many open files) is repeated multiple times per run.

I guess your listen queue is too small. It's 128 by default on macOS. What's happens if you do:

```
% sudo sysctl kern.ipc.somaxconn=10000
```

**Comment by koterpillar** [comment]
Please note that my problem isn't the message but the memory leak. I still get the memory leak with increased `somaxconn`.

**Comment by kazu-yamamoto** [comment]
@koterpillar Would you try #667?

**Comment by kazu-yamamoto** [comment]
@koterpillar Would you try Warp v3.2.15?

**Comment by koterpillar** [comment]
I don't see the rapid memory increase with v3.2.15, thanks!
