### ISSUE TITLE
travis CI

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#665]
Recently, building & testing take too much time resulting in failures on travis CI.
Should we remove something?

https://travis-ci.org/yesodweb/wai/builds/327988263?utm_source=github_status&utm_medium=notification

**Comment by snoyberg** [comment]
I've just pushed a commit which should hopefully address this.

**Comment by kazu-yamamoto** [comment]
Very fast but it seems to me that no "cabal test" is running. Is it your intention?

**Comment by snoyberg** [comment]
Yes, I can't figure out a way to make that work. Stack is already running
its test suites.

**Comment by kazu-yamamoto** [comment]
OK. That is dependency checking only. I understand.
