### ISSUE TITLE
The "sanitizes header values" test case

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#668]
I got `http-client` back for Warp testing since it does not rely on crypto stuff.
Unfortunately, the "sanitizes header values" test case fails because the behavior of `http-client` is different from that of `HTTP`. 

@snoyberg Do you know how to fix this?

**Comment by snoyberg** [comment]
I think it's a limitation of http-client, it doesn't support multiline headers.

**Comment by kazu-yamamoto** [comment]
Thanks. I commented out it.
