### ISSUE TITLE
Long-time renaming request: Make clear in the name that requestBody returns just one chunk

### ISSUE THREAD

**Issue by nh2** [yesodweb/wai#669]
My biggest gripe with `wai` is `requestBody :: Request -> IO ByteString`.

> Get the next chunk of the body. Returns `empty` when the body is fully consumed.

Even though the docs say that it gets only the next chunk, not the full request body, this is just too easy to forget.

```haskell
bs <- requestBody req
```

is too easily written, it compiles, it looks correct, it works in most of the cases, but it is wrong: when you get over 16 KiB (16384 Bytes), stuff starts breaking.

It would be nice if over coming major releases we could fade its usage over to `requestBodyChunk` or `requestBodyGetNextChunk` or something like this.

**Comment by MaxGabriel** [comment]
I just saw someone run into this in the #yesod channel on the FP Slack:

> btw, I'm sending a file through ajax to one of my endpoints. Is using `rawRequestBody` and then doing some conduit witchcraft the right path?

> I think I did it (maybe) :smile:

> too soon... it works, but it only writes the first 15kB :confused:
> This is what I'm doing:
```  body <- getRequest
  val <- lift $ NW.requestBody $ reqWaiRequest body
  writeFile directory val
```

> ok I keep answering myself, `requestBody` gets just the next chunk :slightly_smiling_face:

**Comment by kazu-yamamoto** [comment]
@snoyberg This proposal makes sense to me. What do you think?

**Comment by snoyberg** [comment]
I'd like to avoid a breaking change, but I think we can get away with:

* Add a new function like `getRequestBodyChunk = requestBody`
* Deprecate `requestBody`

Backends like Warp will still need to work directly with `requestBody` for constructing the `Request` value, but end user code should be safe.

**Comment by ocramz** [comment]
This is the only place I've seen mentioning the size of a body chunk; perhaps it's worth mentioning this quantity in the Haddock? Is it 16KB in all cases ?
