### ISSUE TITLE
Investigate how warp handles HTTP/2 GOAWAY

### ISSUE THREAD

**Issue by nh2** [yesodweb/wai#673]
Hi @kazu-yamamoto,

yesterday I found a problem in nginx's implementation of the HTTP/2 `GOAWAY` feature. It is very easy to get that feature wrong. I have written up and linked the details on https://trac.nginx.org/nginx/ticket/1250#comment:4.

Would you be able to tell me if warp handles this correctly currently, or if that's not clear yet, how it implements sending `GOAWAY` or where the bit that handles this is in the code?

Thanks!

**Comment by kazu-yamamoto** [comment]
This may be relating to https://github.com/yesodweb/yesod/issues/1479

**Comment by kazu-yamamoto** [comment]
Warp does not make use of `shutdown` at this moment. So, the same thing would happen in many cases including sending `GOAWAY`.

**Comment by nh2** [comment]
@kazu-yamamoto Yes, it's very likely the issue you see in the other bug.

**Comment by kazu-yamamoto** [comment]
I think I will be able to take time to consider this in March.
