### ISSUE TITLE
Space leak on wai or warp.

### ISSUE THREAD

**Issue by huseyinyilmaz** [yesodweb/wai#676]
Here is the original discussion:

https://www.reddit.com/r/haskell/comments/81cbmt/help_for_a_space_leak/

I made this simple wai app:
https://github.com/huseyinyilmaz/spock-memmory-usage-test/blob/master/waitest/library/Example.hs

I have build and run the server with this command:

```
stack build && stack install && waitest
```

Then, I started to the send requests to the server:

```
wrk http://localhost:3000 -d 5m
```

I saw that memory usage is keep going up on the server with each request it handles:

https://cl.ly/1i28272h062M

I am testing this on mac os high sierra 10.13.3.
package build with stackage LTS10.7 dependencies are wai, warp, http-types

Here is the system info gist: https://gist.github.com/huseyinyilmaz/50f99c4f5d44cf2fd61a90840e22b240

I am afraid I don't know what else to tell about this problem. Let me know if I can provide more information.

Thanks.

**Comment by huseyinyilmaz** [comment]
I think I found the problem with the help of /u/tom-md on reddit. 
It was caused by warp version 3.2.13 having a space leak. So it turns out that problem was fixed in version 3.2.17. So, for my personal problem I can just use nightly build to get rid of the problem.

I will keep this issue open because LTS version 10.7 and 10.8 is still using warp 3.2.13. I thought that warp version on those versions should also be updated.

Unfortunately, I don't know who to inform about the issue. So if this is the right place feel free to close the issue whenever is appropriate.

**Comment by kazu-yamamoto** [comment]
@huseyinyilmaz Thank you for your report!
@snoyberg Do you have ideas to fix this issue in the LTS versions?

**Comment by snoyberg** [comment]
I've opened up https://github.com/fpco/lts-haskell/issues/101 to address this.

**Comment by kazu-yamamoto** [comment]
@snoyberg Thank you!
I would close this in favor of fpco/lts-haskell#101.

**Comment by snoyberg** [comment]
Agreed.
