### ISSUE TITLE
New version of streaming-commons breaks warp 3.2.13

### ISSUE THREAD

**Issue by jkarni** [yesodweb/wai#678]
When running a project on GHC 7.8, installing `warp` results in the following error:

```
Configuring library for warp-3.2.13..
Preprocessing library for warp-3.2.13..
Building library for warp-3.2.13..
Network/Wai/Handler/Warp/Response.hs:45:8:
    Could not find module ‘Data.Streaming.Blaze’
    Perhaps you meant
      Data.Streaming.Zlib (from streaming-commons-0.2.0.0)
      Data.Streaming.Text (from streaming-commons-0.2.0.0)
    Use -v to see a list of the files searched for.
cabal: Failed to build warp-3.2.13 (which is required by test:spec from
```

There's a minimal reproduction [here](https://github.com/jkarni/repro/tree/master/warp). 

Later versions of `warp` have higher lower bounds on base, so they don't get picked when using 7.8.4.

**Comment by kazu-yamamoto** [comment]
Unfortunately, we don't support GHC 7.8 anymore according to the rule of three major GHC versions.

**Comment by jkarni** [comment]
Hm, would it be possible to simply edit cabal file to put an upper bound on streaming-commons? It seems like a very quick fix, and it'd be unfortunate to have projects not work anymore because of the lack of such a bound.

**Comment by phadej** [comment]
@kazu-yamamoto Note: the issue is about past (not latest) release of `warp`. 
3.2.13 was the last release supporting GHC-7.8.

As a Hackage Trustee I'll soon make revisions for old `warp` releases. See https://github.com/haskell-infra/hackage-trustees/issues/137

**Comment by kazu-yamamoto** [comment]
So, should we bring this to `streaming-commons`?

**Comment by jkarni** [comment]
Why bring it there? Isn't this just an issue with a missing upper bound in warp?

**Comment by phadej** [comment]
I made revisions, `warp` is again green: https://matrix.hackage.haskell.org/package/warp

**Comment by jkarni** [comment]
Yup, thanks a lot!
