### ISSUE TITLE
Releasing packages for GHC 8.4

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#685]
@snoyberg I think we should release some packages to save GHC 8.4 users from `blaze-builder`.

**Comment by snoyberg** [comment]
They should all be released already.

**Comment by kazu-yamamoto** [comment]
Sorry.
I should have done `git fetch upstream` to get tags before creating this issue.
Thank you for your work!

**Comment by snoyberg** [comment]
No problem, thank you for the review and merge on the changes.
