### ISSUE TITLE
wai-handler-launch needs a release for latest stackage nightly

### ISSUE THREAD

**Issue by simonmichael** [yesodweb/wai#686]
wai-handler-launch-3.0.2.3 fails to build with nightly-2018-03-23 (eg) due to a too loose upper bound on streaming-commons. This has been fixed in git, could it be released ? This will allow hledger-web back into stackage.

**Comment by snoyberg** [comment]
I've just released 3.0.2.4 to Hackage.

**Comment by simonmichael** [comment]
Thanks!
