### ISSUE TITLE
Interest in having a function that returns the remote IP?

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/wai#687]
A long time ago I answered a StackOverflow question about getting a user's IP in Yesod: https://stackoverflow.com/a/33575615/1176156

I recently needed that functionality and it occurred to me it might make sense to add it to one of the WAI libraries directly, if you'd be interested. 

1. This would add a dependency on iproutes (@kazu-yamamoto 's package). Because of this, maybe it should be in wai-extra instead of a more core package?
2. The new network package removes `SockAddrCan` so that could be dropped from the implementation
3. I'm not sure if a web server could ever get a `SockAddrUnix`. If not, that could be dropped and the function would no longer need to return `Maybe`.

(This question basically intersects with a bunch of @kazu-yamamoto libraries (network, iproutes and wai) you may know the best home for such a function)

**Comment by kazu-yamamoto** [comment]
What about implementing a convert function (`:: SockAddr -> Maybe IP`) in `iproute`?
If you wish, I will implement it.

**Comment by MaxGabriel** [comment]
That would work. I was wondering if implementing it in Wai would allow us to ignore the sockAddrUnix case and drop the Maybe, but I’m not sure if that’s the case

**Comment by kazu-yamamoto** [comment]
Done: https://github.com/kazu-yamamoto/iproute
If you like it, I will release a new version of iproute.

**Comment by MaxGabriel** [comment]
Thanks, looks great!

**Comment by kazu-yamamoto** [comment]
A new version of `iproute` has been released.

**Comment by moll** [comment]
For the sake of record, Wai definitely gets Unix socket remote hosts. I run Wai this way behind Nginx. In fact, I'm just debugging why `Wai.requestHost req` returns a `SockAddrUnix` with a path of a single newline (`"\n"`). That's a surprising remote host. It's probably coming from a deeper layer, though.
