### ISSUE TITLE
warp-tls: setSocketCloseOnExec requires warp 3.2.17

### ISSUE THREAD

**Issue by QuLogic** [yesodweb/wai#688]
In warp-tls 3.2.4.2, [this call to setSocketCloseOnExec](https://github.com/yesodweb/wai/blob/master/warp-tls/Network/Wai/Handler/WarpTLS.hs#L301) was added. The [minimum warp](https://github.com/yesodweb/wai/blob/master/warp-tls/warp-tls.cabal#L24) is 3.2.10, but `setSocketCloseOnExec` was [added in warp 3.2.17](https://hackage.haskell.org/package/warp-3.2.18.2/docs/Network-Wai-Handler-Warp-Internal.html#v:setSocketCloseOnExec). It either needs to be made conditional or the minimum version can be bumped.

**Comment by kazu-yamamoto** [comment]
Than you for this report.
Set warp >= 3.2.17 and a new version has been released.
