### ISSUE TITLE
Testing HTTP/2

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#690]
- [x] GET, HEAD, POST
- [x] 0-length and large request/response body

**Comment by fizruk** [comment]
Should compatibility with various clients be tested as well (cURL, Chrome, Safari, Firefox, IE)?

**Comment by lucasdicioccio** [comment]
I can definitely give a hand using `http2-client` for generating a few scenarios (so that `http2-client` also benefits from some cross-testing).

**Comment by kazu-yamamoto** [comment]
This is done in `http2` library.
