### ISSUE TITLE
Safari won't load (also: HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR)

### ISSUE THREAD

**Issue by alexanderkjeldaas** [yesodweb/wai#703]
Using 

* stack Version 1.7.1, Git revision 681c800873816c022739ca7ed14755e85a579565 (5807 commits) x86_64 hpack-0.28.2
* resolver: nightly-2018-06-27

So I was fed up with haproxy + let's encrypt and wrote a simple reverse proxy using `reverse-proxy` and some loading of certs etc.

All was good until someone told me that it doesn't load on Safari.  I'm getting`NSPOSIXErrorDomain:100` which the internet says could be related to http/2 headers being somehow wrong.

Does this ring a bell?  Anyone seen this or tested on Safari.  Is there some well known service that works with warp-tls that works well with Safari?

```
wai 3.2.1.2
wai-app-static 3.1.6.2
wai-extra 3.0.22.1
wai-logger 2.3.2
wai-websockets 3.0.1.2
warp 3.2.22
warp-tls 3.2.4.3
```
I see that there was an issue with Safari earlier,

**Comment by alexanderkjeldaas** [comment]
website in question:  astor.ai

**Comment by alexanderkjeldaas** [comment]
I'm getting errors in `curl` as well now:
```
$ curl --version
curl 7.58.0 (x86_64-pc-linux-gnu) libcurl/7.58.0 OpenSSL/1.1.0g zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3
Release-Date: 2018-01-24
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL
$ curl -D out https://astor.ai/
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

**Comment by kazu-yamamoto** [comment]
@alexanderkjeldaas Would you try to test `master`?
If this does not solve your problem, please identify which header causes this problem, "Keep-Alive:", "Proxy-Connection:" or "Upgrade:"?

**Comment by alexanderkjeldaas** [comment]
I will.  It will take a while though.

**Comment by andreyk0** [comment]
For what it's worth, something has improved!
I used to see protocol errors in chrome (android and desktop), couldn't isolate enough to submit a bug report, so ran with HTTP2 disabled on an older version.
Just updated to (latest lts on stackage):
```
warp 3.2.25
warp-tls 3.2.4.3
```
used to get errors pretty consistently on some pages but haven't seen any so far, browsed for a while on mobile and desktop. 
Thanks a lot for looking into this!

**Comment by iand675** [comment]
Note: I think #740 will help this some by not triggering what some browsers treat as protocol errors. (Chrome at least treats INTERNAL_ERROR as PROTOCOL_ERROR for me).

**Comment by kazu-yamamoto** [comment]
I would like to close this issue because #740 is merged.
Please reopen if necessary.
