### ISSUE TITLE
warp-tls and connection keep-alive header error

### ISSUE THREAD

**Issue by k-bx** [yesodweb/wai#707]
So, I was trying to add a `Connection: keep-alive` header to my application, which is served in both, HTTP and HTTPS (via warp-tls). Surprisingly, once I've added the header, curl started showing an error `curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)`. I've re-created the minimal code here: https://github.com/k-bx/warp-keepalive

Without the header I get:

```
➜  warp-keepalive git:(master) ✗ curl --insecure -i https://localhost:3000
HTTP/2 200
date: Wed, 15 Aug 2018 17:41:17 GMT
server: Warp/3.2.23

Hello World%
```

Adding header gives:

```
➜  warp-keepalive git:(master) ✗ curl --insecure -i https://localhost:3000
curl: (92) HTTP/2 stream 1 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

I'm not an expert in HTTP/2, but from quick googling, I've found [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Keep-Alive) saying "Also, Connection and Keep-Alive are ignored in HTTP/2", but some [answer on SO](https://stackoverflow.com/questions/38188404/http2-and-nginx-when-would-i-use-a-keepalive-directive) have said: "So HTTP/2 doesn't negate need for keep-alives. It negates need for multiple connections (amongst other things)."

**Comment by alexanderkjeldaas** [comment]
Seems related to #703 - does Safari set this header for HTTP/2 unlike other browsers?

**Comment by kazu-yamamoto** [comment]
https://tools.ietf.org/html/rfc7540#section-8.1.2.2 says:

> HTTP/2 does not use the Connection header field to indicate
   connection-specific header fields; in this protocol, connection-
   specific metadata is conveyed by other means.  An endpoint MUST NOT
   generate an HTTP/2 message containing connection-specific header
   fields; any message containing connection-specific header fields MUST
   be treated as malformed

> This means that an intermediary transforming an HTTP/1.x message to
   HTTP/2 will need to remove any header fields nominated by the
   Connection header field, along with the Connection header field
   itself.  Such intermediaries SHOULD also remove other connection-
   specific header fields, such as Keep-Alive, Proxy-Connection,
   Transfer-Encoding, and Upgrade, even if they are not nominated by the
   Connection header field.

I will make a patch to remove Connection:, Keep-Alive, Proxy-Connection, Transfer-Encoding, and Upgrade in HTTP/2.

**Comment by kazu-yamamoto** [comment]
I could reproduce this and confirmed that the patch above fixed this issue.

@k-bx Would you try to test `master`?

**Comment by k-bx** [comment]
@kazu-yamamoto yes, it works, thank you!

```
➜  warp-keepalive git:(master) ✗ curl --insecure -i https://localhost:3000
HTTP/2 200
date: Fri, 07 Sep 2018 16:45:48 GMT
server: Warp/3.2.24
```

**Comment by kazu-yamamoto** [comment]
A new version of Warp has been released.
Thank you for your contribution!
