### ISSUE TITLE
Irritating comment in "Wai.hs" - "this library is built on top of the conduit package"

### ISSUE THREAD

**Issue by staffehn** [yesodweb/wai#713]
Hi. I’m trying to get a quick grasp of the wai package and therefore looking at the Hackage page, and one of the first thing I read is that wai "is built on top of the conduit package" (in [this file](https://github.com/yesodweb/wai/blob/master/wai/Network/Wai.hs#L7)). This seems to be outdated, since from version 3.0.0 on, there’s no dependency on the conduits package and also nothing obvious in the source code.

**Comment by snoyberg** [comment]
True. Could you send a PR to update the docs?

**Comment by staffehn** [comment]
I would. I have no idea what it *is* built on top now though, like - if the Bytestring builders are still relevant (probably yes?) or if anything new worth mentioning in that sentence was used, since, as mentioned, I only took a quick look on the documentation of the package so far.

**Comment by snoyberg** [comment]
I've pushed a commit to change the wording.
