### ISSUE TITLE
HCAR files

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#718]
@snoyberg You removed `hcar-wai.tex` and `hcar-warp.tex` in 9cf4a6890e345bcffcc18edf0700e0998750eb9c. Was it accidental?

- If it was accidental, I will add them again.
- If it was intentional, would you tell me the reason?

**Comment by snoyberg** [comment]
I believe they were already out-of-date, I always rely on the HCAR team to send me the most up to date versions of the entries. If you'd like them back, go ahead, apologies for removing them without checking.

**Comment by kazu-yamamoto** [comment]
Just curious. How do you track the versions of your HCAR article?

**Comment by snoyberg** [comment]
I don't at all. Each time I receive an email from the HCAR team, I download the files they send and update them.

**Comment by kazu-yamamoto** [comment]
OK. I will take your approach.

**Comment by kazu-yamamoto** [comment]
P.S. I submitted articles about WAI and Warp.

**Comment by snoyberg** [comment]
Awesome, thank you!
