### ISSUE TITLE
How is packet ordering achieved with wai.run?

### ISSUE THREAD

**Issue by crockeea** [yesodweb/wai#723]
This isn't a bug so much as it a question about appropriate usage. If a client sends two requests to a WAI server (using `run` or friends from Network.Wai.Handler.Warp), my understanding is that the server spawns two new `Application` threads. But it's not clear to me how my application can be sure to handle those requests in the order in which they were sent.

The only way I can imagine this being achieved is if the server does not spawn the second application (corresponding to a second request on the same connection) until the first application calls the response continuation. However, this would require a lot of buffering if the Application is non-trivial and there are many requests per connection.

What's the right way to process many simultaneous requests *over the same connection* and *in order*?

**Comment by snoyberg** [comment]
Excluding details of HTTP/2, which I'm not that familiar with, you're describing HTTP pipelining. The first request will be fully processed and answered before any other requests are processed at all.

**Comment by crockeea** [comment]
I'm just wondering how that works under the hood.

If I have
```
f :: Application
f req cont = do
  <some expensive work 1>
  
  let resp = responseBuilder ...
  recpt <- f resp

  <some expensive work 2>

  return recpt
```

are both <work 1> and <work 2> guaranteed to be finished before the server creates a new thread to handle another response? Internally, how does warp detect this? I mentioned that perhaps the response continuation could be used, but I suppose the server could also just track the thread lifetime.

**Comment by snoyberg** [comment]
They'll both finish. As to how it's guaranteed, you'd have to look at the codebase, but it's pretty straightforward in the main event loop.
