### ISSUE TITLE
Session Manager consumes large amounts of memory

### ISSUE THREAD

**Issue by crockeea** [yesodweb/wai#728]
I've attached a simple project in which the warp-tls server consumes large amounts of memory. There is a single client which repeatedly sends requests to the server. The memory profile changes from extremely greedy to constant by varying the parameters of the `tlsSessionManagerConfig` in memleak\Crypto\TLS.hs.
[memleak.zip](https://github.com/yesodweb/wai/files/2784138/memleak.zip)

$ cd memleak
$ stack build
$ stack exec server &
$ stack exec client
Then watch the server's memory usage climb.

I expect that since there is a single client connecting to the server, the session manager settings shouldn't affect *anything*, since all messages should be sent in the same session. Thus there should be exactly one session open on the server at all times. Instead, with the [`defaultConfig`](http://hackage.haskell.org/package/tls-session-manager-0.0.0.2/docs/Network-TLS-SessionManager.html#t:Config), my memory increases over time, and not slowly. After starting at about 12MB of memory, usage had risen to 600MB within an hour (corresponding to the client sending 17,000 requests).

Here are some other settings I used, and their resulting memory usage:

`tlsSessionManagerConfig=Just $ defaultConfig{...}`

`{}`: Over 600 MB in an hour
`{ticketLifetime=10}`: over 400 MB when I killed the process in < 1 hr
`{dbMaxSize=3}`: over 300 MB when I killed the process in < 1 hr
`{pruningDelay=5, dbMaxSize=3}`: over 700 MB when I killed the process in < 1 hr
`{ticketLifetime=10,pruningDelay=5}`: stayed around 37 MB, didn't seem to be rising, or rising very slowly
`{ticketLifetime=10,pruningDelay=5,dbMaxSize=3}`: ran 16 hours and stayed at 38.2 MB

It's unclear why setting the session lifetime affects memory usage, especially since restricting the `dbMaxSize` doesn't help by itself. 

Here's the output for various profiling options. [Note: -hr doesn't work; see [GHC #16182](https://ghc.haskell.org/trac/ghc/ticket/16182)]
![memoryprofile](https://user-images.githubusercontent.com/4899463/51557045-aa8ad700-1e30-11e9-9fea-8277b33120d3.png)

My two questions are: is the session manager even reusing the session? In either case, why do most settings for the manager result in very high memory consumption?

This problem occurs with GHC 8.6.3 on Windows 10 and Ubuntu 18.04. I sent an email to Kazu Yamamoto, maintainer of the tls-session-manager package, but have not received a response.

**Comment by crockeea** [comment]
I added the default extensions and tried again. I'm assuming that the "right" amount of memory use is somewhere in the <40MB range (and it seems like it should be *much* less than that). Even with `-XStrict` and `-XStrictDat`, memory usage was over 150MB within a few minutes using the `defaultConfig`.

**Comment by kazu-yamamoto** [comment]
@crockeea Thank you for your report. So, I need to consider deeply. Uhhhm.

**Comment by kazu-yamamoto** [comment]
Since I'm very busy now, I will get back to this issue in Febrary.

**Comment by crockeea** [comment]
@kazu-yamamoto Any progress on this? Does [#354](https://github.com/vincenthz/hs-tls/pull/354) fix the issue, or not? Is there anything I can do to help?

**Comment by kazu-yamamoto** [comment]
@crockeea Sorry, I forgot to inform you. Would you try `master` of `tls`?  We suspect that this issue is due to `ByteString` fragmentation and modified the code to copy `ByteString` relating to sessions.

**Comment by crockeea** [comment]
The example included with the original post doesn't work with hs-tls HEAD, so I had to make some modification. My preliminary results indicate that there is no change, or if anything, that matters are now worse. I'll do some further investigating and try to post an updated example.

**Comment by crockeea** [comment]
[memleak2.zip](https://github.com/yesodweb/wai/files/2876737/memleak2.zip)
Here's an updated example that compiles with hs-tls HEAD and still leaks like crazy. Server uses about ~350 MB after just 15 minutes. This should be easy to test with new versions of hs-tls; just update the hash in the stack.yaml file.

**Comment by crockeea** [comment]
I think I fixed the problem in #732

**Comment by kazu-yamamoto** [comment]
I found one more speak leak in the session manager. Months ago, TLS maintainers found the values were leaking due to `ByteString`. So, we changed to copy the values.

I found that keys are also leaking due to `ByteString`. So, we should also copy the keys. I will send a PR to TLS and this leaking should be fixed in version 1.5.1.
