### ISSUE TITLE
warp-tls doesn't complain when it can't bind to the port

### ISSUE THREAD

**Issue by neongreen** [yesodweb/wai#730]
I have something running on port 4570 on my machine.

I attempt to start a warp-tls server on the same port:

```haskell
import Network.Wai.Handler.WarpTLS
import Network.Wai.Handler.Warp

main = runTLS (tlsSettings "cert.pem" "key.pem") (setPort 4570 defaultSettings) undefined
```

It starts (but is inaccessible, of course). I would expect it to throw an exception instead. Am I missing something?

---

```
OS: macOS
warp version: 3.2.25
warp-tls version: 3.2.4.3
```

**Comment by kazu-yamamoto** [comment]
This is because macOS controls IPv4 and IPv6 separately. For example, your something binds to IPv6:4570 while warpTLS binds IPv4:4570. 

`netstat -a -n | grep 4570` would help.

**Comment by kazu-yamamoto** [comment]
I would like to close this issue. Please reopen if necessary.
