### ISSUE TITLE
Add Map from MimeType to canonical Extension

### ISSUE THREAD

**Issue by tysonzero** [yesodweb/wai#738]
Currently I am converting mime types back into file extensions to generate appropriate extensions for uploading files. It would be nice if there was some easy functionality for going the opposite direction.

**Comment by snoyberg** [comment]
Does [`defaultMimeMap`](https://www.stackage.org/haddock/lts-13.15/mime-types-0.1.0.9/Network-Mime.html#v:defaultMimeMap) provide what you're looking for? I realize you'd have to reverse it yourself, and there may be more than one potential extension, but I'm wondering if this is good enough for your use case.

**Comment by tysonzero** [comment]
Yeah that is what I am using at the moment and it works. So not an urgent issue by any means but thought it was worth suggesting some sort of functionality for finding the "canonical" extension of a given mime-type.

**Comment by kazu-yamamoto** [comment]
@tysonzero Would you send a PR?

**Comment by tysonzero** [comment]
On what basis should the canonical file extension be decided? For my use case just effectively picking the first (earliest lexicographically/alphabetically) works fine, but in the general case that might not be desired.

**Comment by tysonzero** [comment]
Perhaps the [IANA](https://www.iana.org/assignments/media-types/media-types.xhtml) could be used.

One thing worth noting is that neither direction in this relation is actually truly injective, since one mime type can have multiple valid extensions, and one extension can have multiple valid mime types.

This isn't a huge problem as we can just pick a canonical value in each direction. It just means that the extension-to-mime map won't include all mime-types, and the mime-to-extension map won't include all extensions.

**Comment by kazu-yamamoto** [comment]
@tysonzero If you want this to go forward, please show us your proposal code.

**Comment by Vlix** [comment]
Implemented in #948
