### ISSUE TITLE
Releasing warp 3.2.27

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#742]
#740 and #741 have been merged.
It's time to release a new version.
@snoyberg Should we fix CI before releasing it?

**Comment by snoyberg** [comment]
I won't be able to look into this until next week. I don't see a problem
with making a release now if you're ready.

**Comment by kazu-yamamoto** [comment]
OK. I will take core of this issue.

**Comment by kazu-yamamoto** [comment]
Warp 3.2.27 has been released.
