### ISSUE TITLE
auto-update feature request: be able to control leading vs. trailing edge in Control.Debounce

### ISSUE THREAD

**Issue by thomasjm** [yesodweb/wai#745]
Most debounce packages I've seen allow you to specify whether the debounced action should occur on the leading edge or trailing edge of the wait period. For example, [Lodash's version](https://lodash.com/docs/4.17.11#debounce) has a good API.

For some debouncing use-cases, you want the update to happen only after one or more events have happened and things have settled down. But the current package always fires on the leading edge, so I end up with two updates when I would prefer only one.

**Comment by snoyberg** [comment]
Would you be interested in submitting a PR to add this functionality?

**Comment by thomasjm** [comment]
I won't have time in the foreseeable future unfortunately, but maybe eventually if nobody else gets around to it first.

**Comment by kazu-yamamoto** [comment]
Fixed in #756. Let's close.
