### ISSUE TITLE
setOnException not called in warp-tls

### ISSUE THREAD

**Issue by k-bx** [yesodweb/wai#746]
I see a difference in behavior between warp and warp-tls. The latter doesn't call my setOnException handler.

I've made a fully reproducible repo (run with `stack run`) where you can comment/uncomment to switch between http/https and see the difference: https://github.com/k-bx/servant-custommonad-logging/blob/master/waitls-onexception-bug/src/Main.hs

```
$ curl -i localhost:8000/api/error-out
```

HTTP Gives:

```
Allocating scarce resource
Cleaning up
Error: caught an exception: Erroring out
CallStack (from HasCallStack):
  error, called at src/Main.hs:33:12 in main:Main. Call stack: CallStack (from HasCallStack):
  onExceptionAct, called at src/Main.hs:37:29 in main:Main
```

Switchging to https:

```
$ curl --insecure -i https://localhost:8000/api/error-out
```

Gives no output from the app.

**Comment by kazu-yamamoto** [comment]
I'm very sorry. I did not notice this and the code changed very much.
Would you give a look at the current code and think how to integrate?

**Comment by k-bx** [comment]
Sure, I can check it out on latest wai/warp/http2. Just tried -- getting this build error:

```
http2                 > Configuring http2-2.0.0...
http2                 > build
http2                 > Preprocessing library for http2-2.0.0..
http2                 > Building library for http2-2.0.0..
http2                 > [ 1 of 45] Compiling Imports
http2                 > [ 2 of 45] Compiling Network.HPACK.Builder
http2                 > [ 3 of 45] Compiling Network.HPACK.HeaderBlock.Integer
http2                 >
http2                 > /tmp/stack31729/http2-2.0.0/Network/HPACK/HeaderBlock/Integer.hs:40:11: error:
http2                 >     Not in scope: type constructor or class ‘WriteBuffer’
http2                 >    |
http2                 > 40 | encode :: WriteBuffer -> (Word8 -> Word8) -> Int -> Int -> IO ()
http2                 >    |           ^^^^^^^^^^^
http2                 >
http2                 > /tmp/stack31729/http2-2.0.0/Network/HPACK/HeaderBlock/Integer.hs:85:27: error:
http2                 >     Not in scope: type constructor or class ‘ReadBuffer’
http2                 >    |
http2                 > 85 | decode :: Int -> Word8 -> ReadBuffer -> IO Int
http2                 >    |                           ^^^^^^^^^^
http2                 >
```

You can reproduce by cloning this repo https://github.com/k-bx/servant-custommonad-logging and then doing `cd waitls-onexception-bug && stack build --fast`

**Comment by kazu-yamamoto** [comment]
Very strange. `network-byte-order` version 0.1.1 should provide both. And `http2` version 2.0.0 requires it.

**Comment by k-bx** [comment]
Ok, I'll check it later sometime.

**Comment by hanshoglund** [comment]
I've run into this on a private repo using LTS-11.17 (warp-tls-3.2.4.3). Will try to do a minimal repro.

**Comment by k-bx** [comment]
Just spent a minute checking this. The issue is still present, made a PR fixing it https://github.com/yesodweb/wai/pull/770
