### ISSUE TITLE
content-length  header in wai-app-static does not appear automatically when use yesod devel.

### ISSUE THREAD

**Issue by idcm** [yesodweb/wai#749]
Though a note in the sources code of wai-app-static say warp can do this automatically. This is ture when compiled the program using stack build, but  when I test the program using yesod devel,  strange thing happens, the "Content-Length" header just disappear. Some thing may be done by yesod devel, but I can not find out.

**Comment by snoyberg** [comment]
This is probably due to the reverse proxy provided by `yesod devel`. You can try `--disable-reverse-proxy` and see if the headers come through.

**Comment by idcm** [comment]
The headers come through with "--disable-reverse-proxy".

**Comment by snoyberg** [comment]
Cool. This is all working as expected, so closing.
