### ISSUE TITLE
A new version of Warp

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#755]
I'm going to release a new version of Warp. But I would like to register this issue just in case.
Since the type of `http2dataTrailers`, I would like to make a major release: 3.3.0. I updated the change log.

@snoyberg Would you make double check?

**Comment by snoyberg** [comment]
I'll be out of the house all day today, but can check tomorrow. From what you've described, this is the correct version bump.

**Comment by snoyberg** [comment]
@kazu-yamamoto No objection to the release from me, thanks for checking. 👍

**Comment by kazu-yamamoto** [comment]
Thanks. I have released warp-3.3.0 and warp-tls-3.2.7.
@snoyberg You should release a new version of wai-app-static.
