### ISSUE TITLE
Change log specifies incorrect pull request

### ISSUE THREAD

**Issue by centromere** [yesodweb/wai#760]
The [change log](https://github.com/yesodweb/wai/blob/master/warp/ChangeLog.md#330) says:

> Switching from the original implementation to HTTP/2 server library. #752

but in 3.2.28 it says:

> Using the Strict and StrictData language extensions for GHC >8. #752

and lists the same PR for both.

**Comment by kazu-yamamoto** [comment]
Sorry for the late response. I did not notice this.
This is fixed in a7c8be2.
Thank you for your report!
