### ISSUE TITLE
sinkRequestBodyEx fails to parse multipart/form-data, loops

### ISSUE THREAD

**Issue by goolord** [yesodweb/wai#763]
Ubuntu 18.04
ghc 8.6.3
cabal 2.4.1.0
wai-extra == 3.0.27
wai == 3.2.2.1

minimal reproducible example:
https://github.com/goolord/wai-sinkRequestBodyEx-mre/blob/master/src/Main.hs

with `noLimitParseRequestBodyOptions`, this loops forever

**Comment by snoyberg** [comment]
I don't reproduce that behavior. Using Stack and lts-13.28, I get:

```
Main.hs: ConnectionError (UnknownErrorCode 431) "Request Header Fields Too Large"
```
