### ISSUE TITLE
wai-extra: new EventSource builder to enable recursive emitters?

### ISSUE THREAD

**Issue by xaviershay** [yesodweb/wai#765]
Let's say I'm writing an eventsource handler that counts upwards. To do this with current API, I _think_ the best way is to use an `IORef` with `eventSourceAppIO`. WDYT about a method like this as an alternative:

```
eventStreamIO :: ((Network.Wai.EventSource.ServerEvent -> IO()) -> IO ()) -> Application
eventStreamIO handler _ respond = respond $ responseStream status200 [(hContentType, "text/event-stream")] (streamer handler)
  where
    streamer handler sendChunk flush = do
      handler emit

      where
        emit :: Network.Wai.EventSource.ServerEvent -> IO ()
        emit event = do
           case eventToBuilder event of
             Nothing -> return ()
             Just b  -> sendChunk b >> flush
```

The type is a bit weird, but it lets me do:

```
myApp :: Application
myApp = do
  eventStreamIO (handle 0)

  where
    handle :: Int -> (Network.Wai.EventSource.ServerEvent -> IO ()) -> IO ()
    handle counter emit = do
      emit $ Network.Wai.EventSource.ServerEvent
               (Just "snapshot")
               Nothing
               [ Data.Binary.Builder.fromLazyByteString
                   (Data.Aeson.encode $ counter)
               ]

      Control.Concurrent.threadDelay 1000000

      handle (counter + 1) emit
```

... which I think is quite nice and feels more like how I would write this sort of loop normally?

I'm happy to contribute a patch (with better naming and docs) if you think this seems reasonable. Quite possible I'm doing it completely wrong though! Am pretty new to this library.

**Comment by xaviershay** [comment]
There's some prior art in `wai-websockets`, which isn't exactly the same interface but allows the same approach: http://hackage.haskell.org/package/wai-websockets-3.0.1.2/docs/Network-Wai-Handler-WebSockets.html (recursively call `sendTextData`)

**Comment by snoyberg** [comment]
I'm OK with something like this in principle, no strong opinions right now.

**Comment by xaviershay** [comment]
Thanks, I'll try putting together a proper PR!
