### ISSUE TITLE
Http headers for HEAD method and GET method differs

### ISSUE THREAD

**Issue by kamoii** [yesodweb/wai#768]
When the reponse is created using `responseLBS`, the response http headers for `GET` method and `HEAD` method differs. `GET` haves `Transfer-Encoding: chunked` header but `HEAD` doesn't.

Test code:
```haskell
main :: IO ()
main = run 9000 $ \_req resf -> do
  resf $ responseLBS ok200 [("content-type", "text/plain")] "test"
```

Request with `GET` and `HEAD`
```
$ http -p hb GET localhost:9000
HTTP/1.1 200 OK
Date: Thu, 29 Aug 2019 14:41:46 GMT
Server: Warp/3.2.28
Transfer-Encoding: chunked
content-type: text/plain

test

$ http -p hb HEAD localhost:9000
HTTP/1.1 200 OK
Date: Thu, 29 Aug 2019 14:41:55 GMT
Server: Warp/3.2.28
content-type: text/plain
```

According to [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html), `GET` and `HEAD` response http headers should be same.

```
wai version: 3.2.2.1
warp version: 3.2.28
stack version: Version 2.1.3, Git revision 636e3a759d51127df2b62f90772def126cdf6d1f (7735 commits) x86_64 hpack-0.31.2
ghc version: The Glorious Glasgow Haskell Compilation System, version 8.6.5
uname: Linux carbon 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
```

**Comment by kazu-yamamoto** [comment]
[RFC 7231](https://tools.ietf.org/html/rfc7231#section-4.3.2) says:

> The server SHOULD send the same
   header fields in response to a HEAD request as it would have sent if
   the request had been a GET, except that the payload header fields
   (Section 3.3) MAY be omitted. 

[RFC 7230](https://tools.ietf.org/html/rfc7230#section-3.3.1) says:

> Transfer-Encoding MAY be sent in a response to a HEAD request

Thus, `Transfer-Encoding` should be sent but not MUST.

So, my question comes: do we have sufficient reason to spend our time to fix this?

**Comment by kamoii** [comment]
@kazu-yamamoto If its not a `MUST`, no, I don't think there is any reason to spend time fixing this issue.
Thank you for responding. Closing the issue.
