### ISSUE TITLE
warp-tls: responseFile doesn't seem to work

### ISSUE THREAD

**Issue by fumieval** [yesodweb/wai#769]
In https://github.com/fumieval/webauthn/blob/2f496a4809a4e328970820f070b904412969aaff/wai-middleware-webauthn/demo/Main.hs, using `responseFile` instead of `responseLBS` causes ERR_SPDY_PROTOCOL_ERROR on the browser. ~It displays
`HandshakeFailed (Error_Packet_unexpected "Alert13 [(AlertLevel_Fatal,CertificateUnknown)]" " expected: handshake 13")` __in both cases__, not sure if it's relevant.~

Additional info:

* macOS mojave 10.14.6 18G95
* Google Chrome 76.0.3809.132
* [cabal.project.freeze](https://github.com/fumieval/webauthn/blob/middleware/cabal.project.freeze)

**Comment by kazu-yamamoto** [comment]
What will happen if set `settingsHTTP2Enabled` to `False`?

**Comment by fumieval** [comment]
That did work.

**Comment by kazu-yamamoto** [comment]
Did you access to `https`, not to `http`?
Anyway, is the certificate of your server valid? I.e. do you provide certificate chains including all intermediate CAs?

**Comment by fumieval** [comment]
The problem I'm talking about is `ERR_SPDY_PROTOCOL_ERROR`, not `HandshakeFailed`. `ERR_SPDY_PROTOCOL_ERROR` happens only when `responseFile` is used.

**Comment by kazu-yamamoto** [comment]
This is not relating to TLS. TLS is just required to negotiated HTTP/2.
This bug happens on all platforms including macOS if `settingsFdCacheDuration` is 0, the default value.

b688d9b30e0b0b05813cc612ae03e64af112e04b should fix this.

**Comment by kazu-yamamoto** [comment]
A new version of `warp` has been released.
Than you for reporting this issue.
