### ISSUE TITLE
Hiding passwords from RequestLogger

### ISSUE THREAD

**Issue by emhoracek** [yesodweb/wai#774]
I'd like to use RequestLogger in my app because it seems like the simplest logging solution, but I need to be able to filter passwords from the logs. I see that I can create a `OutputFormatterWithDetails` but it's pretty annoying to have to import a bunch of low-level libraries to stitch together a custom logging string, when I really like the `Detailed` format except that it logs passwords. I have a fork where I added a param to `Detailed` that lets you add a function `Param -> Param` so you can remove whatever you want from the params, but I'm not sure if there's an easier way that I'm missing. If that solution would be acceptable to y'all, I'm happy to open a PR.

**Comment by snoyberg** [comment]
Do I understand correctly that you're concerned about passwords in query string parameters? Standard best practice is to not include passwords or any sensitive information there, since multiple systems may by default log that information (including intermediate proxies and clients themselves). Instead, it's better to include passwords in POST parameters (i.e. the request body) or some kind of authentication token in a header.

**Comment by emhoracek** [comment]
@snoyberg No, these passwords are in POST parameters. The `Detailed True` format prints the POST body and POST parameters.

**Comment by emhoracek** [comment]
Here's a test I added to the PR I just submitted (#776 )
```
caseModifyPostParamsInLogs :: Assertion
caseModifyPostParamsInLogs = do
    flip runSession (debugApp (Detailed False Nothing) unredacted) $ do
        let req = toRequest "application/x-www-form-urlencoded" "username=some_user&password=dont_show_me"
        res <- srequest req
        assertStatus 200 res

    flip runSession (debugApp (Detailed False (Just hidePasswords)) redacted) $ do
        let req = toRequest "application/x-www-form-urlencoded" "username=some_user&password=dont_show_me"
        res <- srequest req
        assertStatus 200 res

  where
    unredacted = [("username", "some_user"), ("password", "dont_show_me")]
    redacted = [("username", "some_user"), ("password", "***REDACTED***")]

    postOutputStart params = TE.encodeUtf8 $ T.toStrict $ "POST /\n  Params: " <> (T.pack . show $ params)
    postOutputEnd = TE.encodeUtf8 $ T.toStrict "s\n"

    hidePasswords p@(k,_) = if k == "password" then (k, "***REDACTED***") else p

    debugApp format output req send = do
        iactual <- I.newIORef mempty
        middleware <- mkRequestLogger def
            { destination = Callback $ \strs -> I.modifyIORef iactual $ (`mappend` strs)
            , outputFormat = format
            }
        res <- middleware (\_req f -> f $ responseLBS status200 [ ] "") req send
        actual <- fromLogStr <$> I.readIORef iactual
        actual `shouldSatisfy` S.isPrefixOf (postOutputStart output)
        actual `shouldSatisfy` S.isSuffixOf postOutputEnd

        return res 
```

**Comment by Vlix** [comment]
#826 has implemented this, so I'm closing the issue.
