### ISSUE TITLE
incorrect Request.isSecure for plain text HTTP/2 connection

### ISSUE THREAD

**Issue by bjin** [yesodweb/wai#777]
### steps to reproduce

* Compile and run the following wai application (tested with stackage `nightly-2019-11-01`)

~~~haskell
{-# LANGUAGE OverloadedStrings #-}
module Main where

import qualified Network.HTTP.Types         as HT
import           Network.Wai
import           Network.Wai.Handler.Warp

app :: Application
app req respond =
    respond $ responseLBS
        HT.status200
        [("Content-Type", "text/plain")]
        (if isSecure req then "secure=true" else "secure=false")

main :: IO ()
main = run 8080 app
~~~

* Connect to application with HTTP/1.1 get correct `Request.isSecure`
~~~sh
$ curl http://localhost:8080/
secure=false
~~~

* Connect to the application with plain text HTTP/2 get incorrect `Request.isSecure`
~~~sh
$ curl --http2-prior-knowledge http://localhost:8080/
secure=true
~~~

### expected behavior
The application should return the same response for HTTP/1.1 and HTTP/2, and since both example above is in plain text, the response should be `secure=false`.

### additional notes
While no major Browser supports plain text HTTP/2 connections. This issue still have some security implications.

* For wai application running on `warp-tls` server overriding `onInsecure` to have customized HTTPS redirection page, the server might leak sensitive content with plain text HTTP/2 connection.
* Assuming the warp-tls server requires valid client certificate to establish connections, plain text HTTP/2 connection will be able to bypass such restrictions.

**Comment by snoyberg** [comment]
@kazu-yamamoto do you have thoughts on this?

**Comment by kazu-yamamoto** [comment]
To tell the truth, I knew this issue. But I have not motivated for a long time, sorry.

eb33f4b6d0cd316be4bcd811337c9350cca34a2c should fix this. With my toy code:
```
% curl -k --http2-prior-knowledge http://localhost/
secure=false
% curl -k --http2-prior-knowledge https://localhost/
secure=true
```

@bjin Would you try `master`?

**Comment by bjin** [comment]
yes, it fixed the issue. thanks.

**Comment by kazu-yamamoto** [comment]
A new version has been released.
Thank you for your contribution!
