### ISSUE TITLE
Extreme slowdowns (x20) in web spec tests with warp==3.3.4

### ISSUE THREAD

**Issue by hasufell** [yesodweb/wai#780]
### Bug Report

We are running some webspecs with a scotty/warp/wreq/http2 stack.

The freeze file can be seen at: https://gist.github.com/hasufell/0d709bbbdc06af9a86809d64be69dd6c#file-cabal-freeze-broken

Our entire test suite used to take **8 minutes**, with the bump to `warp==3.3.4` it takes about **3 hours**. There is no other bump that can cause it, *all other dependencies are exactly the same*.

* OS name and version: ubuntu bionic docker containers (reproducible outside of docker as well)
* Tools: ghc-8.6.5, cabal-3

I wasn't able to create a minimal test case yet, please bear with me.

**Comment by hasufell** [comment]
Through bisecting I found the commit: https://github.com/yesodweb/wai/commit/aee7377197a30aff4cdff3064a569bdf01d1d42b
related issue: https://github.com/yesodweb/wai/issues/673

**Comment by kazu-yamamoto** [comment]
@hasufell Thank you for reporting.

`gracefulClose` adds extra 5 seconds to close a connection in *worst* case. Does webspec include about 2,000 test cases?

**Comment by hasufell** [comment]
> Does webspec include about 2,000 test cases?

I think about ~1k, but some of them have multiple requests.

Shouldn't `gracefulClose` be specific to HTTP/2?

**Comment by kazu-yamamoto** [comment]
Yes, `gracefulClose` helps HTTP/2. But it should not harm HTTP/1.1.
Could you look into packet dumps to see if clients send TCP FINs?
It FINs are coming, this is a bug of `gracefulClose`. If FINs are not coming, this is a bug of the client.

**Comment by hasufell** [comment]
I don't see any FINs from the client https://gist.github.com/hasufell/d87db04ada989c34bba37beebfadde01

> But it should not harm HTTP/1.1.

IMO, it's a huge assumption. I think such a big change should be as narrow in scope as possible.

**Comment by kazu-yamamoto** [comment]
OK. I will think workaround for HTTP/1.1.

**Comment by hasufell** [comment]
@kazu-yamamoto afais wreq uses http-client to do the calls and this doesn't seem to send FIN either. @snoyberg?

**Comment by snoyberg** [comment]
I don't know offhand, but the keepalive/connection manager code in http-client would probably prevent that.
