### ISSUE TITLE
Eventsource with HTTP/2 + TLS terminates after approximately 60s

### ISSUE THREAD

**Issue by larskuhtz** [yesodweb/wai#785]
We have an event source, that when served via HTTP/2 works fine, but when served via HTTPS/2 terminates after about 60s, but sometimes also earlier. On the server side the application receives `ThreadKilled`. On the network side the TLS connection is closed normally with `Alert (Level: Warning, Description: Close Notify)` and the TCP connection is closed.

This happens with browsers and curl as clients. It does not happen with `http-client` as client. It was tested with `warp-tls-3.2.9` and most recent versions of `tls` and `cryptonite`.

The issues doesn't occur with HTTP/1.1.

**Comment by kazu-yamamoto** [comment]
Thank you for your report. The point is getting clearer. I will try to find a source of this bug.

**Comment by kazu-yamamoto** [comment]
Relating to #692.

**Comment by kazu-yamamoto** [comment]
`http-client` does not support HTTP/2. I think that HTTP/1.1 was used in your test.

**Comment by larskuhtz** [comment]
That would explain why the issue was not observed with http-client. So, it's specific to HTTP/2 over TLS.

**Comment by kazu-yamamoto** [comment]
Ah. OK. Thanks.
Would you tell me how to use `curl` to reproduce this issue?

**Comment by larskuhtz** [comment]
Here is some code that I use to reproduce the issue. It contains a comment about how to test with curl. It also has some html to reproduce from a browser. https://gist.github.com/larskuhtz/f8eb5616d5eb9a0c7afa228171c45e76

The example isn't minimal, but roughly mimics the relevant bits of our actual production code. Let me know if you want me to try to come up with a minimal example.

**Comment by kazu-yamamoto** [comment]
Now I reproduced it!

**Comment by kazu-yamamoto** [comment]
This is not specific to HTTP/2 over TLS but specific to HTTP/2.
Please try `curl -v --http2-prior-knowledge -H "Accept:text/event-stream" "http://127.0.0.1:8080""`.

This makes sense to me.

**Comment by kazu-yamamoto** [comment]
@larskuhtz Would you try this patch? https://github.com/kazu-yamamoto/wai/commit/520c3de860d9e31ac39470d03c381a3ed405b096

This fixed this issue on my local machine.

**Comment by kazu-yamamoto** [comment]
The minimum server code so far: https://gist.github.com/kazu-yamamoto/370d3ff3e0bc28bbfe6eb2ecc67feb95

**Comment by kazu-yamamoto** [comment]
This should be fixed with Warp 3.3.6.
Please reopen if necessary.

**Comment by larskuhtz** [comment]
@kazu-yamamoto thanks a lot for taking care of this! I'll try your fix soon.
