### ISSUE TITLE
Deleting stale branches

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#788]
@snoyberg We have about 30 stale branches. They are annoying me when I try to find a target commit. May I delete stale branches? Which branches do you want to keep?

**Comment by kazu-yamamoto** [comment]
The `wai-frontend-monad` branch is huge and really annoying.

**Comment by snoyberg** [comment]
I've cleaned up a bunch of these. Are you happy with what's left?

**Comment by kazu-yamamoto** [comment]
Yes. Yes. Yes! Thank you!
