### ISSUE TITLE
Large builder-generated responses are unreasonably timed out while being written

### ISSUE THREAD

**Issue by exarkun** [yesodweb/wai#797]
If an application provides a builder for a response body that builds a sufficiently large value then it cannot be written to a client before the "slow-loris" timeout engages and closes the connection.  This seems to be because the `sendRsp` implementation for `RspBuilder` never tickles the timeout manager while sending the response data to the connection.

Imagine a response body of 1000 KiB and a client which can receive data at 10 KiB / sec.  It will take around 100 seconds to deliver this response to the client.  Meanwhile, the reasonable default timeout will elapse and the connection will be closed.  This is regardless of the real transfer progress being made.  The client may have received most of the data at the point the timeout kicks in but this won't save it.  Of course, if these numbers seem too small, they can all be multiplied by any factor and the scenario holds.

The issue can be worked around, to some extent, by raising the timeout.  However, a timeout which is large enough to handle cases like this is also too large for small responses.

It seems like the "slow-loris" timeout should be reserved for truly slow transfers.  Perhaps it could be tickled whenever enough progress is made writing the response.

It is also worth noting that if one manages to hand Warp a *stream* response, the `sendRsp` implementation for `RspStream` uses `sendFragment` which does tickle the timeout manager.  It's hard to see why, from an application perspective, there should be any difference in timeout behavior between providing a builder and providing a stream.  This seems doubly important in cases where it might be hard to provide one instead of the other (in my particular case, returning a JSON body by way of Servant, it's not clear how to cause the response to be built with a stream instead of a builder (from a lazy bytestring)).

**Comment by snoyberg** [comment]
It's definitely intended by me that each reasonably-sized chunk that is sent in a response should tickle the timer. If it's not behaving that way, I'd consider it a bug. @kazu-yamamoto does this issue sound familiar to you?

**Comment by kazu-yamamoto** [comment]
It seems to me that the current semantic of timeout in the HTTP/1.1 code is ambiguous. It's good time to re-consider things around timeout. I think more `tickle`s are necessary.

**Comment by kazu-yamamoto** [comment]
Probably relating to #684
