### ISSUE TITLE
Supporting HTTP/3 (aka HTTP/2 over QUIC)

### ISSUE THREAD

**Issue by kazu-yamamoto** [yesodweb/wai#802]
I added `warp-quic` to this repository. 

This library depends on no-yet-released libraries including `tls`, `quic` and `http3`. I don't recommend to use it now.

HTTP/3 and QUIC are still under standardization. I will release `quic` and `http3` when their specs become RFCs.

Anyway, `warp-quic` is working well. I'm looking forward to the day to release `warp-quic`!

Cc: @snoyberg

**Comment by snoyberg** [comment]
I was just discussing QUIC with some coworkers yesterday, we're all very excited about your work here!

**Comment by kazu-yamamoto** [comment]
FYI: https://kazu-yamamoto.hatenablog.jp/entry/2020/06/09/155236

**Comment by lachrimae** [comment]
What's the situation with the HTTP/3 project? @kazu-yamamoto mentioned wanting to release some dependency libraries once these specs became RFCs.

It seems like [QUIC has become an RFC](https://datatracker.ietf.org/doc/html/rfc9000), and [so has HTTP/3](https://datatracker.ietf.org/doc/html/rfc9114/), though I am not clear on the exact meaning of the various RFC statuses. (These two have the sub-status "Proposed Standard".)

**Comment by kazu-yamamoto** [comment]
`quic`, `http3` and `warp-quic` are already on Hackage.

**Comment by GuillaumeCisco** [comment]
Hello,

Maybe a non-sense question, but why warp and warp-quic are not merged in a single project?
This way, projects depending on warp could easily give the possibility to use http/3.

Does it sound realistic?
