### ISSUE TITLE
is it possible to flush headers early when using responseStream ?

### ISSUE THREAD

**Issue by docteurklein** [yesodweb/wai#803]
I'm using wai-extra's `eventSourceAppChan` and the headers are only sent after the first activity on the chan, which causes clients like curl to timeout with `curl: (52) Empty reply from server`.

I think the headers should be flushed right after the connection is initiated.
Any idea how I could achieve that?

**Comment by snoyberg** [comment]
Not sure it'll work, but could you try adding a `CommentEvent` with a [`flush`](https://www.stackage.org/haddock/lts-15.13/binary-0.8.7.0/Data-Binary-Builder.html#v:flush)?

**Comment by docteurklein** [comment]
I thought about putting an initial CommentEvent to trigger the header flush, but it should be triggered right after a new connection, which doesn't seem to be possible (how to know when a connection is made) ?

Thanks for the quick answer and your time :)

**Comment by docteurklein** [comment]
I just tested this change https://github.com/yesodweb/wai/commit/c4aa172e3978837313424f843355563fa02c5f94
and it seems to do the trick.
Do you think i should try to propose a PR?

**Comment by snoyberg** [comment]
I'm OK with such a PR.
