### ISSUE TITLE
Control.Reaper undocumented cache lookup/cleanup race

### ISSUE THREAD

**Issue by vdukhovni** [yesodweb/wai#809]
The `Control.Reaper` module includes example usage as a cache with a periodic cleanup action.

However, I believe that the cache exhibits an unexpected and undocumented behaviour, in that it is
made empty when the cleaner action starts, and threads doing lookups overlapping that action will
needlessly perform work and create new entries that will need to be merged with the retained cache
once the cleaner completes its work.

A somewhat different design may be needed for the cache use-case.  The existing design seems better
suited to handling job lists and the like.

Perhaps I'm misreading [the code in question](https://github.com/yesodweb/wai/blob/master/auto-update/Control/Reaper.hs#L172-L182)?

**Comment by snoyberg** [comment]
I think you're reading the code correctly

**Comment by vdukhovni** [comment]
Perhaps a disclaimer about the current limitation (behaviour) is sufficient, unless there's an appetite for a more atomic cleaner action that can replace the cache without zeroing it temporarily.  But I don't think this meshes well with the job reaping use-case.  The two just aren't looking for the same semantics.

It seems that the cache example was just a refactoring of documentation for a plausible, but likely not natural, use-case. And a cache API would look different.

For my own needs I ended up writing something much less general (an LRU cache over OrdPSQ with expiration times embedded in the values, and because I expect rather low concurrency, an MVAR around the PSQ and just prune on every lookup and insert. No timers, because the cache just holds some memory slots.

Robust and performant parallel cleanup with concurrent readers is harder, and probably not worth trying to shoehorn into this module?

What are your thoughts?

**Comment by snoyberg** [comment]
Sounds good. Doc PR definitely welcome

**Comment by snoyberg** [comment]
Addressed by #810
