### ISSUE TITLE
Behavior of strictRequestBody and lazyRequestBody is undocumented

### ISSUE THREAD

**Issue by MaxGabriel** [yesodweb/wai#811]
`strictRequestBody` and `lazyRequestBody` consume the request body such that calling them twice will yield empty string the second time. This is fairly error prone and I think unexpected.

Example cases where you might access the body twice:

1. Middleware, which might read the body to log data about it up front, or could catch an exception in processing the request and log the request's body.
2. Authentication checks, which are separate from application code in e.g. Yesod. For example, [Github's webhook API](https://developer.github.com/webhooks/securing/) is authenticated by applying HMAC to the request body 

In these cases, it may be difficult or impossible to get the `ByteString` body and thread it through to later calls.

I would propose:

1. The functions should definitely be documented to say that a second call with return empty string. 
2. The functions be renamed to something that suggests they are not idempotent, if people can come up with anything better. Possibly `consumeRequestBodyStrict`? `nonIdempotentStrictRequestBody`? `nonRepeatableReadStrictRequestBody`? Not sure.
3. The docs should explain the rationale for this (I assume to keep total memory usage down if possible)
4. The docs should suggest a workaround, if there is a decent way to avoid this behavior. I'm not sure if there is one—the best method I know in Yesod would be to use the per-request caching to store the ByteString there so it can be reused multiple times, but that's Yesod specific. Possibly WAI could be modified to optionally store the results to be retrieved later?

Thoughts?

**Comment by snoyberg** [comment]
1. Agreed
2. I'm not in favor of breaking the API
3. That's reasonable, but I think the answer is straightforward: the entire point of the API is to be streaming, so consuming is a requirement
4. No, that breaks the point of the API and encourages bad behavior. There shouldn't be a "workaround," there should be "if you really think you have this need, do X."

**Comment by MaxGabriel** [comment]
I guess, how do you think about the two example use cases I provided? Is the answer that middleware or middleware-esque functions like Yesod's [isAuthorized](https://www.stackage.org/haddock/lts-16.14/yesod-core-1.6.18/Yesod-Core.html#v:isAuthorized) should never touch the request body?

To me those use-cases are things I run into all the time and are legitimate (especially authentication checks like HMAC on a body). To me it's OK that WAI doesn't handle all use-cases perfectly in order to support the streaming one, but I don't think it's fair to call them "bad behavior".

tbc, I don't support a breaking API change either, but I would support something like deprecating the existing functions in favor of ones with a different name, similar to [`requestBody`](https://hackage.haskell.org/package/wai-3.2.2.1/docs/Network-Wai.html#v:requestBody) being deprecated in favor of `getRequestBodyChunk`.

**Comment by snoyberg** [comment]
Bad behavior means holding data in memory when it isn't necessary. Most of the time, it isn't necessary. There are certainly cases where it is necessary. But talking about them as workarounds instead of necessary evils will encourage bad behavior.

I'm ok with introducing docs to clarify the situation. I'm ok with adding new functions with clearer names. I'm semi OK with deprecating the old ones. And I'm ok with helper functions or docs as long as they make clear that holding onto a request body is both inefficient and, if done incorrectly, a massive security hole.

**Comment by MaxGabriel** [comment]
Ok cool, writing up some docs. The main security hole I envision is being vulnerable to a DDOS attack, since data could be kept in memory for longer. Is there also a concern about e.g. keeping plaintext passwords in memory longer than necessary or something like that that I'm missing?

**Comment by snoyberg** [comment]
No, I was thinking of the DDoS attack. But it's really just a DoS attack: a single machine can trivially take down a server.
