### ISSUE TITLE
wai-app-static: Allow handling of methods other than GET/HEAD

### ISSUE THREAD

**Issue by saurabhnanda** [yesodweb/wai#819]
I think I have hit an issue similar to #715. I'm trying to compose a Scotty application with wai-app-static, with wai-app-static being the first application in the Wai "chain".

wai-app-static has an `ss404Handler` which narrowly handles only those requests that are deemed worthy of a 404 by wai-app-static. In the case of a `POST` request, it summarily reject the request with a 405 and stops all further processing.

Would you be open to a PR that introduces an `ssUnhandledRequestHandler` that would take care of request that are deemed "out of scope' for wai-app-static?

**Comment by snoyberg** [comment]
I don't really understand from this issue what the problem is, so I can't comment.

**Comment by saurabhnanda** [comment]
@snoyberg do the changes in #820 make the issue and it's resolution clearer?

**Comment by snoyberg** [comment]
Sort of. It seems like you're trying to convert this project into a middleware, when it was never designed for that use case. I'm hesitant to start adding hacks in to address a use case the library was never designed for in the first place.

I would recommend instead having a middleware in front of wai-app-static that checks its responses and then falls back to a different application on 404 or 405 responses.

**Comment by saurabhnanda** [comment]
Hmm, I thought this was a logical extension of the existing `ss404Handler`.

Nevertheless, would you be able to point me to an example where a middleware executes multiple applications and decides which response is sent back to the browser/client?

**Comment by snoyberg** [comment]
I don't have such an example available, sorry.

**Comment by Vlix** [comment]
Added example in #820 of having a different app catching methods other than `GET/HEAD`.
