### ISSUE TITLE
Please remove template haskell dependency from wai-websockets

### ISSUE THREAD

**Issue by IfSixWasNine** [yesodweb/wai#821]
The Network.Wai.Handler.WebSockets module (being content of the wai-websockets package) does obviously not use code from the wai-app-static package, but it references this latter package as dependency. As a consequence, it has a dependency on template haskell which is painful for cross compiling.

Please remove this dependency for avoiding cross-compiling complexity.

**Comment by snoyberg** [comment]
PR welcome

**Comment by IfSixWasNine** [comment]
I've now detected the cause of the problem. It is due to the setting of the 'example' flag which is enabled by default.
Consequently, the only change that I'd propose is to disable this flag by default as this is probably a more suitable setting for the majority of the use cases and then this issue can be closed again.
