### ISSUE TITLE
Vault is always empty on setOnException

### ISSUE THREAD

**Issue by Valdsonjr** [yesodweb/wai#824]
OS : Windows 10 Home
Cabal: 3.2.0.0
ghc: 8.8.4

Description: ```lookup key vault``` aways returns Nothing inside setOnException. Am I missing something?

example:

```haskell
module Main where

import qualified Data.Vault.Lazy as V
import Control.Exception
import Network.Wai
import Network.Wai.Handler.Warp

traceIdMiddleware :: V.Key Int -> Middleware
traceIdMiddleware k application req =
    application (req { vault = V.insert k 10 $ vault req })

customLog :: V.Key Int -> Maybe Request -> SomeException -> IO ()
customLog k mReq _ = do
    putStr "On Exception: "
    print (V.lookup k . vault =<< mReq)

app :: V.Key Int -> Application
app k req _= do
    putStr "On Application: "
    print $ V.lookup k $ vault req
    error "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"

main :: IO ()
main = do
    traceIdKey <- V.newKey
    let settings = setOnException (customLog traceIdKey)
            $ setPort 8080 defaultSettings
    runSettings settings (traceIdMiddleware traceIdKey (app traceIdKey))

```
Expectation:
![image](https://user-images.githubusercontent.com/6580116/99159312-0d122e80-26ba-11eb-8d3b-50f10fd803d4.png)

Reality:
![image](https://user-images.githubusercontent.com/6580116/99159197-33839a00-26b9-11eb-89bc-4a7bd00538c5.png)

**Comment by snoyberg** [comment]
That's the way it's expected to work. The Vault is not stored in a mutable variable.

**Comment by Valdsonjr** [comment]
I'm not sure I understood you, shouldn't `setOnException` (in case of an exception) receive the same request that went in the app function?

Anyway, thank you and can you tell me what is the recommended way to do what i'm trying to do? (generating an unique id for every request to be logged in case of an exception)

**Comment by snoyberg** [comment]
Yes, it's exactly the same request. But you've "modified" the vault by creating a new request value and putting in a modified vault value. Warp doesn't have access to that.

You should ideally not rely on `setOnException`, but rather catch applications yourself and then handle them. That's what frameworks like Yesod do.

**Comment by Valdsonjr** [comment]
Thank you for the explanation

**Comment by darrell-roberts** [comment]
Is this also true for `setLogger`? In my case I had created Middleware to generate a UUID for each request and store it in vault. This is used to correlate logs for individual requests. It seems though the function provided to `setLogger` is unable to extract from vault.

**Comment by snoyberg** [comment]
Yes the same logic would apply

**Comment by darrell-roberts** [comment]
@snoyberg Thanks for the prompt reply. And of course thank-you for all your Haskell contributions. 

I suspect what I can do to retain this `UUID` I'm putting in the `Request` vault for error logging is to add `Middleware` that has a catch all with a re-throw.

```haskell

getRequestId ∷ Request → Maybe UUID
getRequestId req = V.lookup requestIdKey (vault req)

exceptionLogger ∷ AppContext → Middleware
exceptionLogger ctx application req resFunc = do
  result <- tryAny (application req resFunc)
  case result of
    Left e  -> do
      logError ctx (getRequestId req) $
        "Error on Request: "
          <> getRequestUrl req
          <> pack (displayException e)
      throwIO e
    Right r -> pure r

main :: IO ()
main =
  ...
  runSettings (warpSettings ctx) $
    requestIdMiddleware ctx $
    logStartMiddleware ctx $
    exceptionLogger ctx $
    gzip def $
    app ctx


```
This seems to give me what I need however with what I read on an article [you wrote on exceptions in Haskell](https://www.fpcomplete.com/blog/2016/11/exceptions-best-practices-haskell/) I question if I got this right. I'm also wondering if this is not a misuse of `Middleware`.

**Comment by snoyberg** [comment]
Overall seems right.
