### ISSUE TITLE
TimeoutThread exceptions in 3.3.16, what to do with them in my application?

### ISSUE THREAD

**Issue by magthe** [yesodweb/wai#852]
When making the switch 3.3.15 -> 3.3.16 I noticed that my application's "uncaught exception handler" started receiving `TimeoutThread` exceptions for the first time. As I'm not really sure what I as an application writer should do with them I have to ask, was that intentional?

I suspect maybe the change  https://github.com/yesodweb/wai/commit/45e76481a5297aadf46241e5e4dbab197fe83211 could be the cause of it :thinking:

**Comment by snoyberg** [comment]
Please see #851. Can you try out version 3.3.17?

**Comment by magthe** [comment]
Ah yes that should be easily done. Thanks!

**Comment by magthe** [comment]
Yes, 3.3.17 seems good. :smiley: 

Thanks for your help!
