### ISSUE TITLE
Question: should the `InvalidRequest` exception type be ignored by middlewares?

### ISSUE THREAD

**Issue by chrisdone-artificial** [yesodweb/wai#876]
## Scenario

I have a middleware with a `catchAny` (of `safe-exceptions`), that catches everything apart from async exceptions, the problem is logged, and then a 500 status is returned.

```haskell
 exceptionHandlingMiddleware :: Wai.Middleware 
 exceptionHandlingMiddleware innerApp request reply = do 
   catchAny 
     (innerApp request reply) 
     ( \exception -> do 
         log $ EndpointException $ fromString $ show exception 
         -- We intentionally don't share with the world what the 
         -- actual error was. 
         reply (Wai.responseLBS Http.status500 [] "An internal exception occurred.") 
     ) 
```

Pretty much following the advice under here:

https://github.com/yesodweb/wai/blob/40a53a88074c96a7bd2bc55f825324178836fd00/warp/Network/Wai/Handler/Warp.hs#L174-L182

## Result

I've found that `Warp: Client closed connection prematurely` is now being logged once in a while in production. Not often, just every couple days. I looked that up in warp and found it comes from the `InvalidRequest` type:

https://github.com/yesodweb/wai/blob/40a53a88074c96a7bd2bc55f825324178836fd00/warp/Network/Wai/Handler/Warp/Types.hs#L36-L52

It could be thrown here,

https://github.com/yesodweb/wai/blob/40a53a88074c96a7bd2bc55f825324178836fd00/warp/Network/Wai/Handler/Warp/Request.hs#L118

or here,

https://github.com/yesodweb/wai/blob/517d96b881acf7992a58e9aa8fbc88271130ea2f/warp-tls/Network/Wai/Handler/WarpTLS.hs#L319

But I wasn't able to directly reproduce it via some intentionally bad requests via `nc`.

## Conclusions

In any case, should I just consider this exception to be internal to warp or part of its own control flow, and ignore it in my `catchAny`? It feels to me like an everyday HTTP error and not something worth logging as something wrong with the app.

**Comment by snoyberg** [comment]
> should I just consider this exception to be internal to warp or part of its own control flow, and ignore it

That seems reasonable to me.
