### ISSUE TITLE
wai-extra-3.1.12 testsuite failure: WaiExtra.Network.Wai.gzip gzip checking of files

### ISSUE THREAD

**Issue by juhp** [yesodweb/wai#886]
In the Stackage Nightly build:
```
Test suite failure for package wai-extra-3.1.12                   
    spec:  exited with: ExitFailure 1  
:
:
    Failures:
     
      test/WaiExtraSpec.hs:313:9:  
      1) WaiExtra.Network.Wai.gzip gzip checking of files
           Expected header "Content-Encoding" to be "gzip", but it was not present
     
      To rerun use: --match "/WaiExtra/Network.Wai/gzip/gzip checking of files/"
     
    Randomized with seed 606399493
     
    Finished in 3.0131 seconds
    126 examples, 1 failure
```

**Comment by snoyberg** [comment]
@Vlix any thoughts?

**Comment by Vlix** [comment]
Hmmm, only with the Nightly build? :thinking: 
I'll have to run the tests locally to find out what's going on. Will try to come back to this ASAP.

**Comment by juhp** [comment]
Okay if it's not reproducible I would say don't worry too much about it for now.

**Comment by felixonmars** [comment]
I am also getting the same failure reliably with either wai-extra 3.1.11 or 3.1.12 on Arch Linux. It probably has something to do with https://github.com/yesodweb/wai/pull/880

**Comment by felixonmars** [comment]
Update: Figured it out. The tests run successfully from the git repository but not the hackage tarball because `test/json.gz` and `test/noprecompress` aren't present in the latter.

**Comment by Vlix** [comment]
> Update: Figured it out. The tests run successfully from the git repository but not the hackage tarball because `test/json.gz` and `test/noprecompress` aren't present in the latter.

Ah, so it was me being dumb! Thankfully not in the code 🤦 I somehow always forget `extra-source-files` 😞

**Comment by juhp** [comment]
Already in lts19 btw:
https://www.stackage.org/lts-19.7/package/wai-extra-3.1.12.1
