### ISSUE TITLE
warp-tls: offer the possibility to provide our own data to the library via some hooks or `Connection` object

### ISSUE THREAD

**Issue by jecaro** [yesodweb/wai#907]
I'm working on a low level network application. And basically I'd need to pass some buffered data straight to warp-tls instead of having it fetching from client sockets.

Ideally, I'd need to have some kind of interface or hooks in the like of `Connection` objects so I can pass my data to warp-tls. I understand this is not possible right now. FWIU of the code, warp-tls performs some low level operations on the client socket before creating such `Connection` object and running warp on it.

I'm asking for advice & ideas here. Would that be possible to provide such an interface for warp-tls ? How difficult it would be ? Any other available approaches that I missed to address this issue ?

**Comment by kazu-yamamoto** [comment]
The `tls` package has `Backend`: https://hackage.haskell.org/package/tls-1.6.0/docs/Network-TLS.html#g:2

Would you give a look at `Backend` first? It's quite easy to extend `warp-tls` to specify `Backend` to `tls`, I guess.

**Comment by jecaro** [comment]
Thx for pointing this. 

That looks like a better idea. And for handling plain HTTP, one can create the required `Connection` from the TLS `Backend`, just like it's done for HTTP over TLS. Indeed, I think that could work. 

Would you be interested in a PR on that feature ?

**Comment by kazu-yamamoto** [comment]
Yes, of course!

**Comment by jecaro** [comment]
Closing as #912 solves this issue
