### ISSUE TITLE
warp fails to build with unix ^>=2.8 even though cabal file claims to support any version

### ISSUE THREAD

**Issue by Merivuokko** [yesodweb/wai#908]
warp fails to build with a recent unix version (>= 2.8) which breaks the old API.

The error is in warp/Network/Wai/Handler/Warp/FdCache.hs on line 70 and can be simply fixed by deleting the "Nothing" argument from the function call to openFd.

This is made more annoying by cabal file claiming to support any version of the unix package.

Note (for testing) that unix-compat also needs some patching in order to compile with unix 2.8.

unit >=2.8 is necessary for packages that utilize AFPP (Abstract filepath proposal) support.

**Comment by hasufell** [comment]
That seems tobe fixed: https://github.com/yesodweb/wai/commit/7ce2a02ad2991a49f3304550645587e7bec153d7

@kazu-yamamoto

**Comment by kazu-yamamoto** [comment]
Thanks. Let's close this.
