### ISSUE TITLE
warp: test-suite: uses but does not depend on curl

### ISSUE THREAD

**Issue by itd0** [yesodweb/wai#910]
Dear maintainer,

it would be great if `warp`'s test-suite `spec` would express its dependency on the tool `curl`.
(Which is used, e.g., [here](https://github.com/yesodweb/wai/blob/46142591534cb848a2c653ae4e6f813d5ee6e350/warp/test/WithApplicationSpec.hs#L23).)

Thanks!

Regards
itd

**Comment by Vlix** [comment]
Do you mean you'd like a comment above the `spec` function saying so? Or somewhere else?

**Comment by Vlix** [comment]
#939 has made it very obvious why tests might fail if `curl` is missing. This seems to be the best we can do at the moment. So until anyone demands more, I'll close this issue.
