### ISSUE TITLE
Regression in graceful shutdown in warp > 3.3.21

### ISSUE THREAD

**Issue by swamp-agr** [yesodweb/wai#924]
### Bug Report

- Since the project migration from `nightly-2022-09-21` (which points to `warp-3.3.21`) to `lts-20.3` (which points to `warp-3.3.24`) (as you can see, `stack` is a build tool) `warp` stopped from being shut down gracefully. It started to throw a following exception spontaneously during graceful shutdown:

    ```
    modifyFdOnce: invalid argument (Bad file descriptor) (IOException)
    ```

- I was not able to come up with a minimal reproducible.

- Speaking of custom setup, the application is running on Linux and managed as a service via `systemd`.

## What is known

- `modifyFdOnce` is used by GHC `EventManager`. 
- Therefore, it could be triggered via `threadWait*` functions either in `warp` (directly) or from `network` (indirectly). 
- At the same time, we had not traced where it's coming from it yet. It is difficult to make a conclusion what exactly happens.

@kazu-yamamoto do you have any thoughts of how the latest changes (e.g. `recv`) could introduce such a regression?

**Comment by kazu-yamamoto** [comment]
`recv` was just an extracted library from `warp`. So, I don't think it is related to this issue.

Would you tell me your old and new version of `network`?

**Comment by swamp-agr** [comment]
Sure: 
- nightly-2022-09-21: `network-3.1.2.7`.
- current one: `network-3.1.2.8`.

**Comment by kazu-yamamoto** [comment]
There is only one relating commit: https://github.com/haskell/network/commit/9529569bb35e6527f52c613cdd9266d851469b31
But I'm not sure that this is the source of this problem.

@swamp-agr Could you use network-3.1.2.7 in your environment to check if this issue does not happen?

**Comment by kazu-yamamoto** [comment]
I'm going to release `http2` v4.1.0 today. 
This version fixed many bugs.
So, if your clients are using HTTP/2, it's worth trying.

Also, would you tell me whether or not you are using QUIC?

**Comment by swamp-agr** [comment]
- Yes, we will try downgrading to `3.1.2.7` in the meantime. I checked that commit and it does not look suspicious for me too.
- No, we are using `HTTP/1.1`. I should specify the protocol in the first place. My apologies.

**Comment by kazu-yamamoto** [comment]
@swamp-agr Any progress?

**Comment by swamp-agr** [comment]
@kazu-yamamoto I have to admit that I have difficulties with reproducing issue on a separate environment rather than a production. I am planning to work on a minimal reproducible case to address that.

**Comment by kazu-yamamoto** [comment]
@swamp-agr Again, any progress?

**Comment by swamp-agr** [comment]
Closing as lack of resources / priority to look into tihs. Also workaround (outside of Haskell) has been applied on our side.
