### ISSUE TITLE
warp-tls 3.3.7 is not compatible with warp-tls 3.3.6, contradicting the intended use of PVP

### ISSUE THREAD

**Issue by exarkun** [yesodweb/wai#932]
warp-tls 3.3.7 switches from cryptonite to crypton (#931).  This is an incompatible change because the types from cryptonite are part of the warp-tls exposed interface.

A consumer of warp-tls which still uses cryptonite and which worked with warp-tls 3.3.6 will be broken with warp-tls 3.3.7 because the types from cryptonite will not unify with the types from crypton.

warp-tls 3.3.7 should instead have been versioned as warp-tls 3.4.0 or warp-tls 4.0.0 to indicate this incompatibility.

**Comment by kazu-yamamoto** [comment]
@exarkun Sorry for your inconvenience.
@snoyberg If you agree, I will follow @exarkun's suggestion and make v3.3.7 deprecated on Hackage.

**Comment by snoyberg** [comment]
I'm fine either way.

**Comment by kazu-yamamoto** [comment]
@snoyberg Thanks.

@exarkun `warp-tls` v3.4.0 is out there and v3.3.7 has been deprecated. Please check it out.

**Comment by Vlix** [comment]
I feel like this has been handled as best as can be. Closing issue.
