### ISSUE TITLE
can't install warp-tls.3.3.6 in macOS

### ISSUE THREAD

**Issue by lenohard** [yesodweb/wai#936]
### Bug Reports
the error when built warp-tls.3.3.6

cmd:  cabal install warp-tls.3.3.6
output: 

Build profile: -w ghc-9.2.8 -O1
In order, the following will be built (use -v for more details):
 - warp-tls-3.3.6 (lib) (requires build)
Starting     warp-tls-3.3.6 (lib)
Building     warp-tls-3.3.6 (lib)

Failed to build warp-tls-3.3.6.
Build log ( /Users/senaca/.cabal/logs/ghc-9.2.8/wrp-tls-3.3.6-461b631a.log ):
Configuring library for warp-tls-3.3.6..
Preprocessing library for warp-tls-3.3.6..
Building library for warp-tls-3.3.6..
[1 of 2] Compiling Network.Wai.Handler.WarpTLS.Internal ( Network/Wai/Handler/WarpTLS/Internal.hs, dist/build/Network/Wai/Handler/WarpTLS/Internal.o, dist/build/Network/Wai/Handler/WarpTLS/Internal.dyn_o )
[2 of 2] Compiling Network.Wai.Handler.WarpTLS ( Network/Wai/Handler/WarpTLS.hs, dist/build/Network/Wai/Handler/WarpTLS.o, dist/build/Network/Wai/Handler/WarpTLS.dyn_o )

Network/Wai/Handler/WarpTLS.hs:244:36: error:
    • Couldn't match type ‘DH.Params’
                     with ‘crypton-0.33:Crypto.PubKey.DH.Params’
      Expected: Maybe TLS.DHParams
        Actual: Maybe DH.Params
      NB: ‘crypton-0.33:Crypto.PubKey.DH.Params’
            is defined in ‘Crypto.PubKey.DH’ in package ‘crypton-0.33’
          ‘DH.Params’
            is defined in ‘Crypto.PubKey.DH’ in package ‘cryptonite-0.30’
    • In the ‘serverDHEParams’ field of a record
      In the expression:
        def
          {TLS.serverWantClientCert = tlsWantClientCert,
           TLS.serverCACertificates = [],
           TLS.serverDHEParams = tlsServerDHEParams, TLS.serverHooks = hooks,
           TLS.serverShared = shared, TLS.serverSupported = supported,
           TLS.serverEarlyDataSize = 2018}
      In an equation for ‘params’:
          params
            = def
                {TLS.serverWantClientCert = tlsWantClientCert,
                 TLS.serverCACertificates = [],
                 TLS.serverDHEParams = tlsServerDHEParams, TLS.serverHooks = hooks,
                 TLS.serverShared = shared, TLS.serverSupported = supported,
                 TLS.serverEarlyDataSize = 2018}
    |
244 |       , TLS.serverDHEParams      = tlsServerDHEParams
    |                                    ^^^^^^^^^^^^^^^^^^
cabal: Failed to build warp-tls-3.3.6. See the build log above for details.

* Your OS name and version
  Apple Silicon macOS 13.4.1
* The versions of tools you're using (e.g. `stack`, `ghc`).
 ghcup installation and cabal to install lambdabot
* The versions of dependencies you're using
 warp-tls.3.6.6 build error

command -v sw_vers && sw_vers # Only for OS X
ProductName:            macOS
ProductVersion:         13.4.1
BuildVersion:           22F82

command -v uname && uname -a # Kernel version
 /usr/bin/uname
Darwin PlatoMac 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

command -v stack && stack --version
/Users/senaca/.ghcup/bin/stack
Version 2.9.3, Git revision d0e984f00034552aac7c67675d49ef0807c10c7b (dirty) (112 commits) aarch64
Compiled with:
- Cabal-3.6.3.0
- Cabal-syntax-3.8.1.0
- Glob-0.10.2
- OneTuple-0.3.1
- QuickCheck-2.14.2
- StateVar-1.2.2
- aeson-2.0.3.0
- annotated-wl-pprint-0.7.0
- ansi-terminal-0.11.4
- ansi-wl-pprint-0.6.9
- appar-0.1.8
- array-0.5.4.0
- asn1-encoding-0.9.6
- asn1-parse-0.9.5
- asn1-types-0.3.4
- assoc-1.0.2
- async-2.2.4
- attoparsec-0.14.4
- attoparsec-0.14.4
- attoparsec-iso8601-1.1.0.0
- auto-update-0.1.6
- base-4.16.3.0
- base-compat-0.12.2
- base-compat-batteries-0.12.2
- base-orphans-0.8.7
- base16-bytestring-1.0.2.0
- base64-bytestring-1.2.1.0
- basement-0.0.15
- bifunctors-5.5.14
- binary-0.8.9.0
- bitvec-1.1.3.0
- blaze-builder-0.4.2.2
- blaze-html-0.9.1.2
- blaze-markup-0.8.2.8
- byteorder-1.0.4
- bytestring-0.11.3.1
- casa-client-0.0.1
- casa-types-0.0.2
- case-insensitive-1.2.1.0
- cereal-0.5.8.3
- clock-0.8.3
- colour-2.3.6
- comonad-5.0.8
- conduit-1.3.4.3
- conduit-combinators-1.3.0
- conduit-extra-1.3.6
- connection-0.3.1
- containers-0.6.5.1
- contravariant-1.5.5
- cookie-0.4.5
- cryptohash-sha256-0.11.102.1
- cryptonite-0.30
- cryptonite-conduit-0.2.2
- data-default-class-0.1.2.0
- data-fix-0.3.2
- deepseq-1.4.6.1
- digest-0.0.1.4
- directory-1.3.6.2
- distributive-0.6.2.1
- dlist-1.0
- easy-file-0.2.2
- echo-0.1.4
- ed25519-0.0.5.0
- exceptions-0.10.4
- extra-1.7.12
- fast-logger-3.1.1
- file-embed-0.0.15.0
- filelock-0.1.1.5
- filepath-1.4.2.2
- fsnotify-0.4.1.0
- generic-deriving-1.14.2
- ghc-bignum-1.2
- ghc-boot-th-9.2.4
- ghc-prim-0.8.0
- githash-0.1.6.3
- hackage-security-0.6.2.3
- hashable-1.4.1.0
- hfsevents-0.1.6
- hi-file-parser-0.1.3.0
- hourglass-0.2.12
- hpack-0.35.1
- hpc-0.6.1.0
- http-api-data-0.5
- http-client-0.7.13.1
- http-client-tls-0.3.6.1
- http-conduit-2.3.8
- http-download-0.2.0.0
- http-types-0.12.3
- indexed-traversable-0.1.2
- indexed-traversable-instances-0.1.1.1
- infer-license-0.2.0
- integer-gmp-1.1
- integer-logarithms-1.0.3.1
- iproute-1.7.12
- libyaml-0.1.2
- lift-type-0.1.1.1
- lifted-base-0.2.3.12
- lukko-0.1.1.3
- megaparsec-9.3.0
- memory-0.18.0
- microlens-0.4.13.1
- microlens-mtl-0.2.0.3
- microlens-th-0.4.3.11
- mime-types-0.1.1.0
- mintty-0.1.4
- monad-control-1.0.3.1
- monad-logger-0.3.37
- monad-loops-0.4.3
- mono-traversable-1.0.15.3
- mtl-2.2.2
- mtl-compat-0.2.2
- mustache-2.4.1
- neat-interpolation-0.5.1.3
- network-3.1.2.7
- network-uri-2.6.4.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- open-browser-0.2.1.0
- optparse-applicative-0.17.0.0
- optparse-simple-0.1.1.4
- pantry-0.8.1
- parsec-3.1.15.0
- parser-combinators-1.3.0
- path-0.9.2
- path-io-1.7.0
- path-pieces-0.2.1
- pem-0.2.4
- persistent-2.13.3.5
- persistent-sqlite-2.13.1.0
- persistent-template-2.12.0.0
- pretty-1.1.3.6
- primitive-0.7.4.0
- process-1.6.13.2
- project-template-0.2.1.0
- random-1.2.1.1
- resource-pool-0.3.1.0
- resourcet-1.3.0
- retry-0.9.3.0
- rio-0.1.22.0
- rio-orphans-0.1.2.0
- rio-prettyprint-0.1.4.0
- rts-1.0.2
- safe-0.3.19
- safe-exceptions-0.1.7.3
- scientific-0.3.7.0
- semialign-1.2.0.1
- semigroupoids-5.3.7
- semigroups-0.20
- silently-1.2.5.3
- socks-0.6.1
- split-0.2.3.5
- splitmix-0.1.0.4
- stm-2.5.0.2
- stm-chans-3.0.0.6
- streaming-commons-0.2.2.5
- strict-0.4.0.1
- syb-0.7.2.2
- tagged-0.8.6.1
- tar-0.5.1.1
- tar-conduit-0.3.2
- template-haskell-2.18.0.0
- temporary-1.3
- text-1.2.5.0
- text-metrics-0.3.2
- text-short-0.1.5
- th-abstraction-0.4.5.0
- th-compat-0.1.4
- th-expand-syns-0.4.10.0
- th-lift-0.8.2
- th-lift-instances-0.1.20
- th-reify-many-0.1.10
- these-1.1.1.1
- time-1.11.1.1
- time-compat-1.9.6.1
- tls-1.6.0
- transformers-0.5.6.2
- transformers-base-0.4.6
- transformers-compat-0.7.2
- typed-process-0.2.10.1
- unicode-data-0.4.0
- unicode-transforms-0.4.0.1
- unix-2.7.2.2
- unix-compat-0.6
- unix-time-0.4.8
- unliftio-0.2.23.0
- unliftio-core-0.2.0.1
- unordered-containers-0.2.19.1
- uuid-types-1.0.5
- vault-0.3.1.5
- vector-0.13.0.0
- vector-algorithms-0.9.0.1
- vector-stream-0.1.0.0
- witherable-0.4.2
- x509-1.7.7
- x509-store-1.6.9
- x509-system-1.6.7
- x509-validation-1.6.12
- yaml-0.11.8.0
- zip-archive-0.4.2.2
- zlib-0.6.3.0
Warning: this is an unsupported build that may use different versions of
dependencies and GHC than the officially released binaries, and therefore may
not behave identically.  If you encounter problems, please try the latest
official build by running 'stack upgrade --force-download'.

command -v stack && stack ghc -- --version
The Glorious Glasgow Haskell Compilation System, version 9.4.5

**Comment by kazu-yamamoto** [comment]
You are using too old `warp`.
Please use the latest one.

**Comment by lenohard** [comment]
Thanks for your reply.

I am interested in constructing lambdabot, but cabal is unable to build hoogle due to a dependency called warp-tls.3.3.6, which cannot be built by cabal for an unknown reason.

I am unable to use 'stack init' to locate a matching snapshot for installing lambdabot.

After changing it to warp-tls.3.4.0, the dependencies of hooogle cannot be satisfied, at least not manually.
However, I can utilize "stack init" to locate a compatible snapshot that satisfies the dependency for hoogle after I modify it to "warp-tls.3.4.0".

I. have try to set the warp == 3.3.28 both in warp-tls.3.36 and hoogle.5.0.18.3 
for warp-tls the error is:
`    • Couldn't match type ‘DH.Params’
                     with ‘crypton-0.33:Crypto.PubKey.DH.Params’
      Expected: Maybe TLS.DHParams
        Actual: Maybe DH.Params
      NB: ‘crypton-0.33:Crypto.PubKey.DH.Params’
            is defined in ‘Crypto.PubKey.DH’ in package ‘crypton-0.33’
          ‘DH.Params’
            is defined in ‘Crypto.PubKey.DH’ in package ‘cryptonite-0.30’
    • In the ‘serverDHEParams’ field of a record
      In the expression:
        def
          {TLS.serverWantClientCert = tlsWantClientCert,
           TLS.serverCACertificates = [],
           TLS.serverDHEParams = tlsServerDHEParams, TLS.serverHooks = hooks,
           TLS.serverShared = shared, TLS.serverSupported = supported,
           TLS.serverEarlyDataSize = 2018}
      In an equation for ‘params’:
          params
            = def
                {TLS.serverWantClientCert = tlsWantClientCert,
                 TLS.serverCACertificates = [],
                 TLS.serverDHEParams = tlsServerDHEParams, TLS.serverHooks = hooks,
                 TLS.serverShared = shared, TLS.serverSupported = supported,
                 TLS.serverEarlyDataSize = 2018}
    |
244 |       , TLS.serverDHEParams      = tlsServerDHEParams
    |                                    ^^^^^^^^^^^^^^^^^^
`
for hoogle the error is:
`
Network/Wai/Handler/WarpTLS.hs:389:40: error:
    • Couldn't match type ‘x509-1.7.7:Data.X509.CertificateChain.CertificateChain’
                     with ‘crypton-x509-1.7.6:Data.X509.CertificateChain.CertificateChain’
      Expected: Maybe
                  crypton-x509-1.7.6:Data.X509.CertificateChain.CertificateChain
        Actual: Maybe
                  x509-1.7.7:Data.X509.CertificateChain.CertificateChain
      NB: ‘crypton-x509-1.7.6:Data.X509.CertificateChain.CertificateChain’
            is defined in ‘Data.X509.CertificateChain’
                in package ‘crypton-x509-1.7.6’
          ‘x509-1.7.7:Data.X509.CertificateChain.CertificateChain’
            is defined in ‘Data.X509.CertificateChain’ in package ‘x509-1.7.7’
    • In the ‘tlsClientCertificate’ field of a record
      In the first argument of ‘return’, namely
        ‘TLS
           {tlsMajorVersion = major, tlsMinorVersion = minor,
            tlsNegotiatedProtocol = proto,
            tlsChiperID = TLS.cipherID infoCipher,
            tlsClientCertificate = clientCert}’
      In a stmt of a 'do' block:
        return
          TLS
            {tlsMajorVersion = major, tlsMinorVersion = minor,
             tlsNegotiatedProtocol = proto,
             tlsChiperID = TLS.cipherID infoCipher,
             tlsClientCertificate = clientCert}
    |
389 |               , tlsClientCertificate = clientCert
    |                                        ^^^^^^^^^^
cabal: Failed to build warp-tls-3.3.6 (which is required by exe:hoogle from
hoogle-5.0.18.3). See the build log above for details.
` (this is the error that I met when directly run 'cabal install lambdabot

**Comment by bo-tato** [comment]
I got this error also trying to `cabal install hoogle`, it seems it installs an old version of warp-tls as warp-tls-3.4.0 depends on tls-1.7 and hoogle depends on connection which depends on tls <1.7. I also ran into [this issue](https://github.com/snoyberg/http-client/issues/511) and was able to install hoogle with versions:
`cabal install hoogle-5.0.18.3 warp-3.3.23 http-conduit-2.3.8.2 aeson-2.1.2.1`

warp-tls should have it's dependency on `warp (>=3.3.23 && <3.4)` updated to be only the range of warp versions it can actually build with?

**Comment by kazu-yamamoto** [comment]
One way to fix this is that `hoogle` uses `crypton-connection`.
We decided that WAI-related packages use `crypton` families instead of `cryptonite`.
If the third party packages use WAI, please migrate to `crypton` families.
We know it's a pain.
Sorry for your inconvenience.
But it was unavoidable.

**Comment by lenohard** [comment]
> I got this error also trying to `cabal install hoogle`, it seems it installs an old version of warp-tls as warp-tls-3.4.0 depends on tls-1.7 and hoogle depends on connection which depends on tls <1.7. I also ran into [this issue](https://github.com/snoyberg/http-client/issues/511) and was able to install hoogle with versions: `cabal install hoogle-5.0.18.3 warp-3.3.23 http-conduit-2.3.8.2 aeson-2.1.2.1`
> 
> warp-tls should have it's dependency on `warp (>=3.3.23 && <3.4)` updated to be only the range of warp versions it can actually build with?

it works !
`
cabal install lambdabot lambdabot-haskell-plugins-5.3.1 hoogle-5.0.18.3 warp-3.3.23 http-conduit-2.3.8.2 aeson-2.1.2.1 
`
this is the cmd for my purpose based on your solution, thanks a lot !
