### ISSUE TITLE
wai-extra: Safe handling of temp files that exceed configured limits

### ISSUE THREAD

**Issue by ocramz** [yesodweb/wai#963]
[`parseRequestBodyEx`](https://hackage.haskell.org/package/wai-extra-3.1.13.0/docs/src/Network.Wai.Parse.html#parseRequestBodyEx) contains calls to `error` that will crash a server if it handles file requests that exceed limits; this behaviour seems to be a Denial of Service but with extra steps.

What if we had a safe variant of `parseRequestBodyEx` that instead throws an exception ~~or accumulates file limit violations~~? 

I'd be willing to implement this feature in case.

**Comment by kazu-yamamoto** [comment]
Merged via #972.

**Comment by ocramz** [comment]
Thanks @kazu-yamamoto ! Could you release this on Hackage too, or are you waiting for other patches to get in first? Thanks!

**Comment by kazu-yamamoto** [comment]
@snoyberg Would you give me the upload permission for `wai-extra` to Hackage?

**Comment by snoyberg** [comment]
Absolutely, you should have access now.

**Comment by kazu-yamamoto** [comment]
@snoyberg Thanks.

A new version has been released.

**Comment by ocramz** [comment]
Hi @kazu-yamamoto thank you for releasing so quickly !  However why did you change the version number without updating it in the cabal file and changelog? https://github.com/yesodweb/wai/commit/9d2f7d8cdd499d20cd656f5433d3dbfa94b5d6c2

**Comment by kazu-yamamoto** [comment]
I changed the version in the cabal file since 3.1.14 is not registered on Hackage.
I forgot to update changelog.
