### ISSUE TITLE
HTTP/2 or /3 might not have minor version

### ISSUE THREAD

**Issue by Vlix** [yesodweb/wai#971]
There are some sections in the code that assume `HTTP/2` will be `HTTP/2.0`, and IIRC the RFC allows for the version number to be omitted if it is 0. (at least for `HTTP/2` and `HTTP/3`)

**Comment by kazu-yamamoto** [comment]
In the standardization process, it was called "HTTP/2.0".
Hence we have the prefix ""PRI * HTTP/2.0".
When the process was about to finish, the name is changed to "HTTP/2".
The prefix was not changed because there were a lot of implementation installed.

**Comment by Vlix** [comment]
Ah ok, I see where my misinterpretation happened.

Apologies for the unnecessary issue.
