### ISSUE TITLE
"is http2" detection doesn't seem quite correct

### ISSUE THREAD

**Issue by mitchellwrosen** [yesodweb/wai#989]
https://github.com/yesodweb/wai/blob/2a7399f5229f6a8ea675a20cf0cf8f69ba8b9f72/warp/Network/Wai/Handler/Warp/Run.hs#L390

Here we seem to determine whether this is an HTTP/2 request by reading some bytes off the wire, and if they are `PRI `, it is.

But there's no guarantee we read 4 bytes, of course. We could read `PR`, determine this isn't an HTTP/2 request, go down the HTTP/1 code path and proceed to read the remaining `I `!

**Comment by kazu-yamamoto** [comment]
Right.
But a question is whether or not we should rescue this corner case.

**Comment by mitchellwrosen** [comment]
Why is that a question?

**Comment by kazu-yamamoto** [comment]
Clients to send a few bytes at the beginning seem malicious.
Should we treat them kindly?

**Comment by davean** [comment]
This sounds like an argument for ossification
<https://en.wikipedia.org/wiki/Protocol_ossification> over correctness.
Why shouldn't it be able to handle a semantically correct connection if the
server chooses to?

**Comment by mitchellwrosen** [comment]
@kazu-yamamoto For sure; it's clearly a corner case. Nonetheless, it's exactly the kind of thing I would expect to be handled correctly in a web server!
