### ISSUE TITLE
`Control.Debounce.mkDebounce` might be not debouncing correctly when `Leading`

### ISSUE THREAD

**Issue by Vlix** [yesodweb/wai#993]
```hs
mkDebounceInternal
    :: MVar () -> (Int -> IO ()) -> DebounceSettings -> IO (IO ())
mkDebounceInternal baton delayFn (DebounceSettings freq action edge) = do
    mask_ $ void $ forkIO $ forever $ do
        takeMVar baton
        case edge of
            Leading -> do
                ignoreExc action
                delayFn freq
            Trailing -> do
                delayFn freq
                -- Empty the baton of any other activations during the interval
                void $ tryTakeMVar baton
                ignoreExc action

    return $ void $ tryPutMVar baton ()
```

The `Leading` section doesn't `tryTakeMVar` at all, so if two triggers happen right after another, the first would start the debounced function, and the second would immediately fill the baton causing the function to run after the delay for a second time, even though the trigger happened during the delay.

**Comment by kazu-yamamoto** [comment]
@snoyberg Could you analyze this issue?

**Comment by Vlix** [comment]
There's also the question of, what does `Trailing` mean?

IIRC most trailing debouncing will postpone the execution of the action until NO triggers have happened during the delay (when `Trailing`), but that will make this more complicated as well. So it depends on the goal, but the documentation should probably be explicit about how the debouncing works.

**Comment by snoyberg** [comment]
I haven't looked at this code in a long while, I don't have any insights. `git blame` led me to this commit:

https://github.com/yesodweb/wai/commit/68d4f8193a007f9bfdd37646d357c5f3013a69c5

CC @thomasjm

**Comment by thomasjm** [comment]
> if two triggers happen right after another, the first would start the debounced function, and the second would immediately fill the baton causing the function to run after the delay for a second time, even though the trigger happened during the delay.

That sounds like correct behavior to me, and consistent with what the Haddocks say will happen.

The PR that introduced this feature is here: https://github.com/yesodweb/wai/pull/756

**Comment by Vlix** [comment]
@thomasjm I didn't think to read the settings docs, which is my bad.

I've talked to some colleagues today about debouncing in general as well, and I've come to realize there's different flavours of debouncing depending on the use case:

- Leading + muting: Fires on first trigger and ignores anything during "cooldown"
- Leading + last guarantee: Fires on first trigger, but will trigger again after cooldown if anything was triggered after the first trigger. (to guarantee it at least always fires for the last trigger)
- Trailing + constant wait: Fires a set waiting period after first trigger, ignoring any triggers between first trigger and firing.
- Trailing + delay: Fires only x amount of time after the last trigger, perpetually redelaying the firing if it gets triggered before the waiting time runs out.

All these flavours have their use cases, so I guess it depends on what we want `Control.Debounce` to be able to do. 🤷

**Comment by thomasjm** [comment]
Right, this library implements "Leading + last guarantee" (`Leading`) and "Trailing + constant wait" (`Trailing`).

Some other flavors could certainly be added. (Not sure about "Trailing + delay" though, that one sounds like a recipe for starvation...)

**Comment by Vlix** [comment]
`Trailing + delay` is something you'd want for something like "trigger on keystrokes and wait until the user has stopped typing for 0.5 seconds and do a call to ElasticSearch to show autocomplete results"
